### ISSUE TITLE
Dart run is not working

### ISSUE THREAD

**Issue by Zaryob** [emacs-lsp/lsp-dart#100]
**Describe the bug**
I'm trying to run a flutter project. When I clicked Run button on main function to run it it give me that error
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/zaryob/.emacs.d/.extension/vscode/Dart-Code.Dart-Code/3.19.2/extension/out/dist/debug.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Process Flutter Run stderr finished
```

I opened a new dart project to test if it is specific for flutter:
```
dart create -t console-full awesome-app
```
then tried again to run. It give me another error:
```
Server dart_analysis_server:20167/starting exited with status exit(check corresponding stderr buffer for details). Do you want to restart it? (y or n) 
```

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages.

- [X] Checked all melpa upgrades.
- [X] Remove `.emacs.d/.extension` then reinitialize lsp-dart with `dap-dart-setup` but not worked 
- [X] Tried several times with cleaning `.emacs.d` directory and reinitialize emacs

Looked up github issues:
[Issue 99](https://github.com/emacs-lsp/lsp-dart/issues/99)

**To Reproduce**
{populate}
I clicked `run` attached onto main function. It opened a buffer to ask which device that I use to run flutter app. This is the list of devices used by flutter
```
Click on a completion to select it.
In this buffer, type RET to select the completion near point.

Possible completions are:
linux - device - Linux
web - device - Chrome
```

I tried both of them but not worked both devices. Gave me same output.

**Expected behavior**
{populate}

**Screenshots**

From flutter project:
![image](https://user-images.githubusercontent.com/22801690/116420072-53151600-a846-11eb-9545-1f57e873db79.png)
output:
![image](https://user-images.githubusercontent.com/22801690/116420159-67f1a980-a846-11eb-80ee-9f21fa81ff32.png)

From dart project:
![image](https://user-images.githubusercontent.com/22801690/116419888-24973b00-a846-11eb-84e8-d517b2490248.png)

**Version**
Include here the result of: <kbd>M-x</kbd> `lsp-dart-version`
{populate}
```
[LSP Dart] 1.18.1 (package: 20210406.2012) at 2021.04.28 @ Emacs 27.2
[Dart SDK] Dart SDK version: 2.13.0-211.6.beta (beta) (Wed Apr 14 13:59:12 2021 +0200) on "linux_x64"
```

**Comment by yyoncho** [comment]
have you performed `M-x dap-dart-setup`?

**Comment by ericdallo** [comment]
☝🏻 @Zaryob

**Comment by Zaryob** [comment]
> have you performed `M-x dap-dart-setup`?

I performed after first install and also after removed vscode extension But not worked.

**Comment by ericdallo** [comment]
The issue is that is not finding the debug js file: `/home/zaryob/.emacs.d/.extension/vscode/Dart-Code.Dart-Code/3.19.2/extension/out/dist/debug.js`, could you check what you have on `/home/zaryob/.emacs.d/.extension/vscode/Dart-Code.Dart-Code/3.19.2/extension/out/dist` or the parent folders?

**Comment by Zaryob** [comment]
> could you check what you have on `/home/zaryob/.emacs.d/.extension/vscode/Dart-Code.Dart-Code/3.19.2/extension/out/dist` or the parent folders?

There are folder named as `~/.extension/vscode/Dart-Code.Dart-Code/3.19.2/` but it is empty. It is message output for `dap-dart-setup`:

```
[/tmp/extFL2ZVY.zip]                                                                                                                                                   
  End-of-central-directory signature not found.  Either this file is not                                                                                               
  a zipfile, or it constitutes one disk of a multi-part archive.  In the                                                                                               
  latter case the central directory and zipfile comment will be found on                                                                                               
  the last disk(s) of this archive.                                                                                                                                    
unzip:  cannot find zipfile directory in one of /tmp/extFL2ZVY.zip or                                                                                                  
        /tmp/extFL2ZVY.zip.zip, and cannot find /tmp/extFL2ZVY.zip.ZIP, period.
```

**Comment by yyoncho** [comment]
most likely you are hitting rate limit of the vscode market place. You may go and download it manually and then unzip the achieve on the proper location.

**Comment by Zaryob** [comment]
> most likely you are hitting rate limit of the vscode market place. You may go and download it manually and then unzip the achieve on the proper location.

Yes thanks @yyoncho . I fix it with  manual way (getting files via curl and extract onto that path) right now 😂 its working.
