### ISSUE TITLE
dap-dart-setup not working.

### ISSUE THREAD

**Issue by eansa1997** [emacs-lsp/lsp-dart#102]
**Describe the bug**
After fresh installing emacs27 and adding a very basic ~/.emacs config with the example provided, running dap-dart-setup appears to be successful. Once I try to run a flutter app on any device, it won't work. It will open an android emulator device but won't do anything at all. Attempting to run a desktop app with linux as the target also fails saying "error in process filter: dap--create-session: Searching for program: No such file or directory, node". 
I deleted the extensions and reran the dap-dart-setup like recommended in a closed issue #99 . Still wouldn't work. 

**Screenshots**
![screen1](https://user-images.githubusercontent.com/42599836/116800489-87e7ce00-aacf-11eb-8bec-9452703ffeda.png)

**Version**
Also, just giving as much info as possible, the dart vscode extension that works is on version 3.21.1 while the one that is downloaded is 3.19.2. Not sure if it makes a difference.

![screen2](https://user-images.githubusercontent.com/42599836/116800504-b2398b80-aacf-11eb-92aa-4e75ce5d08e5.png)

**Comment by ericdallo** [comment]
Could you check Dart stderr output and also check if the debugger was installed properly with the following:
- `M-x` `lsp-dart-dap-dart-debugger-program`
- Check if the returned path exists

You can test a different debugger version by changing `lsp-dart-dap-extension-version`.

**Comment by ericdallo** [comment]
Oh, I'm almost sure this is related with lsp-dart not finding the correct entrypoint for your project. it uses the `lsp-dart-get-project-entrypoint` function to get the correct path. Could you also check the value of it with `M-:` `(lsp-dart-get-project-entrypoint)`?

**Comment by eansa1997** [comment]
Hmmm, I don't have that command available... 
![screen3](https://user-images.githubusercontent.com/42599836/116800803-4c023800-aad2-11eb-9c78-bc1d0df4b695.png)
Also don't have the get-project-entrypoint command...
![screen4](https://user-images.githubusercontent.com/42599836/116800881-e6627b80-aad2-11eb-9874-3bfade595164.png)

**Comment by eansa1997** [comment]
Going to drop my ~/.emacs file to give as much context as possible. 

![screen5](https://user-images.githubusercontent.com/42599836/116800938-6983d180-aad3-11eb-9a83-442b9c5ce655.png)

**Comment by eansa1997** [comment]
An update, using flutter run builds the app just fine and launches the linux app. Very similar to #101 . I'll be building my apps that way for now.

**Comment by ericdallo** [comment]
You should not run as command, you should use `M-:` or `M-x` `eval-expression`

**Comment by eansa1997** [comment]
lsp-dart-dap-dart-debugger-program
![screen6](https://user-images.githubusercontent.com/42599836/116817456-65d46700-ab34-11eb-86e3-8bc31c4c6670.png)
(lsp-dart-get-project-entrypoint)
![screen8](https://user-images.githubusercontent.com/42599836/116817514-b946b500-ab34-11eb-97ec-83412503dd25.png)

**Comment by ericdallo** [comment]
Could you confirm that path exists in your machine and the entrypoint is correct?

**Comment by eansa1997** [comment]
".../debug.js" exists. As does the project entry point.

**Comment by ericdallo** [comment]
Could you test if [this flutter sample](https://github.com/ericdallo/flutter_sample) works for you?

**Comment by eansa1997** [comment]
When I opened main.dart, it asked to import project root. 
![screen10](https://user-images.githubusercontent.com/42599836/116818076-8225d300-ab37-11eb-9735-c0284f4d092e.png)
I chose i .
There are a lot of import errors, but clicking run still gives me the same error with "node". I also made sure to select android emulator as target since the project doesn't have a linux build folder.

**Comment by ericdallo** [comment]
So it seems something wrong with your flutter or debugger downloaded, could you try on flutter stable channel?

**Comment by eansa1997** [comment]
Okay so I was on master 2.3.0 for some reason but switching to stable and running flutter upgrade didn't fix it.

**Comment by eansa1997** [comment]
It seems all the import errors are flutter package errors, all the local imports seem fine. 
![screen11](https://user-images.githubusercontent.com/42599836/116818404-1e9ca500-ab39-11eb-9e3d-315a0e883534.png)

**Comment by ericdallo** [comment]
the errors happen because you didn't run flutter pub get.

Just to confirm the errors is the same from [this first screenshot](https://github.com/emacs-lsp/lsp-dart/issues/102#issue-873822869)

**Comment by eansa1997** [comment]
Okay so I removed a dependency from pubspec.yaml that was a local path and pub get fixed the import issues. I'm so used to not running pub get.. my bad, but yes the same error as the screenshot persists.

**Comment by ericdallo** [comment]
(You can use `lsp-dart-put-get` as well :))

Oh, my bad... I didn't pay the proper attention on the error, the debugger is not finding `node` on your PATH, because under the hood, dap-mode runs `node <path to the debug.js>`.

So, installing node or configuring properly on your emacs path should fix your problem

**Comment by eansa1997** [comment]
Okay so installing nodejs fixed that issue but the debugger can't find flutter on the path which is weird. I verified both flutter and dart work in the terminal.
This is what I used in my ~/.emacs file. 
(setq lsp-dart-sdk-dir "~/dev/flutter/bin/cache/dart-sdk/")
(setq lsp-dart-flutter-sdk-dir "~/dev/flutter/")
Error message:
![screen12](https://user-images.githubusercontent.com/42599836/116819003-2c075e80-ab3c-11eb-8e0a-4baf88f106ec.png)
Thank you for being so helpful.

**Comment by ericdallo** [comment]
Nice!

Hum, only setting `lsp-dart-flutter-sdk-dir` should handle that, not sure you should set it on `:config` of use-package or if both should works

**Comment by ericdallo** [comment]
My config if helps: https://github.com/ericdallo/dotfiles/blob/master/.doom.d/config.el#L157

**Comment by eansa1997** [comment]
Okay so I couldn't fix my vanilla emacs setup, I purged it and installed doom emacs. Just uncommenting what I needed in the ~/.doom.d/init.el file worked. Didn't have to set any paths explicitly. Ill just use doom emacs.. doom sync is really nice.

**Comment by ericdallo** [comment]
Nice, yeah, some default doom improvements helps a lot with performance and UX, LMK if need any more help.
