### ISSUE TITLE
I can't start lsp-dart

### ISSUE THREAD

**Issue by MitaiGit** [emacs-lsp/lsp-dart#104]
Debian 11. Gnome. zsh The Dart and Flutter commands work in the terminal, but when I run Emacs and the flutter project, it writes that it can't find the SDK of either
![Снимок экрана от 2021-06-02 01-25-29](https://user-images.githubusercontent.com/32243762/120386003-836a3b80-c341-11eb-9909-8d1eef014b85.png)
Supported settings#  lsp-dart-flutter-sdk-dir
do you need to write this in .emacs? please give me an example, I have no idea what the actual code should look like, sorry I'm new to emacs...
my way to Flutter /home/mitai/flutter/bin

**Comment by ericdallo** [comment]
Hi, emacs is not finding flutter/dart in your path, you can try [this](https://www.emacswiki.org/emacs/ExecPath) or tell to lsp-dart where the flutter sdk is with `(setq lsp-dart-flutter-sdk-dir "/home/mitai/flutter")` in your init.el

**Comment by MitaiGit** [comment]
in i3wm everything worked without problems...
thank you for your help
