### ISSUE TITLE
Unable to Reload or Restart Dap Debug

### ISSUE THREAD

**Issue by bilemon** [emacs-lsp/lsp-dart#105]
**Describe the bug**
After setting up `lsp-dart`, I am trying to hot restart/reload the application against an Android emulator. While the emulator does _launch_, I am unable to interact with the emulator after it has launched. My cumbersome workaround is to manually invoke `flutter run` and then hot-reload by watching files.

**To Reproduce**
After invoking `lsp-dart-dap-flutter-hot-reload`, I receive the following error:

```
Debugger entered--Lisp error: (wrong-type-argument dap--debug-session nil)
  signal(wrong-type-argument (dap--debug-session nil))
  dap--send-message((:command "hotReload" :type "request") #f(compiled-function (res) #<bytecode -0x139fedd8ebdb172a>) nil)
  dap-request(nil "hotReload")
  lsp-dart-dap--flutter-hot-reload()
  lsp-dart-dap-flutter-hot-reload()
  funcall-interactively(lsp-dart-dap-flutter-hot-reload)
  call-interactively(lsp-dart-dap-flutter-hot-reload record nil)
  command-execute(lsp-dart-dap-flutter-hot-reload record)
  execute-extended-command(nil "lsp-dart-dap-flutter-hot-reload" "lsp-dart-dap-flutter-hot-rel")
  funcall-interactively(execute-extended-command nil "lsp-dart-dap-flutter-hot-reload" "lsp-dart-dap-flutter-hot-rel")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

Presumably this is because `lsp-dart.el` is unable to find the session. I'm not sure if this is due to my own configuration error or if I've uncovered a bug. I cannot find anything unique to my machine which would cause this error, although I will keep looking. Any tips of resolving this would be appreciated.

**Expected behavior**
`lsp-dart-dap-flutter-hot-reload` reload the app in the android emulator

**Version**
[LSP Dart] 1.18.5 at 2021.06.07 @ Emacs 28.0.50
[Dart SDK] Dart SDK Version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "linux_x64"

[Flutter SDK] /opt/flutter
[Flutter project] true
[Project entrypoint] `$PATH_TO/lib/main.dart`

**Comment by ericdallo** [comment]
I could not reproduce the issue with my [flutter_sample](https://github.com/ericdallo/flutter_sample) project that I use for testing/develop. For some reason `(dap--cur-session)` on [this line](https://github.com/emacs-lsp/lsp-dart/blob/master/lsp-dart-dap.el#L311) is returning `nil`, this usually means that there is no dap session running globally on your emacs.

BTW, are you running it via `dap-debug`, right (after running successfully `dap-dart-setup`)?

**Comment by bilemon** [comment]
@ericdallo Thanks for honing in on the line. I'll tinker around with it and let you know if I'm able to resolve it. Love lsp-dart so far btw :smile: 

> BTW, are you running it via dap-debug, right (after running successfully dap-dart-setup)?

Yes, I'm running it via dap-debug after running an initial dap-dart-setup. This allows me to "start" the emulator session, but it seems that it fails to "attach" to the session for any subsequent command.

**Comment by ericdallo** [comment]
@bilemon A few moments ago I released lsp-dart 1.19.0 with few improvements on web debug/debug-setup, could you test it again? but now running `lsp-dart-dap-setup`

**Comment by bilemon** [comment]
@ericdallo Just tried it again, and all is working a-okay. I think this was probably just user error caused by me futzing with some configuration settings in AVD :sweat_smile:.

Anyhow, apologies for any distraction this may have caused. All seems to be working :+1:

**Comment by ericdallo** [comment]
No problem, thanks for the response
