### ISSUE TITLE
replicate vscode behavior 

### ISSUE THREAD

**Issue by ForrestHilton** [emacs-lsp/lsp-dart#106]
Vscode seams to have part of the same problem as emacs in regard to issues #73 and #74. However, vscode partly gets around this by using an already opened project as the project root when possible.
For example if I open ~/project/lib/main.dart, then jump to definition of onPanUpdate, vscode opens /opt/flutter/packages/flutter/lib/src/widgets/gesture_detector.dart with existing lsp process and existing workspace. This is supper helpful.

To replicate this in lsp-mode, I can manually select ~/project/  as project root after jumping to definition, but this is finicky and annoying. 

Would you please attempt to replicate this vscode behavior? I can attempt it myself, but I don't know anything about lsp mode internals and barely know elisp.

There is actually a second discrepancy. It seams that lsp-mode does not start an analysis server for dart library, but when given the correct project root for a dart package outside the sdk, vscode is able to use the lsp server just fine. If this is disabled deliberately to avoid an error I would be curios to try and debug that.

**Comment by ericdallo** [comment]
Hi, thank you for the suggestion, this actually is totally possible with lsp-mode :) I did it for clojure [here](https://github.com/emacs-lsp/lsp-mode/pull/2746). I can try to do the same with lsp-dart

**Comment by ForrestHilton** [comment]
I took another look, and the problem with ordinary dart projects was mostly user error.  
I set
           lsp-dart-flutter-sdk-dir "/opt/flutter"
but not 
           lsp-dart-sdk-dir "/opt/flutter/bin/cache/dart-sdk"
for dart projects I needed both, and it would be cool if dart-lsp could auto detect as it would make dart-lsp without any variable for most people.

**Comment by ericdallo** [comment]
> for dart projects I needed both, and it would be cool if dart-lsp could auto detect as it would make dart-lsp without any variable for most people.

It's a good suggestion, I have an idea in mind to improve that, thanks!

**Comment by ericdallo** [comment]
@ForrestHilton I made a fix on master and I should release a new version after this PR get merged https://github.com/emacs-lsp/lsp-mode/pull/3000, so you may have no issues after that when opening flutter/dart files, it should use the current workspace and show no errors :)

**Comment by ForrestHilton** [comment]
I will test it soon.
when I tested it by pasting the new
(defun lsp--try-open-in-library-workspace ()
into my config, it was working then it stopped working.

**Comment by ForrestHilton** [comment]
I installed the changes in spacemacs according to these instructions:
https://develop.spacemacs.org/doc/FAQ.html#how-to-override-a-layer-package
lsp--try-open-in-library-workspace is the new version and I think the layer is configured correctly but it still says 
LSP :: gesture_detector.dart not in project or it is blacklisted.

**Comment by ForrestHilton** [comment]
It is working better actually: jump-to-defintion works in gesture detector and gesture_detector.dart is listed in the same project under describe session.

**Comment by ForrestHilton** [comment]
I think the error message was actually harmless and can be silenced. 

Also, Is it possible to make it associate any furthur files I visit with the current project? At present if I jump to definition within gesture_detector.dart to another library file, it does not associate that file with the current project.

3rd, It might not be your problem, but spacemacs/jump-to-definition no longer refreshes the screen after successfully loading a new buffer. It waits till I type to show the new buffer.

**Comment by ericdallo** [comment]
This behaviour of multiple file navigations use the same project already work with that fix, I don't know spacemacs but I suggest you open an issue on their project or ask on gitter

**Comment by ericdallo** [comment]
@ForrestHilton the PR on lsp-mode was merged, could you test latest MELPA unstable packages of lsp-dart and lsp-mode?

**Comment by ForrestHilton** [comment]
when I opened the sample flutter project with my current spacemacs set up with most recent melpa, emacs shows:
Target of URI doesn't exist: 'package:flutter/material.dart'.
 Try creating the file referenced by the URI, or Try using a URI for a file that does exist. (lsp)
This is completely new and I don't understand.

When I tried to reproduce with the example ~/.emacs from the lsp-dart readme, it did not start the analysis server at all even with me manually setting the sdk path.

**Comment by ericdallo** [comment]
This seems to be some issue with the lsp-dart setup on your machine, try to set both `lsp-dart-flutter-sdk-dir` and `lsp-dart-sdk-dir`

**Comment by ForrestHilton** [comment]
this is the .emacs that doesnt work at all:

(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)

(setq package-selected-packages 
      '(dart-mode lsp-mode lsp-dart lsp-treemacs flycheck company
                  ;; Optional packages
                  lsp-ui company hover))

(when (cl-find-if-not #'package-installed-p package-selected-packages)
  (package-refresh-contents)
  (mapc #'package-install package-selected-packages))

(add-hook 'dart-mode 'lsp)

(setq
 lsp-dart-flutter-sdk-dir "/opt/flutter")
(setq
 lsp-dart-sdk-dir "/opt/flutter/bin/cache/dart-sdk")

(setq gc-cons-threshold (* 100 1024 1024)
      read-process-output-max (* 1024 1024)
      company-minimum-prefix-length 1
      lsp-lens-enable t
      lsp-signature-auto-activate nil)

**Comment by ForrestHilton** [comment]
I think the URI not found error was just a problem with the example file since I couldnt build that project.

**Comment by ForrestHilton** [comment]
I have everything is working now under spacemacs. I am using the template flutter project from "flutter create". I updated everything I could think of, and I am loading the new lsp--try-open-in-library-workspace in my init.

**Comment by ericdallo** [comment]
oh, you are right, the sample project is using a local deps `linear_progress_loading`, you can comment that on pubspec.yaml and it should work the `flutter pub get`

**Comment by ForrestHilton** [comment]
"flutter pub get" works and so does lsp-dart in that project. It all looks good. Thankyou for your time it all looks good to me.

**Comment by ericdallo** [comment]
released 1.19.1
