### ISSUE TITLE
'Error installing Dart debugger' - lsp-mode 7.0.1 doesn't have a `:download` provider registered

### ISSUE THREAD

**Issue by scottbale** [emacs-lsp/lsp-dart#108]
**Describe the bug**

Trying to `M-x lsp-dart-dap-setup`, I get the message

    [LSP Dart] Error installing Dart debugger. Unable to find a way to install dart-debugger
    
With some debugging, it appears the problem is the `'dart-debugger` lsp dependency is defined as a `:download` type of dependency, but lsp mode's `lsp-deps-providers` plist does not contain an entry for `:download`. 

**To Reproduce**

When I eval `lsp-deps-providers` I get

    (:npm
      (:path lsp--npm-dependency-path :install lsp--npm-dependency-download)
      :system
      (:path lsp--system-path))

So the expression

    (plist-get lsp-deps-providers :download)

Evaluates to `nil` and the `lsp-dart-dap-setup` function falls back to error callback. I did a cursory search but didn't find any documentation about configuring lsp deps providers in either package.

**Workaround**

It looks like I can just install the debugger by hand and make sure that it's actual location on disk matches `lsp-dart-dap-debugger-path` var.

**Version**

`lsp-dart` v. 1.19.1
`lsp-mode` v. 7.0.1

**Comment by ericdallo** [comment]
Hi @scottbale, thanks for the report, are you using latest lsp-mode from unstable melpa?

**Comment by scottbale** [comment]
Hi @ericdallo. No, it looks like I got `lsp-mode` 7.0.1 as a dependency when I installed `lsp-dart` package. I'll give the latest `lsp-mode` a try here in a little while.

**Comment by ericdallo** [comment]
Also make sure you have latest dap-mode as well

**Comment by scottbale** [comment]
Okay, installed the latest `lsp-mode` (`20210729.732`) and `dap-mode` (`20210720.448`) from melba unstable. Still `lsp-dart` v `1.19.1`. Now I seem to be getting farther when I `M-x lsp-dart-dap-setup`. `lsp-mode` begins to download the extension...

```
LSP :: Starting to download https://github.com/Dart-Code/Dart-Code/releases/download/v3.23.0/dart-code-3.23.0.vsix to /Users/scott.bale/.dap/extension/github/Dart-Code/Dart-Code/3.23.0/dart-code.zip...
Contacting host: github.com:443
```

...but it never completes. I can see the empty directory structure being created where expected, `extension/github/Dart-Code/Dart-Code/3.23.0/`, but no files. Nothing else in `*Messages*`. There's a `*lsp-log*` buffer with some logging but nothing about the download.

**Comment by ericdallo** [comment]
probably some connection issue, you can try to remove the `extension/github/Dart-Code` folder and retry

**Comment by scottbale** [comment]
Thanks for your prompt help @ericdallo - it seems to be working with latest `lsp-mode` and `dap-mode` (other than whatever spurious connection thing is happening). I will close this issue.
