### ISSUE TITLE
lsp-dart searches for "dart.exe" instead of "dart.bat" on windows

### ISSUE THREAD

**Issue by jeremy302** [emacs-lsp/lsp-dart#110]
Hi, I just installed dart (through flutter), flycheck, company....etc. When i try to execute `lsp-dart-show-outline`, I get this error:
```
[LSP Dart] Dart command not found in path ’c:/Users/USERNAME/Documents/flutter/sdk/flutter/bin/dart.exe’
lsp-dart-assert-sdk-min-version: Assertion failed: Feature not supported before dart SDK %s
```
In that directory, there exists a `dart` and `dart.bat` file, but no `dart.exe` file. using dart in the command line works just fine.
I've set `lsp-dart-sdk-dir` to the `dart.bat` directory, and `lsp-dart-flutter-executable` to `flutter.bat` (as there seems to be no `lsp-dart-dart-executable` variable), but the issue persists.

OS: Windows 10 64 bit
Emacs Version: 27.2
Dart Version: 2.13.4
`M-x lsp-dart-version` output:
```
[LSP Dart] Dart command not found in path ’c:/Users/USERNAME/Documents/flutter/sdk/flutter/bin/dart.exe’
[LSP Dart] 1.19.1 (package: 20210728.201) at 2021.08.04 @ Emacs 27.2
[Dart SDK] ’[LSP’ is not recognized as an internal or external command,
operable program or batch file.

[Flutter SDK] c:/Users/USERNAME/Documents/flutter/sdk/flutter/
[Flutter project] false
[Project entrypoint] Not found
```

**Comment by ericdallo** [comment]
Thank you for the report @jeremy302 you need to set those variables to the root of the dart SDK and/or flutter SDK, not the path there the executable lies.
Even so, I'll double check if we are using the .bat instead of a .exe file

**Comment by jeremy302** [comment]
@ericdallo could you please elaborate on what you mean by setting those variables to the root of the dart/flutter sdk. Thanks.

**Comment by ericdallo** [comment]
if your flutter executable is `C:/Users/USERNAME/Documents/flutter/sdk/flutter/bin/flutter.bat`, you can try set on emacs:
```elisp
(setq lsp-dart-flutter-sdk-dir "C:/Users/USERNAME/Documents/flutter/sdk/flutter")
```

**Comment by jeremy302** [comment]
Ohk.I have tried that, but the problem still persists

**Comment by ericdallo** [comment]
@jeremy302 I can't understand why it's failing for you, for some reason, it's trying to find the `dart.exe` command from your `<flutterSDK>/bin` folder but the correct path is from `<flutterSDK>/bin/cache/dart-sdk/bin`, COuld you test setting those 2 variables:
```elisp
(setq lsp-dart-flutter-sdk-dir "<your-flutter-sdk-PATH>"
      lsp-dart-sdk-dir "<your-flutter-sdk-PATH>/bin/cache/dart-sdk")
```

We need to get `lsp-dart-version` work, printing the correct paths.
Are you using windows via mingw or something like that?

**Comment by jeremy302** [comment]
@ericdallo Yep, that worked, thanks a lot. I'm have mingw, but I'm not using emacs with it

**Comment by ericdallo** [comment]
Good, lmk if you find anything to improve, I can't understand the issue here, but like some other issues, most are fixed setting the flutter SDK and dart SDK path manually

**Comment by shivjm** [comment]
I’ve got the inverse problem: after installing the Dart and Flutter SDKs via Chocolatey, I have dart.exe, not dart.bat. I have [a WIP branch](https://github.com/emacs-lsp/lsp-dart/commit/af331f56c73080bab8bef110d3e0b3c1d0942fb3) that fixes the issue, but it does so by running `executable-find` every single time it’s called, which seems sub-optimal. I’m not sure what the right solution is here.

**Comment by ericdallo** [comment]
yeah, that could lead to performance issues, I think we should support both .bat and .exe just checking if one of those exsits
