### ISSUE TITLE
Readme Incorrect Instructions for dart-mode-hook

### ISSUE THREAD

**Issue by vnayar** [emacs-lsp/lsp-dart#113]
**Describe the bug**

The README file has the following instructions:
(add-hook 'dart-mode 'lsp)

However, the variable that actually gets executed on loading of dart-mode is "dart-mode-hook". Instead this line should be:
(add-hook 'dart-mode-hook 'lsp)

**Comment by ericdallo** [comment]
Thanks for the report, fixed!
