### ISSUE TITLE
Connect to simulator and run flutter without debug mode?

### ISSUE THREAD

**Issue by shivahnshankar** [emacs-lsp/lsp-dart#115]
Hi 
I am a bit confused about running a flutter program on an emulator/simulator without debugging. VS Code has "Start debugging" and "Run without debugging". In lap-dart, I believe we have to use dap-debug to open the emulator. Does this mean that we are always in debug mode? There are times when I can see that I have entered DAP mode (doom modeline changes to Orange) while in others I am not. Or am I misunderstanding? 
Need to understand DAP better I guess. 
Thanks

**Comment by ericdallo** [comment]
You are almost right, lsp-dart uses dap to run in debug mode and normal mode, the difference is that the normal mode doesn't use the dart debugger, and runs the program like when you run on the CLI via `flutter run`, in the end, the normal mode should be a little bit faster and similar to running via `flutter run`

**Comment by shivahnshankar** [comment]
Thanks. And is there a way to make sure that I always stay in "normal" mode in the configuration, unless I want to switch to debug mode explicitly?

**Comment by ericdallo** [comment]
ATM there is no specific command for that, only available via code lens, but looks a good idea to create a `lsp-dart-dap-run-flutter` and `lsp-dart-dap-run-dart`, WDYT?

**Comment by shivahnshankar** [comment]
Right...however, there should a way to choose the emulator/simulator/device, and the hot reload and the hot restart functionality should work as well.

**Comment by ericdallo** [comment]
for that I think [flutter.el](https://github.com/amake/flutter.el) solves your issue, right?

**Comment by ericdallo** [comment]
@shivahnshankar just released a new version adding a new command `lsp-dart-run`, which should be specific for running any flutter or dart app without debugging with support for passing custom args as well :)
