### ISSUE TITLE
run lsp get error:  The following servers support current file but do not have automatic installation configuration: dart_analysis_server

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#116]
**Describe the bug**

I am new to dart/flutter, so maybe somethings not config correct.

following is my config:

```cl
(require 'project)
(defun project-try-dart (dir)
  (let ((project (or (locate-dominating-file dir "pubspec.yaml")
                     (locate-dominating-file dir "BUILD"))))
    (if project
        (cons 'dart project)
      (cons 'transient dir))))
(add-hook 'project-find-functions #'project-try-dart)
(cl-defmethod project-roots ((project (head dart)))
  (list (cdr project)))

(require 'dart-mode)
(require 'lsp-dart)

(setq lsp-signature-auto-activate nil)

(setq dart-format-on-save t)

(add-hook 'dart-mode-hook 'lsp)

(add-to-list 'auto-mode-alist '("\\.dart\\'" . dart-mode))

(provide 'dart-mode_init)

;;; dart-mode_init.el ends here
```
---------

My flutter folder like this

```
/home/public/Dropbox/linux/utils/flutter/
|── bin
| flutter # <= flutter binary here
│ ├── cache
│ │ ├── dart-sdk
│ │ │ ├── bin
│ │ │ │ ├── snapshots
│ │ │ │ │ ├── analysis_server.dart.snapshot # <= i guess anaysis server here, right?
```

When i start to run `lsp` after enter `dart-mode`, get following error.

```
LSP :: The following servers support current file but do not have automatic installation configuration: dart_analysis_server
You may find the installation instructions at https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).
```

------------

following is my (lsp-dart--server-command) output.

("/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/dart" "/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot" "--lsp" "--client-id emacs.lsp-dart" nil)

all path is correct, in fact, i can run server successful like this: (like a server, blocked)

"/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/dart" "/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot" "--lsp" "--client-id emacs.lsp-dart" nil

I consider this command string is correct, but don't know why lsp not work.

if need more detail, please let me know, i will offer here.

**Version**
```
[LSP Dart] unknown at 2021.08.25 @ Emacs 27.2
[Dart SDK] Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"

[Flutter SDK] /home/public/Dropbox/linux/utils/flutter/
[Flutter project] true
[Project entrypoint] /home/zw963/Dart/myapp/lib/main.dart
```

**Comment by ericdallo** [comment]
@zw963 from your output of `lsp-dart-version`, I can see lsp-dart is corectly recognizing the project as a flutter one and the `Flutter SDK` points to your flutter root correctly (`/home/public/Dropbox/linux/utils/flutter/`).

What happens if you don't set `lsp-dart-sdk-dir ` at all? 
what lsp-dart outputs when you do `M-:` `(lsp-dart-get-flutter-sdk-dir)`?
what lsp-dart outputs when you do `M-:` `(lsp-dart-get-sdk-dir)`?

**Comment by zw963** [comment]
> What happens if you don't set `lsp-dart-sdk-dir ` at all?

Same error.

> what lsp-dart outputs when you do M-: (lsp-dart-get-flutter-sdk-dir)?

"/home/public/Dropbox/linux/utils/flutter/"

>  what lsp-dart outputs when you do M-: (lsp-dart-get-sdk-dir)?

"/home/public/Dropbox/linux/utils/flutter/"

**Comment by ericdallo** [comment]
so that's the issue, `(lsp-dart-get-sdk-dir)` should output `"/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk"`, we can try to debug this function now.

**Comment by ericdallo** [comment]
`M-:` `lsp-dart-sdk-dir` (just to confirm the variable is not set)
`M-:` `(lsp-dart-flutter-project-p)`
`M-:` `(-some-> (executable-find "dart")
        file-truename
        (locate-dominating-file "bin")
        file-truename)`

**Comment by zw963** [comment]
> `M-:` `(lsp-dart-flutter-project-p)`

t



> (-some-> (executable-find "dart") file-truename (locate-dominating-file "bin") file-truename)

"/home/public/Dropbox/linux/utils/flutter/"

**Comment by ericdallo** [comment]
Alright, could you debug each part of:
```elisp
(let ((dart-sdk (expand-file-name "bin/cache/dart-sdk/" (lsp-dart-get-flutter-sdk-dir))))
          (if (file-exists-p dart-sdk)
              dart-sdk
            (error "Dart SDK not found inside flutter cache dir %s.  Consider setting `lsp-dart-sdk-dir` variable" dart-sdk)))
```
?

**Comment by zw963** [comment]
> Alright, could you debug each part of:

result:

"/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/"

each part:
dark-sdk => (expand-file-name "bin/cache/dart-sdk/" (lsp-dart-get-flutter-sdk-dir)) => "/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/"

(file-exists-p dart-sdk) => true

**Comment by ericdallo** [comment]
Oh, that's odd, are you sure `(lsp-dart-get-sdk-dir)` is returning `/home/public/Dropbox/linux/utils/flutter/` and not `/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/`?

**Comment by zw963** [comment]
> are you sure (lsp-dart-get-sdk-dir) is returning /home/public/Dropbox/linux/utils/flutter/ and not /home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/?

Wired, when i this time run M-: (lsp-dart-get-sdk-dir) , get "/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/" when on dart buffer, I never change anythings config except follow you eval somethings on mini buffer.


> BTW, run the (lsp-dart-get-sdk-dir) on your flutter project, not on lsp-dart source buffer

"/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/" 

sorry, i guess some things wrong before? i test several times restart emacs daemon, (lsp-dart-get-sdk-dir) always get expected result even variable lsp-dart-sdk-dir is nil,  but still get old lsp error. 

--------------


BTW: there is a concern.

in fact, i set flutter path to:  `~/utils/flutter/bin`, but why we see like `/home/public/Dropbox/linux/utils/flutter`? because

because it is a sym link.

```sh
 ╰─ $ ls -ld ~/utils
lrwxrwxrwx 1 zw963 zw963 31 Nov 19  2017 /home/zw963/utils -> /home/zw963/Dropbox/linux/utils/
```

hope this not cause issue.

**Comment by zw963** [comment]
so following is my new config:

```cl
(require 'project)
(defun project-try-dart (dir)
  (let ((project (or (locate-dominating-file dir "pubspec.yaml")
                     (locate-dominating-file dir "BUILD"))))
    (if project
        (cons 'dart project)
      (cons 'transient dir))))
(add-hook 'project-find-functions #'project-try-dart)
(cl-defmethod project-roots ((project (head dart)))
  (list (cdr project)))

(require 'dart-mode)
(require 'lsp-dart)

(setq lsp-signature-auto-activate nil)

(setq dart-format-on-save t)

(add-hook 'dart-mode-hook 'lsp)

(add-to-list 'auto-mode-alist '("\\.dart\\'" . dart-mode))

(provide 'dart-mode_init)

;;; dart-mode_init.el ends here
```

```cl
(require 'dap-mode)
(dap-mode)
(dap-ui-mode)

(provide 'dap-mode_init)

```

**Comment by zw963** [comment]
Yes, please see my `*Messages*` output

```
"/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/"
LSP :: The following servers support current file but do not have automatic installation configuration: dart_analysis_server
You may find the installation instructions at https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).
```

if there is a way to output lsp debug info? 

BTW:  my lsp work well with rust-mode and lsp-rust anyway, so, at least, lsp is working on another mode.

**Comment by ericdallo** [comment]
hum, that's really weird, could you test if it works for [this sample project](https://github.com/ericdallo/flutter_sample)?

I can't see any reason why it's not working as `(lsp-dart-get-sdk-dir)` returns the correct folder

**Comment by zw963** [comment]
@ericdallo , if you want reproduce yourself,  you can checkout my .emacs.d repo. and throw git folder somewhere, then, add those code into your's ~/.emacs, and replace `MY_CONFIG_PLACE` to git repo, and use emacs open sample repo.

```
;;; .emacs --- Where all the magic begins


(defun relative-load (file-relative-path)
  (let ((absolute-path (expand-file-name
                        file-relative-path
                        (file-name-directory (or load-file-name buffer-file-name)))))
    (when (file-exists-p absolute-path) (load absolute-path))))

;; Emacs 默认只是在 shell, vterm, shell, term 下面设定这个环境变量.
;; 这里全局增加这个环境变量.
(setenv "INSIDE_EMACS" "true")

(relative-load "MY_CONFIG_PlACE/set_load_path.el")
(relative-load "MY_CONFIG_PlACE/.emacs")
```

**Comment by ericdallo** [comment]
> i set my lsp-dart-sdk-dir manually like this, but still not working.

I can't understand why, can you confirm that `(lsp-dart-version)` prints the correct sdk dir after setting that?
Also, check the return of `(lsp-dart--server-command)`

> Are you try to reproduce this?

I'd need to spend some time to test your config

**Comment by zw963** [comment]
> I can't understand why, can you confirm that `(lsp-dart-version)` prints the correct sdk dir after setting that?
> Also, check the return of `(lsp-dart--server-command)`

1. i can confirm i set  lsp-dart-sdk-dir manually, because i can read this variable value.

![image](https://user-images.githubusercontent.com/549126/130830462-ebd2c394-7d72-40ed-bdc9-41ac2c6a77c3.png)

--------------

2. following is (lsp-dart-version) output:

![image](https://user-images.githubusercontent.com/549126/130830586-cb00d3f7-2be7-4aaf-81fa-fde01b6a0dac.png)

---------------

3. Following is (lsp-dart--server-command) output.

![image](https://user-images.githubusercontent.com/549126/130830727-86f66250-38ad-4dad-913f-2a9e0470c942.png)


("/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/dart" "/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot" "--lsp" "--client-id emacs.lsp-dart" nil)

**Comment by ericdallo** [comment]
Everything looks correct, what happens if you run on terminal:
```
$ /home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/dart /home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart
```

**Comment by zw963** [comment]
Wired, i found i can run `(lsp)` successful when use dired open dark sample project, but without open dart file,

 but, only when i try to open lib/main.dart, get old error.

> Everything looks correct, what happens if you run on terminal:

Blocked on my terminal, like a web server.

![image](https://user-images.githubusercontent.com/549126/130831510-af61e4ac-b5c0-44cf-a0aa-1ca251adb032.png)

**Comment by ericdallo** [comment]
so the command is perfectly correct, for some reason, lsp-mode is not being able to launch that command, I suspect it's related with your config. There is a way to confirm it's your config, you can try use [lsp-start-plain.el](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el), it will launch a emacs with very basic config and everything that needs to lsp-dart works
