### ISSUE TITLE
Allow recent created files to be imported

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/lsp-dart#12]
**Describe the bug**
when using `lsp-mode` with `dart-mode`, after I create a new dart file, when I try to use it, it just don't show an option on `lsp-ui` for the auto import.
Sometimes if I run `lsp-restart-workspace` then `lsp` again, or I kill the buffer, the option to import shows off.

**To Reproduce**
Example: 

I create a file `b.dart`:
```dart
class B {

}
```
then on an existent file `a.dart`, `lsp-ui` doesn't recognize the class to import:
```dart
void main() {
    final b = B();
}
```
the only options are:
![image](https://user-images.githubusercontent.com/7820865/78319152-ee9d5f80-753c-11ea-95ee-379a20128a6f.png)

**Expected behavior**
Like `lsp-java` I expect it to recognize the new file/class and allows me to import it.

**Which Language Server did you use**
lsp-dart

**OS**
Which os do you use?
NixOS 20.03

**Error callstack**

**Comment by ericdallo** [comment]
@yyoncho, so do you think I should open an issue on upstream?
It's odd, since creating the file via the terminal as I said above, works great. Isn't this a `lsp-mode` bug?

**Comment by yyoncho** [comment]
Here it is the spec:

> The document open notification is sent from the client to the server to signal newly opened text documents. The document’s content is now managed by the client and the server must not try to read the document’s content using the document’s Uri. 

The server should work without depending on the file present on the disc or not.

**Comment by ericdallo** [comment]
It makes totally sense, a weird behaviour too, is that evenly saving the buffer before or after creating the B class, it does not work

**Comment by DanTup** [comment]
This might be the same issue shown here:

https://github.com/Dart-Code/Dart-Code/issues/2286#issuecomment-658597532

Which should be fixed by:

https://dart-review.googlesource.com/c/sdk/+/154960/

**Comment by ericdallo** [comment]
Thanks, @DanTup, I'll try to reproduce the issue with the fix...

**Comment by ericdallo** [comment]
I could confirm that this is fixed on the latest SDK: http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/
Thank you very much @DanTup!
