### ISSUE TITLE
lsp-dart-line-length stopped working on flutter 2.5

### ISSUE THREAD

**Issue by sysint64** [emacs-lsp/lsp-dart#120]
**Describe the bug**
`lsp-dart-line-length` stopped working on flutter 2.5. On version 2.2 it works fine.

**To Reproduce**
Install flutter 2.5 and set the line length to 100 symbols;

```lisp
(setq lsp-dart-line-length 100)
```

format buffer with `lsp-format-buffer`

**Comment by ericdallo** [comment]
I'll take a look at this, probably something related with dart sdk bump

**Comment by ericdallo** [comment]
yeah, I confirmed the issue happens on dart 2.14.0 but not on dart 2.13.1.
@DanTup do you know if there was introduced any regression or new variable to control the line length during formatting? I checked Dart-Code but I didn't see any changes about that

**Comment by ericdallo** [comment]
This is how lsp-dart is sending the `workspace/configuration` response after changing the default from 80 -> 100:
```json
[Trace - 10:24:29 AM] Sending response 'workspace/configuration - (1)'. Processing request took 0ms
Params: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "dart": {
        "enableSdkFormatter": true,
        "completeFunctionCalls": true,
        "showTodos": null,
        "lineLength": 100
      }
    }
  ]
}


```

**Comment by DanTup** [comment]
There was [a change recently to support per-workspace config](https://github.com/dart-lang/sdk/commit/c88193538d78408f3523ad11126dc28136a1b476). Are you able to capture the traffic (or use `--instrumentation-log`) for a session where this doesn't work for me to check?

It should be falling back to the original workspace-level config when there's no folder config, but I wonder if something is going wrong.

**Comment by DanTup** [comment]
@ericdallo do you have the request that the server sent to you that this responds to?

**Comment by ericdallo** [comment]
sure, the server request was:
```json
[Trace - 10:24:29 AM] Received request 'workspace/configuration - (1).
Params: {
  "items": [
    {
      "section": "dart"
    }
  ]
}


```

**Comment by DanTup** [comment]
@ericdallo the "dart" in your response looks suspect. When I log from VS Code, I see a request from the server like this:

```js
{
	"id": 1,
	"method": "workspace/configuration",
	"params": {
		"items": [
			{
				"section": "dart"
			}
		]
	},
	"jsonrpc": "2.0"
}
```

And VS Code responds like this (note there's no "dart" anywhere):

```js
{
	"jsonrpc": "2.0",
	"id": 1,
	"result": [
		{
			"lineLength": 160,
			// ...
		}
	]
}
```

Although the LSP spec doesn't seem to be very clear about this.

**Comment by ericdallo** [comment]
@yyoncho can you help understand what is the probably expected behavior?
Even so, the best would be to fix on lsp-dart/lsp-mode somehow otherwise we would need to wait for another dart-sdk update + flutter update which may take some time

**Comment by DanTup** [comment]
I don't think the spec is very clear, but there is some discussion in https://github.com/microsoft/language-server-protocol/issues/972 which I think matches the Dart/VS Code stuff above - that is if a server asks for `"dart"` configuration, the returned object is already scoped to `"dart"` and should not have all the values wrapped inside another `"dart"`.

If it seems like there are many editors/servers doing the opposite, we should probably ping on https://github.com/microsoft/language-server-protocol/issues/972 and see if we can get concrete clarification (and if that means changing the server and/or VS Code LSP client, I'm happy to do that).

**Comment by ericdallo** [comment]
thank you @DanTup, that makes sense to me indeed.
@yyoncho do you think we can change the lsp-mode response unwrapping the returned item? I don't know any other server that uses `workspace/configuration` so I'm not sure if a lot of servers would be affected though

**Comment by yyoncho** [comment]
@ericdallo makes sense

**Comment by ericdallo** [comment]
So can we say it's something that changed on the newest dart SDK @DanTup ?

**Comment by DanTup** [comment]
@ericdallo the last request/response posted above don't look right to me. The request is asking for two items:

```
"items": [
    {
      "scopeUri": "file:///home/greg/dev/flutter_sample",
      "section": "dart"
    },
    {
      "section": "dart"
    }
  ]
```

But the response contains only one:

```
  "result": [
    {
      "enableSdkFormatter": true,
      "completeFunctionCalls": true,
      "showTodos": null,
      "lineLength": 120
    }
  ]
```

The items in the resulting array need to match up with the request:

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration

> The order of the returned configuration settings correspond to the order of the passed ConfigurationItems (e.g. the first item in the response is the result for the first configuration item in the params).
>
>  If the client can’t provide a configuration setting for a given scope then `null` needs to be present in the returned array.

The server will ignore the response if the number of items don't match the request:

https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/pkg/analysis_server/lib/src/lsp/lsp_analysis_server.dart#L241

**Comment by ericdallo** [comment]
I see, it makes sense to me indeed!
So we probably need to fix lsp-mode to return the matching items, right @yyoncho ?

**Comment by ericdallo** [comment]
Confirmed it works indeed :)
Thank you @yyoncho and @DanTup for the help on this!

**Comment by ericdallo** [comment]
Available on next 1.19.5 release @sysint64

**Comment by laynor** [comment]
I'm still stuck with non-working `lsp-dart-line-length` setting, even though my `lsp-dart` version is `1.20.0`. 
How can I fix it?

**Comment by ericdallo** [comment]
What's your dart-sdk/flutter-sdk version @laynor ?

**Comment by laynor** [comment]
@ericdallo I do not have a `lsp-dart-version` command - I have `lsp-dart-version-string`, which returns `"1.20.0"`.

**Comment by laynor** [comment]
@ericdallo Here it is
```
[LSP Dart] 1.20.0 at 2021.12.12 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "macos_x64"

[Flutter SDK] /Users/ale/local/opt/flutter
[Flutter project] true
[Project entrypoint] Not found
```

**Comment by ericdallo** [comment]
@laynor I just tested with latest flutter (2.8.0, dart 2.15.0) and latest lsp-dart `1.20.1` and it works properly after setting: `(setq lsp-dart-line-length 100)`, could you bump lsp-dart to latest?

**Comment by laynor** [comment]
@ericdallo Can confirm it's working 👍
