### ISSUE TITLE
lsp-dart-dap-setup freezes up

### ISSUE THREAD

**Issue by p4-k4** [emacs-lsp/lsp-dart#122]
`lsp-dart-dap-setup` freezes up . clean and bare install of emacs.
seems as if it's not able to fetch the extension as the directory below is empty.

any quick workaround for this? cheers!

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/paka/.emacs.d/.extension/github/Dart-Code/Dart-Code/3.25.1/extension/out/dist/debug.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.0.1

Process Dart :: Debug stderr finished
```

**Version**

https://i.imgur.com/qJYXX8r.png

**Comment by p4-k4** [comment]
I've downloaded and installed vscode with the dart extensions, then pulled out the debug.js file from the extension install.
That seems to work ok but what's the problem with not being able to use `lsp-dart-dap-setup` as expected?

**Comment by ericdallo** [comment]
@p4-k4 this sounds like corrupted downloaded debugger extension or wrong node version, not sure, maybe try to delete what lsp-dart downloaded and try the command again?
In future releases we should use the debugger from dart SDK and running lsp-dart-dap-setup would not be necessary anymore 🤞🏻

**Comment by p4-k4** [comment]
thanks for that. yeah it seems as though lsp-dart sets up this dir `/Users/paka/.emacs.d/.extension/github/Dart-Code/Dart-Code/3.25.1/extension/`) but from "extension", is empty which tells me somethings wrong with the download or the release file that it downloads?

When manually downloading this release (https://github.com/Dart-Code/Dart-Code/releases?page=2) I also couldn't find the debugger that lsp-dart is expecting and rather, I had to grab it from my vscode dot files (`~/.vscode/extensions/dart-code.dart-code-3.28.0/out/dist/debug.js`).

but yes, using the debugger from the dart SDK in future releases would be the way to go!

**Comment by ericdallo** [comment]
@p4-k4 I just tried on a clean project and clean emacs and I can't repro the issue, the extension folder looks correct after `lsp-dart-dap-setup`:
![image](https://user-images.githubusercontent.com/7820865/141663508-eb97a9a0-9f9a-439f-8d07-a6f64a2123a1.png)

Maybe some issue with your emacs to unzip or when downloading?

**Comment by p4-k4** [comment]
Might I say, I'm not using vanilla emacs so yeah could be the case (currently using doom emacs). I'll investigate further. Thanks

**Comment by ericdallo** [comment]
I use doom-emacs as well, so I'd discard that, do you have npm/node on your PATH? since we use that for npm installing the debugger, unfortunately

**Comment by p4-k4** [comment]
I've installed both with homebrew, after adding homebrew to PATH, it seems like `lsp-dart-dap-setup` wants to start downloading it.

`LSP :: Starting to download https://github.com/Dart-Code/Dart-Code/releases/download/v3.25.1/dart-code-3.25.1.vsix to /Users/paka/.emacs.d/.extension/github/Dart-Code/Dart-Code/3.25.1/dart-code.zip...
Contacting host: github.com:443`

First attempt, it completely crashed emacs, second attempt it just hung on `Contacting host: github.com:443` for over 10 minutes. 3rd time, downloaded fine and can use it now. These issues will be mostly system related but maybe this entire step will be cut in the near future :)

Thanks again!

**Comment by ericdallo** [comment]
Yeah, this installation is something we probably can improve on dap-mode side to catch those timeouts and issues
