### ISSUE TITLE
A bug in customize(defcustom)

### ISSUE THREAD

**Issue by karbiv** [emacs-lsp/lsp-dart#123]
**Describe the bug**
Important config variables do not work in `M-x customize`. Dart SDK directories.

**To Reproduce**
Editing Dart SDK directories in `M-x customize`.
Widgets in _Customize_ disappear after clicking on them.

Current code with the bug:
https://github.com/emacs-lsp/lsp-dart/blob/9c3ba0a27e8ad3b7fa16c553d8a1815db82b8638/lsp-dart-utils.el#L27-L42

**Solution**

`nil`s in `:type` of defcustom must be wrapped in `const`:
`:type '(choice directory (const nil))`

**Comment by ericdallo** [comment]
Thank you, fixed!
