### ISSUE TITLE
JSON parsing error when opening .dart file

### ISSUE THREAD

**Issue by ji6czd** [emacs-lsp/lsp-dart#125]
I can't open the .dart file.
When I open the .dart file, I get the following error message:
error in process filter: End of file while parsing JSON: "premature end of input", "<string>", 1, 1024, 1024 [12 times]

**To Reproduce**
1. Run Emacs.
2. Open .dart file.

**Version**
[LSP Dart] 1.20.1 at 2021.12.22 @ Emacs 27.2
[Dart SDK] Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"
[Flutter SDK] /usr/local/Caskroom/flutter/2.8.1/flutter/
[Flutter project] true
[Project entrypoint] /Users/seiken/src/Experimental/flutter/abc/lib/main.dart

**Comment by ericdallo** [comment]
@ji6czd sounds like a issue on dart-mode or something, could you try with lsp disabled?

**Comment by ji6czd** [comment]
Thank you for your comment.

I tried disable lsp-mode.

1. Open .dart file.
  (Dart yas company flyc-) mode enabled.
2. Enabling lsp-mode.
    M-x lsp-mode
3. Error message displayed.

Is there anything else I should try?

**Comment by ericdallo** [comment]
Yes, could you `M-x` `toggle-debug-on-error` and repro the issue again? it should print a stacktrace of the error so we can know from where this error comes

**Comment by ji6czd** [comment]
I noticed that XCode is being updated automatically.
I launched XCode and reinstalled the required components.
I was able to solve the lsp-mode problem.
Thank you for your support.
