### ISSUE TITLE
Is there a way to set -target=lib/main_local.dart globlly?

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#126]
we development with flutter, but we only use `lib/main_local.dart` as local development entry.

i found there is no easy way to set this. when `dart run`, i have to specify this args with C-u

when run dap-debug, i have to do so again.

is there exist another way to do this? as like VSCode, (it use .vscode/launch.json)

thank you.

**Comment by ericdallo** [comment]
We could add a custom variable to add additional args to the run, would this be enough?
Then if you like for all users of the project to have that variable you could add a .dor-locals.el file to the project root setting that variable to the value you want

**Comment by zw963** [comment]
> We could add a custom variable to add additional args to the run, would this be enough?

Yes, maybe environment variable is more better.

**Comment by ericdallo** [comment]
Fixed on master, I should release if the other issues have lsp-dart fixes

**Comment by zw963** [comment]
For those who need this feature, it seem like add a .dir-locals.el into my project with content like this works for me.

```el
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((dart-mode . ((lsp-dart-program-entrypoints . '("lib/main_local.dart")))))
```
