### ISSUE TITLE
dart_analysis_server causing Emacs 27 to spuriously lock up

### ISSUE THREAD

**Issue by Sorixelle** [emacs-lsp/lsp-dart#13]
**Describe the bug**
When editing a Dart file, Emacs sometimes locks up, until `dart_analysis_server` is killed. Sometimes, the echo area will display `error running timer 'lsp--on-idle': (error "Lisp nesting exceeds 'max-lisp-eval-depth'")` before the hang.

This error only occurs on Emacs 27. I have been unable to reproduce this on Emacs 26.

Error is reproducible using lsp-start-plain.el, adding dart-mode to enable LSP.

Occurs on lsp-mode 20200311.612 and lsp-ui 20200311.1837

**To Reproduce**
Using a barebones project created by `flutter create`:
1. Open `lib/main.dart'
2. Make various edits and saves to the file until Emacs locks up

**Expected behavior**
Emacs does not lock up.

**Which Language Server did you use**
`dart_analysis_server` from Flutter 1.12.3+hotfix.8 and Dart 2.7.0

**OS**
Artix Linux (Arch Linux deriviative) w/ Emacs installed from `emacs27-git`

**Error callstack**
https://gist.github.com/Sorixelle/8f84310d3a0593431d20b0b2a2552ae3 - Output from `*lsp-log*` buffer created by setting `lsp-print-io` to `t`.

https://pastebin.com/Zfju7WRf - Emacs backtrace at point of hang

**Comment by ericdallo** [comment]
@Sorixelle, Could you test it again using `lsp-dart` and with the flutter on master like @LongCatIsLooong said?

**Comment by Sorixelle** [comment]
Yep, looks like that might have been it. Thanks for the pointer.
