### ISSUE TITLE
completion with snippets don't work

### ISSUE THREAD

**Issue by krdzo** [emacs-lsp/lsp-dart#130]
When yasnippet is installed and enabled and you select a candidate from completion list it inserts
additional text inside the parenthesis but it doesn't delete when I start typing.
It is best seen in a video:

https://user-images.githubusercontent.com/31158143/148239814-f28eb6b5-80fc-410d-b57d-7bc8cdee8136.mp4

**To Reproduce**
I used the quickstart configuration from [lsp-dart](https://emacs-lsp.github.io/lsp-dart/#quickstart) website where I added two lined for installing and configuring yasnippet:
```
(setq inhibit-splash-screen t)
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)

(setq package-selected-packages
  '(dart-mode lsp-mode lsp-dart lsp-treemacs flycheck company
    yasnippet                                                                ; line added
    ;; Optional packages
    lsp-ui company hover))

(when (cl-find-if-not #'package-installed-p package-selected-packages)
  (package-refresh-contents)
  (mapc #'package-install package-selected-packages))

(add-hook 'dart-mode-hook 'lsp)


(setq gc-cons-threshold (* 100 1024 1024)
      read-process-output-max (* 1024 1024)
      company-minimum-prefix-length 1
      lsp-lens-enable t
      lsp-signature-auto-activate nil)


(add-hook 'dart-mode-hook 'yas-minor-mode)                                   ; line added


```

**Expected behavior**
Either to not enter the `object` between parentheses or to delete it when I start typing. 
I know that we can enable `delete-selection-mode` and that will happen but that clashes with my other configuration so I would rather not enable `delete-selection-mode`.
It would be better if `object` would be treated like a placeholder, like in yasnippet provided snippets.

**Version**
[LSP Dart] 1.21.0 at 2022.01.05 @ Emacs 27.2
[Dart SDK] Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "linux_x64"

[Flutter SDK] /home/me/.flutter/
[Flutter project] false
[Project entrypoint] Not found

**Comment by ericdallo** [comment]
I suspect yasnippet is not enabled on your emacs properly when trying snippets, could you try `M-x` `yas-global-mode`?

**Comment by krdzo** [comment]
It's unchanged. 
Tried `M-x` `yas-global-mode` and tried to delete `(add-hook 'dart-mode-hook 'yas-minor-mode)` line from above config and to add:
```
(require 'yasnippet)
(yas-global-mode 1)
```
the behavior stayed the same.

**Comment by ericdallo** [comment]
It works for me on doom-emacs with [this config](https://github.com/ericdallo/dotfiles/tree/master/.doom.d), @yyoncho can you give a hand on what is necessary to make snippets work besides that?

**Comment by yyoncho** [comment]
@krdzo I tested with `M-x lsp-start-plain`  and using jdtls server and it works fine(starting to type deletes the selection). I am not quite sure what is causing the placeholder not to be deleted. Can you test if other snippets with placeholders have similar behavior?

**Comment by krdzo** [comment]
I tried other snippets and it behaves the same. Every completion that has placeholders, the placeholder is there when completed and isn't deleted when I start typing.
Tried with the above config and with `M-x lsp-start-plain`.

**Comment by krdzo** [comment]
Hi again. I found out what was the problem here.
When you disable `yas-minor-mode` you can see the "snippet" that the LSP server has returned. In my case with the `print` function it returns 
```
print(${0:object})
```
 Because the yas placeholder `$0` indicates that the snippet expansion has ended yas doesn't do anything and just leaves a active region on the placeholder. 
This happens only for one argument functions in Dart. For functions with more that one arguments the snippet that is returned from LSP server is like this 
```
Point(${1:x}, ${2:y})
```
The yas placeholder it returned are `$1` and `$2`. With these `yas-mode` enables you to edit the placeholder text and when you finished with one you can hit `TAB` to go to the next placeholder, so it doesn't just activate mark like the `$0` placeholder does.

@yyoncho I opened a java file to see why it was working correctly for you and saw that jdtls server returns snippets in this form: `System.out.print(${1:null})` so you can edit the `$1` placeholder field and there is no problem.

@ericdallo I also looked in to what was happening in doom-emacs. Doom uses a [hack](https://github.com/hlissner/doom-emacs/blob/master/modules/config/default/%2Bevil.el#L5) to get around the problem (similar hack that I used in my configuration) they enable `delete-selection-mode` every time when you enter insert-state (and disable it when you exit) so it looks like it's working. It doesn't really work, it has its own bugs (you can see them by trying to insert quote character (`"`) after expansion/completion and if you didn't disable smartparen-mode you will see the bug).

All this to say that the problem is probably that darts lsp server returns the wrong snippet. The one argument snippets that it returns should probably be with `$1` placeholder and not with `$0` so that the tools that are working with snippets don't exit prematurely.

P.S.  I'm not really sure where do I report this issue. Don't know if the dart-lang/sdk repo is the right place or is there another separate repo for the dart-lsp-server so if you could point me where to report this. Or if you want you can report it doesn't really matter to me.

**Comment by ericdallo** [comment]
@krdzo dart-sdk is the right repo, you can ping @dantup, the dart LSP server maintainer too if any doubts, but he doesn't use emacs, but vscode, so having the client <-> server logs are necessary to investigate further

**Comment by DanTup** [comment]
> All this to say that the problem is probably that darts lsp server returns the wrong snippet. The one argument snippets that it returns should probably be with $1 placeholder and not with $0 so that the tools that are working with snippets don't exit prematurely.

I don't believe Dart is using the _wrong_ placeholder here. The LSP spec isn't very specific about how snippets are handled, but this seems to just be a difference in how VS Code and whatever is handling the snippets here behave. The spec only states:

```
		 * A snippet can define tab stops and placeholders with `$1`, `$2`
		 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
		 * the end of the snippet. Placeholders with equal identifiers are
		 * linked, that is typing in one will update others too.
```

I think the difference here is that VS Code exits "snippet mode" (such that pressing `tab` no longer jumps to a tabstop, but instead inserts a literal tab) when it gets to $0, but it still keeps the placeholder text _selected_, and thus it will be replaced when you start typing.

It sounds like the plugin handling your snippets here _also_ prevents typing over the placeholder.

The problem with switching to `$1` is that there are many cases (especially in Flutter code) where the user will want to additional nested code (perhaps callbacks/functions) that include tabs and if pressing `tab` jumps to after the `)` that can be quite frustrating. This is something that has come up many times in the VS Code extension:

https://github.com/Dart-Code/Dart-Code/issues/1173

So I don't think changing to `$1` would overall be a good change. I think it may be better if whatever controls the snippets here to more closely align with the VS Code behaviour (I think that's generally a good idea for any LSP functionality, because - rightly or wrongly - VS Code seems to drive the LSP spec, and for languages where VS Code is the largest user of than LSP server, it makes sense to optimise for its behaviour).

Hope this makes sense!

**Comment by ericdallo** [comment]
Yeah, makes sense to me, thank you for your input @DanTup, @yyoncho would you think we could make the behavior similar to vscode on lsp-mode or would we need to change yasnippets?
