### ISSUE TITLE
Is there a way to disable the auto enable of treemacs-follow-mode when run `lsp-dart-run` ?

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#133]
The reason for why i want to disable treemacs-follow-mode , please check https://github.com/Alexander-Miller/treemacs/issues/886

Thank you.

**Comment by ericdallo** [comment]
Only if you define some kind of workaround advice on this function, like:
```elisp
(advice-add #'lsp-dart-run :after (lambda (&rest _) (setq-local treemacs-follow-mode nil)))
```

**Comment by zw963** [comment]
Hi, @ericdallo , above hack works, but, treemacs-follow-mode will enable again at one time when use dart-lsp ...

**Comment by zw963** [comment]
but, wait , i doubt it opened by my another lsp-ruby frontend ...

**Comment by zw963** [comment]
Hi, i can confirm, lsp-dart still enable treemacs-follow-mode frequently even after i disable it manually again and again.

i never enable others mode which use lsp, so, is there exists a hook, always try to enable it?

Thank you.

**Comment by zw963** [comment]
Hi, this is not a issue anymore, because i found the reason which cause treemacs-follow-mode pull file list back, it caused by https://github.com/wakatime/wakatime-mode, i disable it.

thank you.
