### ISSUE TITLE
Avoid reload when i edit a ruby file which not belong to current flutter project when (setq lsp-dart-dap-flutter-hot-reload-on-save t)

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#134]
When i edit `??.rb` file in my backend project, (i use same emacs session for ruby and flutter), i can always see following log message.

```
Reloaded 0 libraries in 229ms.
Reloaded 0 libraries in 286ms.
Reloaded 0 libraries in 199ms.
```

In fact, which will cause quite lag for some cases, though, the real UI in device never changed as edit a dart file directly, but, there still exist a performance loss after hours editing ruby file. (in this case, never need reload any flutter UI)

**Comment by ericdallo** [comment]
Yeah, we should check yaml and dart files before reloading
