### ISSUE TITLE
How to get started with dap-mode and Flutter/Dart

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#14]
I saw that `lsp-dap-dart.el` is now available and tried to figure out how to get started, but so far was only able to get some error messages. It's unclear what dap-dart is supposed to do exactly and what the prerequisites are so that it can be used with a Dart or Flutter project.

- Do I need to start devtools manually before `dap-debug`?
- Do I need to run the application manually before `dap-debug`?
- Can I pass additional arguments like flavor like shown in https://github.com/flutter/flutter/issues/25363#issuecomment-447376292
- Anything else that needs to be done to discriminate between plain Dart and Flutter project?
- How can I change/delete created dap debug templates?

Currently `M-x dap-debug` results in this output, which seems to indicate that the project is recognized as a plain Dart project instead of as a Flutter project but I do not know where I could change that:

```
lib/main_zoechi.dart: Warning: Interpreting this as package URI, 'package:lookatmybaby_flutter/main_zoechi.dart'.
../../../../../flutter/packages/flutter/lib/src/widgets/app.dart:30:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Locale;
^
../../../../../flutter/packages/flutter/lib/src/widgets/basic.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Image, ImageFilter, TextHeightBehavior;
       ^
../../../../../flutter/packages/flutter/lib/src/widgets/binding.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' show AppLifecycleState, Locale, AccessibilityFeatures, FrameTiming, TimingsCallback;
       ^
../../../../../flutter/packages/flutter/lib/src/widgets/binding.dart:21:1: Error: Not found: 'dart:ui'
export 'dart:ui' show AppLifecycleState, Locale;
^
../../../../../flutter/packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show Color;
       ^
../../../../../flutter/packages/flutter/lib/src/widgets/color_filter.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../../../../flutter/packages/flutter/lib/src/widgets/editable_text.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui hide TextStyle;
       ^
../../../../../flutter/packages/flutter/lib/src/widgets/focus_manager.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../../../../flutter/packages/flutter/lib/src/widgets/focus_traversal.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../../../../flutter/packages/flutter/lib/src/widgets/framework.dart:16:1: Error: Not found: 'dart:ui'
export 'dart:ui' show hashValues, hashList;
^
```

**Comment by zoechi** [comment]
> How can I change/delete created dap debug templates?

Seems to be similar to dap-mode#237

**Comment by ericdallo** [comment]
Currently `lsp-dart-dap.el` is only supported by Dart, the Flutter support is the next thing on my TODO list, so I think in the next days I should release this feature.
For the Dart support, DevTools is automatically installed, started and opened via the `lsp-dart-dap-open-devtools` command, that was [released yesterday](https://github.com/emacs-lsp/lsp-dart/releases/tag/1.7.0)

To setup the DAP, you can check [this section on Readme](https://github.com/emacs-lsp/lsp-dart#debug)

**Comment by zoechi** [comment]
I see. Looking forward trying it out :)

**Comment by zoechi** [comment]
> Can I pass additional arguments like flavor like shown in flutter/flutter#25363 (comment)

will probably work like in dap-mode#247

**Comment by ericdallo** [comment]
Yeah, @zoechi, you already can register a custom template by yourself, but I'll add more default templates for debug similar how VSCode does today.

**Comment by zoechi** [comment]
I haven't used VSCode myself, but Danny did solid work there from what I have seen. 
Great to see Emacs will benefit from his work as well \o/

**Comment by ericdallo** [comment]
Thanks! Danny's work is helping me a lot on implementing these features :)

**Comment by ericdallo** [comment]
@zoechi, the current latest release, `1.8.0`, adds the Flutter debug support :)
