### ISSUE TITLE
[Feature Request] Wrap the widget under the point into another widget(e.g. container)

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#141]
Basically, we have the similar feature in left flutter outline window, as following screenshot.

![image](https://user-images.githubusercontent.com/549126/151340940-4720361b-26f0-4566-a3d3-e1c75f12ed82.png)

but, i think it not conveniently because find the widget under the point in this outline window is not so easy anyway, so i consider, we can improve this two different way.

1.  Following current editing widget in flutter outline window, that is, when we are editing a Container, we can active that Container in flutter outline async, because we are a issue as we discussed on #127, if this is not possible for performance reason, we can try 2
2. Add a right menu sub-item to enable wrap element on the point into the following default right click menu.

![image](https://user-images.githubusercontent.com/549126/151342442-c643c959-de9c-4bb0-ad9c-2cb124077909.png)

**Comment by PatrickWulfe** [comment]
You can do this with eglot using eglot-code-actions

**Comment by ericdallo** [comment]
Via code actions this is possible as well using lsp-mode

**Comment by ericdallo** [comment]
It's not clear to me what is the feature requested @zw963, code actions already provide wrapping widget
![image](https://user-images.githubusercontent.com/7820865/173154743-7208b3d1-a330-4dac-86a3-a3f642a65b16.png)

**Comment by zw963** [comment]
Wired, It still not works for me ...

![image](https://user-images.githubusercontent.com/549126/173179968-7deb83ab-3915-4a32-afca-115c66cee1ea.png)

**Comment by ericdallo** [comment]
That's weird indeed, all those cases work for me, @DanTup is there anything on the server-side that may not return "wrap widget" code actions?

**Comment by DanTup** [comment]
I'm not sure without a repro. I notice in the screenshots above there's a difference with `return Foo()` vs `final app = Foo();`.. does that change things?

If not, some exact code this repros on and a log of the LSP traffic might help figure it out.

**Comment by ericdallo** [comment]
You are correct @DanTup !
I don't get wrap widget code actions if trying on a widget that belongs to a variable: `final foo = MaterialApp();`

**Comment by zw963** [comment]
> 

I try record IO in the last wrappered example.

```
[Trace - 10:17:59 AM] Sending request 'textDocument/codeAction - (40)'.
Params: {
  "textDocument": {
    "uri": "file:///home/zw963/test_project/lib/app.dart"
  },
  "range": {
    "start": {
      "line": 199,
      "character": 16
    },
    "end": {
      "line": 199,
      "character": 16
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 10:17:59 AM] Received response 'textDocument/codeAction - (40)' in 17ms.
Result: [
  {
    "title": "Sort Members",
    "kind": "source.sortMembers",
    "command": {
      "title": "Sort Members",
      "command": "edit.sortMembers",
      "arguments": [
        "/home/zw963/test_project/lib/app.dart"
      ]
    }
  },
  {
    "title": "Organize Imports",
    "kind": "source.organizeImports",
    "command": {
      "title": "Organize Imports",
      "command": "edit.organizeImports",
      "arguments": [
        "/home/zw963/test_project/lib/app.dart"
      ]
    }
  },
  {
    "title": "Fix All",
    "kind": "source.fixAll",
    "command": {
      "title": "Fix All",
      "command": "edit.fixAll",
      "arguments": [
        "/home/zw963/test_project/lib/app.dart"
      ]
    }
  },
  {
    "title": "Extract Method",
    "kind": "refactor.extract",
    "command": {
      "title": "Extract Method",
      "command": "refactor.perform",
      "arguments": [
        "EXTRACT_METHOD",
        "/home/zw963/test_project/lib/app.dart",
        0,
        6228,
        0,
        null
      ]
    }
  },
  {
    "title": "Extract Local Variable",
    "kind": "refactor.extract",
    "command": {
      "title": "Extract Local Variable",
      "command": "refactor.perform",
      "arguments": [
        "EXTRACT_LOCAL_VARIABLE",
        "/home/zw963/test_project/lib/app.dart",
        0,
        6228,
        0,
        null
      ]
    }
  },
  {
    "title": "Extract Widget",
    "kind": "refactor.extract",
    "command": {
      "title": "Extract Widget",
      "command": "refactor.perform",
      "arguments": [
        "EXTRACT_WIDGET",
        "/home/zw963/test_project/lib/app.dart",
        0,
        6228,
        0,
        null
      ]
    }
  }
]
```

**Comment by zw963** [comment]
Yep, i can make it works when i try to directly show action on following returned widget instead.

![image](https://user-images.githubusercontent.com/549126/173481030-12997832-b686-47f5-a81e-766b18f1ddb1.png)

Following is lsp output log

http://dpaste.com/E78YBYJTY


Another strange things is, when i select widget use region, then show action, it get different result.

![image](https://user-images.githubusercontent.com/549126/173481317-0d707f18-4f10-4649-a5ed-85b43037919b.png)

**Comment by ericdallo** [comment]
Awesome @DanTup thank you!
@zw963 we can keep this open until the fix on dart-sdk is merged
