### ISSUE TITLE
[Feature Request] run lsp-dart-run automatically when run lsp-dart-dap-flutter-hot-reload/restart?

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#143]
This was not a bug, just a discuss.

because i binding `lsp-dart-dap-flutter-hot-restart` to a keybinding, so, i expected to this command(and ???-hot-reload) command can start `lsp-dart-run` automatically when i pressing my keybinding, that should be a reasonable default too, and, if user do native desktop development, it is more easy to terminate current app then emulator, which cause user have to run `lsp-dart-run` manually again.

Thank you.

**Comment by ericdallo** [comment]
If I understood it correctly, you want `lsp-dart-dap-flutter-hot-restart`/`lsp-dart-dap-flutter-hot-reload` to run `lsp-dart-run` automatically if no session is running yet?

**Comment by zw963** [comment]
> If I understood it correctly, you want `lsp-dart-dap-flutter-hot-restart`/`lsp-dart-dap-flutter-hot-reload` to run `lsp-dart-run` automatically if no session is running yet?

Yes, i think we can more better, :smile:, in fact, `hover.el` do things like this, right?

**Comment by ericdallo** [comment]
yes, feel free to open a PR

**Comment by zw963** [comment]
In fact, this one is too hard for me to contribute ... sorry.

**Comment by zw963** [comment]
> @zw963 done on commit above, could you confirm later?

It works when after start emacs, run lsp-dart the first time, Cool!

but, it seem like not works if start then terminate.

Following is reproduce use linux desktop:

1.  run `lsp-dart-dap-flutter-hot-restart` to start linux desktop, it works.
2.  because some reason, i close my linux desktop app.
3. try run ``lsp-dart-dap-flutter-hot-restart``
4.  I get a message:  dap--send-message: Session Flutter Run is already terminated


thank you very much.

**Comment by ericdallo** [comment]
Hum, this sounds like a dap-mode bug :( Not sure there is anything to do on lsp-dart
