### ISSUE TITLE
Get many error after jump into current project dependency libraries with lsp-ui-peek-find-definitions.

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#146]
**Describe the bug**
We use library, named. infinite_scroll_pagination, I can jump to following page successful when i run `lsp-ui-peek-find-definitions`
on PagedChildBuilderDelegate class, this was expected. but after jump into this file, that is.

/home/zw963/.pub-cache/hosted/pub.flutter-io.cn/infinite_scroll_pagination-3.1.0/lib/src/core/paged_child_builder_delegate.dart:13

I get many errors, which cause jump to other definition in this file not possible, because those definition not found, need be defined.

![image](https://user-images.githubusercontent.com/549126/153464738-aa8cd8fd-22b4-44de-a0a5-9003bbbf9e07.png)

But continue to jump works quite well when use with code.

BTW:  i can always jump to file defined on my own project, and jump again, that works.

**Comment by zw963** [comment]
Even somethings broken when i jump to any dependency libraries, even on the entry file.

![image](https://user-images.githubusercontent.com/549126/153469903-295f4ca1-1dc0-4c21-b8f5-ca1273da2ab0.png)

Was somethings config wrong?

```sh
 ╰─ $ flutter --version
Flutter 2.8.1 • channel unknown • unknown source
Framework • revision 77d935af4d (8 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
 ╰─ $ cat pubspec.yaml |egrep 'infinite|graphql'
  graphql_flutter: ^5.0.0
  infinite_scroll_pagination: ^3.1.0
```

**Comment by zw963** [comment]
> you didn't imported the project root

What you means of project root is for which one? my working on project, or the library?

**Comment by ericdallo** [comment]
the working project, the one lsp-mode set and send to server when initializing, you can check

**Comment by zw963** [comment]
> the working project, the one lsp-mode set and send to server when initializing, you can check

I don't know why, after i fallback to keep `(setq lsp-auto-guess-root nil)` use default value, it start to work.

thank you very much.
