### ISSUE TITLE
[Question] The correct way to reload the lsp-dart and flycheck after add a new package into pubspec.yml

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#148]
What is the correct way to reload the current project after add a new package into current package?

When i add a new package into my project, i have to run `dap-delete-all-sessions` then `lsp-dart-run` again to make this new package available, It seem like hot-reload or hot-restart all not take effect.

In fact, even, one or two times, after i rerun `lsp-dart-run` and i can run my app successful, i still get many flycheck error as following screenshot.

![image](https://user-images.githubusercontent.com/549126/154791111-800dba28-ca60-4520-bf26-be9f532fed1d.png)

After i restart my emacs, those flycheck error message gone.

So, i just curious, what is the CORRECT way to do after add a new package into pubspec.yml?

Thank you.

**Comment by ericdallo** [comment]
to fix the errors, you can `lsp-workspace-restart` after `lsp-dart-pub-get`
