### ISSUE TITLE
Duplicate `print` Logs When Using Node Debugger

### ISSUE THREAD

**Issue by Walheimat** [emacs-lsp/lsp-dart#154]
**Describe the bug**

Calls to `print` are inserted twice into the debug output buffer.

**To Reproduce**

1. Use the following config:
    ```emacs-lisp
    (use-package lsp-dart
      :custom
      (lsp-dart-dap-use-sdk-debugger nil))
    ```
2. Call `lsp-dart-dap-setup`.
3. Create a sample project (`flutter create <name>`, should give you counter app).
4. Put a `print` statement into the `_incrementCounter` method.
5. Start a debug session using the "Flutter :: Debug" template.
6. Click on fab.
7. Every print call yields the same message twice.

When I set the `dap-handle-event` for `dart.log` in `lsp-dart-dap.el` to nil, it's only logged once. So somewhere, somehow, the logging already happens without the handler doing it.

I'm currently advising the function to avoid this but maybe there's a proper fix for this.

**Expected behavior**

A print statement is only inserted into the buffer once.

**Version**

```
[LSP Dart] 1.21.0 at 2022.04.07 @ Emacs 29.0.50
[Dart SDK] Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "linux_x64"

[Flutter SDK] /home/walheimat/snap/flutter/common/flutter
[Flutter project] true
[Project entrypoint] /home/karusster/tests/flutters/myapp/lib/main.dart
```

**Comment by ericdallo** [comment]
@Walheimat thanks for the report, sounds related to this [recent commit](https://github.com/emacs-lsp/lsp-dart/commit/01b58674842197eb565fdbaa723e9e536ae6d6ab), I'll fix it before a new release but meanwhile using the debugger built-in on dart should be the best, also the new recommended way for recent flutter/dart sdks

**Comment by ericdallo** [comment]
Any reason you have `lsp-dart-dap-use-sdk-debugger` as nil?

**Comment by Walheimat** [comment]
Yes, the SDK debugger sessions randomly exit for me. I haven't had time to look into it so I just went back to the old way.

**Comment by ericdallo** [comment]
@Walheimat also, the built-in dart sdk debugger only works for dart-sdks > 2.16.0, so for versions before that only the node extension is possible

**Comment by Walheimat** [comment]
I upgraded, same issue.

```
[LSP Dart] 1.21.0 at 2022.04.09 @ Emacs 29.0.50
[Dart SDK] Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "linux_x64"

[Flutter SDK] /home/karusster/snap/flutter/common/flutter
[Flutter project] true
[Project entrypoint] /home/karusster/tests/flutters/myapp/lib/main.dart
```

**Comment by ericdallo** [comment]
Right, it seems to happen only with flutter not dart, will test in a flutter sample

**Comment by ericdallo** [comment]
@Walheimat I think this was fixed recently on latest release, could you confirm?

**Comment by Walheimat** [comment]
I'll have a look later, thanks.

**Comment by Walheimat** [comment]
Unfortunately can't confirm:

```dart
print("test one");
print("test two");
```

... leads to ...

```
I/flutter ( 3104): test one
I/flutter ( 3104): test one
I/flutter ( 3104): test two
I/flutter ( 3104): test two
```

I'm guessing this is the latest version:

```
[LSP Dart] 1.22.0 at 2022.06.11 @ Emacs 29.0.50
[Dart SDK] Dart SDK version: 2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "linux_x64"

[Flutter SDK] /home/karusster/snap/flutter/common/flutter
[Flutter project] true
[Project entrypoint] /home/karusster/tests/flutters/print_test/lib/main.dart
```

Btw, I have this hack in my config to avoid the issue if anyone else has this:

```elisp
;; HACK: Temporary empty override to avoid duplicate logs.
(cl-defmethod dap-handle-event ((_event (eql dart.log)) _session _params)
  "Handle debugger uris EVENT for SESSION with PARAMS."
  nil)
```

**Comment by Walheimat** [comment]
Would love to, but I can't start anything anymore because of `(wrong-type-argument stringp ("daemon"))`.

**Comment by Walheimat** [comment]
You closed it already, but just tested with the latest commit and I no longer seem to get duplicate logs.
