### ISSUE TITLE
"Invalid file path" error with lsp-find-definition in Dart core library

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#16]
**Describe the bug**
When I navigate to a Dart code library file from custom source code it works fine, but when I want to jump further from there, I only get the mentioned error.

For example if I use `lsp-find-definition` from a `String` type in a custom source file or in a file of a dependency (in `~/.pub-cach/hosted/...`) it works fine,  
but if I try to do it in a core library file, for example I navigate to `DateTime` and then try to navigate `String` from there, I only get the error. 

```
LSP :: Invalid file path [5 times]
lsp-request: Invalid file path
```
setting `lsp-log-io` to `t` doesn't lead a to more detailed output.

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page.

**To Reproduce**
{populate}

**Expected behavior**
{populate}

**Screenshots**

**Version**
Include here the result of: `M-x` `lsp-dart-version`
```
[LSP Dart] 1.8.0 (package: 20200430.1504) at 2020.05.04 @ Emacs 28.0.50
```

**Logs**
Please include the debug stack trace (if there is an error) and the content of Messages buffer with `lsp-print-io` set to t in case the bug is related to client->server communication.

**Comment by ericdallo** [comment]
Thanks for the report!
I tested on VScode with the LSP enabled and this not seems to happen, so the problem seems to be really in the `lsp-dart` client. I'll keep investigating

**Comment by ericdallo** [comment]
@zoechi The problem was that `lsp-dart` was not including the Dart SDK libraries to the LSP workspace, I released a fix, could you test it again? thanks!

**Comment by zoechi** [comment]
For me it is still the same behavior.

**Comment by ericdallo** [comment]
Odd, I followed your steps and could not reproduce with the latest release:

![lsp-dart-issue-16](https://user-images.githubusercontent.com/7820865/81358541-36b82080-90ad-11ea-93aa-731deda8bef0.gif)

Could you check your version @zoechi ?

**Comment by zoechi** [comment]
lsp-dart 20200504.1959
lsp-mode 20200507.2113

**Comment by zoechi** [comment]
It looks like when I jump from a Dart file in a Flutter project to a core type (`String`), then it's working fine.
If I jump to a package (for example `LogRecord` from the `logging` package) and then to a core type, it does not work anymore.

Also a bit unfortunate is that in the former case it jumps into `~/flutter/bin/cache/pkg/sky_engine/lib/core` (correct) and in the later to `/usr/lib/dart/lib/core` (wrong)

I control the `lsp-dart-project-sdk-dir` using `.dir-locals.el` and that is lost when I navigate from a Flutter project to a package.

**Comment by ericdallo** [comment]
hum, this should be a corner case for flutter lib...
I 'll try to reproduce and fix it if it's a problem...

**Comment by ericdallo** [comment]
@zoechi what's the value that you have on `lsp-dart-project-sdk-dir`?

**Comment by ericdallo** [comment]
I release a new fix that's not entirely related to this but it worth checking it again.
I fixed the way we check for the Dart SDK, before this, even with flutter and dart on PATH, `lsp-dart` chose the dart SDK, not the dart SDK from flutter cache dir.

**Comment by zoechi** [comment]
`lsp-dart-project-sdk-dir` is set to the Flutter location with `.dir-local.el` (I checked the value with files from my Flutter project. For all other files (Dart SDK, Flutter SDK, packages it's the default value `nil`

**Comment by zoechi** [comment]
I think there should be a way to specify `lsp-dart-sdk-dir` and `lsp-flutter-sdk-dir` (instead of `lsp-dart-project-sdk-dir` and it should automatically take one or the other depending on whether it is a Flutter or Dart project.
I believe this is how it is distinguished.

```yml
dependencies:
  flutter:
    sdk: flutter
```
That would also work for packages in `~/.pub-cache/hosted`

**Comment by ericdallo** [comment]
Yeah, it's a little messy the way `lsp-dart` find/get the sdks.
I'll refactor this to a VSCode similar way, where it checks if it is a flutter project to decide which Dart SDK use.
I'll add an option to specify flutter SDK path and dart SDK path too.

Thanks for the suggestion :)

**Comment by ericdallo** [comment]
Done on `1.10.1` release, @zoechi could you test it again please?

**Comment by ericdallo** [comment]
Just FYI @zoechi, I renamed [some variables](https://github.com/emacs-lsp/lsp-dart/pull/27/files#diff-04c6e90faac2675aa89e2176d2eec7d8L153):
 `lsp-dart-project-sdk-dir` -> `lsp-dart-sdk-dir`
 `lsp-dart-project-flutter-sdk-dir` -> `lsp-dart-flutter-sdk-dir`

**Comment by zoechi** [comment]
This seems to work fine now.

When I jump to declaration of `String` in a Dart project it jumps to the Dart SDK and when done from a Flutter project to the Flutter SDK.

Is `/home/user/flutter` the correct value for `lsp-dart-flutter-sdk-dir` or should it be `/home/user/flutter/bin/cache/dart-sdk`?
It worked with `/home/user/flutter` but I think it would be helpful to have this in the docs.

The Flutter SDK is not found though when `lsp-dart-flutter-sdk-dir` is not explicitly set.
I don't see a reason why it couldn't be found.
`flutter` executable is included in `exec-path` and `(get-env "PATH")` (inside Emacs)

The Dart SDK is found automatically even when `lsp-dart-sdk-dir` is `nil`.

**Comment by zoechi** [comment]
`dap-debug` only seems to work with `lsp-dart-flutter-sdk-dir` `/home/user/flutter/bin/cache/dart-sdk`

**Comment by zoechi** [comment]
I don't know why it worked once with `lsp-dart-sdk-dir` set to `nil`.
Now lsp won't start and instead suggest to install dart-analyzer.
Previously I updated the variables and executed `M-x` `lsp-workspace-restart` and closed/reopened the buffer but that doesn't seem to be enough.

**Comment by ericdallo** [comment]
`lsp-dart-flutter-sdk-dir` should point to your flutter root: example `/home/user/flutter`
`lsp-dart-sdk-dir` should point ot your dart sdk root: example `/home/user/dart`

I'll add a info about these

**Comment by ericdallo** [comment]
Updated the [Docs](https://emacs-lsp.github.io/lsp-dart/#supported-settings), if this is not working as described, could reply it?

**Comment by zoechi** [comment]
I somehow missed your response.
`(lsp-dart-get-sdk-dir)` and `(lsp-dart-get-flutter-sdk-dir)` both print the correct directory.

If I navigate (`lsp-find-definition`) to a core library type from within a Flutter project, it opens the file from the Flutter SDK. If I then navigate again from there, it opens a file from the Dart SDK which is wrong in my opinion. This doesn't seem to be 100% reproducible though.

If I navigate to a Flutter dependency (`firebase_crashlytics`) and then further to an SDK type (`String`) it opens `string.dart` from the Dart SDK and prints 

> LSP :: Invalid file path [2 times]

This case reproduced every time. I think it should open from Flutter SDK in this case.

I also get this "Invalid file path" output if I navigate to a normal Dart package (not Flutter specific) and then to an SDK type. It opens a file from the Dart SDK, which is correct in my opinion in this case.

**Comment by ericdallo** [comment]
@zoechi I see the problem now, the problem is that when you enter in a file inside the dart SDK in Flutter SDK, `(lsp-dart-flutter-project-p)` returns false... I'll try to think on something to fix that.

About the `Invalid file path` message, this is a message sent by the dart SDK when you are analysing a external project, this happens to VSCode extension too with the `lsp-preview` flag enabled:
![image](https://user-images.githubusercontent.com/7820865/82683431-69bef000-9c27-11ea-8ead-c0ff43fe2031.png)

I think you can fix this on `lsp-dart` setting `lsp-dart-only-analyze-projects-with-open-files` to `nil`.

**Comment by ericdallo** [comment]
I pushed a new release, `1.11.4`, which may fix your problem using the Dart SDK inside Flutter SDK when entering dart classes.
