### ISSUE TITLE
Is there a way to hidden the upper debug menu when do lsp-dart-run ?

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#161]
Maybe this is not a lsp-dart issue, more like a question, i just ask here, thank you.

please check following screenshot.

![image](https://user-images.githubusercontent.com/549126/167596311-aa9699e2-1fa7-4f85-88ca-baa5715262d7.png)

Is there a way to disable above menu bar? anyway, it always hidden my current buffer tab name or buffer name.

**Comment by ericdallo** [comment]
yes, it's from `dap-mode`, check `dap-auto-configure-features` variable, you want to remove the `controls` from that var
