### ISSUE TITLE
Flutter 3 debug support issues on some cases on MacOS

### ISSUE THREAD

**Issue by elken** [emacs-lsp/lsp-dart#163]
**Describe the bug**
Trying to `dap-debug` in [`flutter_sample`](https://github.com/ericdallo/flutter_sample) causes a JSON parsing error to show up.

Making a minor change in `lsp-dart-flutter-daemon--raw->response` to print the incoming response, it's truncated by something and returned in a batch.

**To Reproduce**
<will add repro-able init.el here>

**Expected behavior**

Being able to debug a flutter project

**Screenshots**

![image](https://user-images.githubusercontent.com/2872862/169299805-ca97814b-d196-42f6-bfb0-5d475d163ad2.png)

**Version**
```
[Flutter SDK] /opt/homebrew/Caskroom/flutter/3.0.0/flutter/
[Flutter project] false
[Project entrypoint] Not found
[LSP Dart] 1.21.0 at 2022.05.19 @ Emacs 28.1
[Dart SDK] Dart SDK version: 2.17.0 (stable) (Mon May 9 10:36:47 2022 +0200) on "macos_arm64"

[Flutter SDK] /opt/homebrew/Caskroom/flutter/3.0.0/flutter/
[Flutter project] true
[Project entrypoint] /Users/elken/build/test/lsp-dart/flutter_sample/lib/main.dart
```

**Comment by ericdallo** [comment]
I can't repro that, so I think it's something specific to the json, could you paste the json that show on the lsp dart flutter daemon buffer?

**Comment by elken** [comment]
> I can't repro that, so I think it's something specific to the json, could you paste the json that show on the lsp dart flutter daemon buffer?

It's likely due to the sheer amount of devices I have. Try adding a bunch of emulators, but JSON [here](https://gist.github.com/elken/35392c5d07cfc9b7a654065525b8ef78)

**Comment by elken** [comment]
OK so this gets weirder, there's something funky with the response.

If I open the daemon buffer, go to one of the "faulty" lines and do `beginning-of-line` it takes me halfway through to where it would normally split...

**Comment by elken** [comment]
https://user-images.githubusercontent.com/2872862/169472110-b7105aa0-cae5-4e88-92b7-5521c8dfb533.mov

All I'm doing is `C-a` and `C-e` (turned evil off to see if that was confusing it)

**Comment by elken** [comment]
I also get the same behaviour on eglot, so it's not even related to lsp-mode :/

Is it worth @'ing DanTup to assist here?

**Comment by fosskers** [comment]
Upon running `dap-debug` I get:

> Debug session process exited with status: killed

After the UI briefly flashes with some cool colours and UI elements.

**Comment by elken** [comment]
Repro case:

1. Clone `flutter_sample`
2. Change branch to `flutter-3.0`
3. `emacs -Q -l dap.el` with the below
```lisp
(setq user-emacs-directory "/tmp/emacs")
(setq package-user-dir (expand-file-name "elpa" user-emacs-directory))
(when (boundp 'native-comp-eln-load-path)
  (push (expand-file-name "eln-cache" user-emacs-directory) native-comp-eln-load-path))

(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)

(setq package-selected-packages
  '(dart-mode lsp-mode lsp-dart lsp-treemacs flycheck company
    ;; Optional packages
    lsp-ui company hover))

(when (cl-find-if-not #'package-installed-p package-selected-packages)
  (package-refresh-contents)
  (mapc #'package-install package-selected-packages))

(add-hook 'dart-mode-hook 'lsp)

(setq gc-cons-threshold (* 100 1024 1024)
      read-process-output-max (* 1024 1024))

(find-file "~/build/test/lsp-dart/flutter_sample/lib/main.dart")
```
4. `dap-debug`
5. `Flutter :: Debug`
6. Select any emulator

**Comment by elken** [comment]
So I "think" I know what's happening.

Something is truncating the buffer, nothing I do seems to resolve it. `inhibit-field-text-motion t` makes the buffer work correctly, but it doesn't make `comint-output-filter` take the whole line.

My first thought is to refactor the comint buffer to print the commands and use them as "prompts" to say anything inbetween them is the response (as long as there's a matching `[]`). WDYT @ericdallo ?

**Comment by ericdallo** [comment]
@elken I can't repro the json issue, I'm starting to think it happens only on your emacs :/ I have 3 emulators including linux native device but not getting that issue, could you try using the old debugger to check if it works? you need to disable `lsp-dart-dap-use-sdk-debugger` and remember to `lsp-dart-dap-setup`

**Comment by elken** [comment]
Others have reported before in the discord, so it's either related to macos or emacs-plus or something else then maybe. Not sure.

No change, it fails before it even gets to hit the debugger.

I'm working on refactoring it to include a JSONRPC version to see if that changes it.

**Comment by ericdallo** [comment]
@yyoncho any suggestions on how to debug that json parse error? it seems to me something related to a minor mode or something that it's preventing beginning of the buffer works properly

**Comment by elken** [comment]
Finally got around to testing on Linux, and there is indeed no issue here it seems.

So it seems to somehow related to macOS...

**Comment by elken** [comment]
https://gist.github.com/elken/852f5656e2416c5b695710db18416df9

Output of `(buffer-string)` in the daemon buffer after running and trying to trigger the issue. With the latest commits, I can also start the chrome debugger, but it fails with the same error shortly after. 

I've tried with the nix version of emacs 28.1 and emacs-mac with the exact same result.

**Comment by nidyaonur** [comment]
Any progress on this issue? I am having the exact same issue with @elken.

**Comment by elken** [comment]
#165 was started as a means to address this properly as it's definitely just comint (and provide a faster, stable interface overall) but I have since been moved away from the flutter project that was blocking me.

If eric is able to find time to review what's there I can try and look further :D

**Comment by ericdallo** [comment]
@elken I thought it was not ready because of tests failing :)
Could you rebase and fix tests?

**Comment by elken** [comment]
> @elken I thought it was not ready because of tests failing :) Could you rebase and fix tests?

There are a couple of issues I was struggling to resolve, but I will look into fixing them when I can :)

**Comment by jvliwanag** [comment]
Encountering a similar issue here.

In my particular case, the error is:

```
error in process filter: could not parse JSON stream: "invalid token near 'fal'", "<string>", 1, 1024, 1024 [4 times]
```

Now, opening `*LSP Dart - Flutter daemon` buffer, the interesting bit is that this first displays ---

```
[{"id":55744,"result":[{"id":"28FE18E8-C80A-4EFF-987D-6CE94AB317E8","name":"iPhone 13","platform":"ios","emulator":true,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":"apple_ios_simulator","sdk":"com.apple.CoreSimulator.SimRuntime.iOS-15-0","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":true,"fastStart":false,"flutterExit":true,"hardwareRendering":false,"startPaused":true}},{"id":"macos","name":"macOS","platform":"darwin","emulator":false,"category":"desktop","platformType":"macos","ephemeral":false,"emulatorId":null,"sdk":"macOS 12.4 21F79 darwin-arm","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":false,"flutterExit":true,"hardwareRendering":true,"startPaused":true}},{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null,"sdk":"Google Chrome 103.0.5060.53","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":fal
```

Note that the message itself was cut short ending at `fal`. And then after a while, it then completes the line to:

```
[{"id":55744,"result":[{"id":"28FE18E8-C80A-4EFF-987D-6CE94AB317E8","name":"iPhone 13","platform":"ios","emulator":true,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":"apple_ios_simulator","sdk":"com.apple.CoreSimulator.SimRuntime.iOS-15-0","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":true,"fastStart":false,"flutterExit":true,"hardwareRendering":false,"startPaused":true}},{"id":"macos","name":"macOS","platform":"darwin","emulator":false,"category":"desktop","platformType":"macos","ephemeral":false,"emulatorId":null,"sdk":"macOS 12.4 21F79 darwin-arm","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":false,"flutterExit":true,"hardwareRendering":true,"startPaused":true}},{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null,"sdk":"Google Chrome 103.0.5060.53","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":false,"flutterExit":false,"hardwareRendering":true,"startPaused":true}}]}]
```

**Comment by jvliwanag** [comment]
Looks like Mac users fall into the 1024 max line length: https://github.com/emacs-mirror/emacs/blob/9c9e34e9b683b6b548d92dc7c1ed57f06f62eefb/lisp/comint.el#L492

**Comment by elken** [comment]
> Looks like Mac users fall into the 1024 max line length: https://github.com/emacs-mirror/emacs/blob/9c9e34e9b683b6b548d92dc7c1ed57f06f62eefb/lisp/comint.el#L492

https://github.com/emacs-lsp/lsp-dart/issues/163#issuecomment-1133553643 please read the whole thread before commenting :)

**Comment by jvliwanag** [comment]
Apologies for the duplicate. :) Perhaps the add here is that, 1024 limit is probably just on the mac. Linux and Windows users won't run into it.

**Comment by jvliwanag** [comment]
Not particularly good with elisp, and unsure what this does. But setting this before launching any dart project solves the issue.

```
(setq process-connection-type nil)
```

**Comment by elken** [comment]
Doesn't work here

**Comment by jvliwanag** [comment]
Needs to get it set before daemon process start. Just to test the workaround, do put it on init.el

**Comment by elken** [comment]
I did, and it's probably not something that should be set globally anyway.

**Comment by ericdallo** [comment]
This should be fixed by https://github.com/emacs-lsp/lsp-dart/pull/165, LMK otherwise
