### ISSUE TITLE
dart analysis server stuck on status starting

### ISSUE THREAD

**Issue by flexv99** [emacs-lsp/lsp-dart#166]
**Describe the bug**
When openening a .dart file the dart analysis server does not start and I the following shows up in the *Messages* buffer:
`LSP :: Connected to [dart_analysis_server:14656/starting].
LSP :: Error from the Language Server: Invalid params for initialize:
params.processId must be of type int (Invalid Parameters)`

I tried various custom lsp-dart-server-commands, but was not able to get it working

Has someone had a similar issue?

**Version**
`[LSP Dart] 1.22.0 at 2022.06.10 @ Emacs 29.0.50
[Dart SDK] Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64`

**Comment by flexv99** [comment]
> Sounds like some issue on the processId arg sent from lsp-mode to the server, could you try updating lsp-mode package as well?

Looking at the logs the `processId` is `null`

**Comment by ericdallo** [comment]
It seems we send processId manually nil [here](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L7337), so not sure this is the problem as it works for all lsp clients and for me on lsp-dart. Also, according to the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams), this param can be null.

Is this message `Invalid params for initialize: params.processId must be of type int` coming from the server?

**Comment by flexv99** [comment]
I think it's coming from the server, but I am not sure i get this in the echo area and in the *Messages* buffer

**Comment by flexv99** [comment]
I hardcoded the processId inside `lsp-mode.el` to a random integer value and now it works but I don't know if I should let it like this

**Comment by ericdallo** [comment]
@yyoncho do you know why lsp-mode could be sending the processId null?

**Comment by yyoncho** [comment]
... and processId is optional.

**Comment by ericdallo** [comment]
Hum, so if it's optional the server must be complaining about it, right?
@DanTup would you mind checking if the dart LSP server is making that required?

**Comment by yyoncho** [comment]
> Hum, so if it's optional the server must be complaining about it, right?

it should accept null as a valid value

**Comment by DanTup** [comment]
Is it possible to get the logs? I checked the code for the version quoted above (2.16.2) here:

https://raw.githubusercontent.com/dart-lang/sdk/2.16.2/pkg/analysis_server/lib/lsp_protocol/protocol_generated.dart

But the check looks like this:

```dart
        final processId = obj['processId'];
        if (processId != null && !(processId is int)) {
          reporter.reportError('must be of type int');
          return false;
        }
```

Which looks reasonable to me. It'd be good to review the full payload and see what's going wrong.

**Comment by ericdallo** [comment]
@flexv99 could you help get the client<->server logs following [this](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/#log-client-server-json)?

**Comment by flexv99** [comment]
`[Trace - 09:48:20 PM] Sending request 'initialize - (1)'.
Params: {
  "processId": null,
  "rootPath": "/Users/flex99/test",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.3.0, NS appkit-2113.30 Version 12.2.1 (Build 21D62))\n of 2022-02-25"
  },
  "rootUri": "file:///Users/flex99/test",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true,
      "codeLens": {
        "refreshSupport": true
      },
      "fileOperations": {
        "didCreate": false,
        "willCreate": false,
        "didRename": true,
        "willRename": true,
        "didDelete": false,
        "willDelete": false
      }
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "isPreferredSupport": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        },
        "resolveSupport": {
          "properties": [
            "edit",
            "command"
          ]
        },
        "dataSupport": true
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "resolveAdditionalTextEditsSupport": true,
          "insertReplaceSupport": true,
          "deprecatedSupport": true,
          "resolveSupport": {
            "properties": [
              "documentation",
              "detail",
              "additionalTextEdits",
              "command"
            ]
          },
          "insertTextModeSupport": {
            "valueSet": [
              1,
              2
            ]
          }
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true,
        "tooltipSupport": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": {
        "dynamicRegistration": true
      },
      "callHierarchy": {
        "dynamicRegistration": false
      },
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [
            1,
            2
          ]
        },
        "versionSupport": true
      },
      "linkedEditingRange": {
        "dynamicRegistration": true
      }
    },
    "window": {
      "workDoneProgress": true,
      "showMessage": null,
      "showDocument": {
        "support": true
      }
    },
    "experimental": {
      "snippetTextEdit": true
    }
  },
  "initializationOptions": {
    "onlyAnalyzeProjectsWithOpenFiles": null,
    "suggestFromUnimportedLibraries": true,
    "closingLabels": true,
    "outline": true,
    "flutterOutline": true
  },
  "workDoneToken": "1"
}


[Trace - 09:48:20 PM] Received response 'initialize - (1)' in 515ms.
Result: {
  "code": -32602,
  "message": "Invalid params for initialize:\nparams.processId must be of type int"
}
`

**Comment by ericdallo** [comment]
And we are indeed sending it as null right? so it seems the server is not handling properly @DanTup , since I can't repro this issue it could be some server corner case?

**Comment by yyoncho** [comment]
@flexv99 what is your server version?

**Comment by DanTup** [comment]
From the log snippet above it does seem like the servers issue, although at a glance the code seemed sound. I'll have to do some testing but I'm not around much this weekend so probably won't be till next week.

This generated code has changed a little recently, so it may be interested to try with the latest code (you can get bleeding edge builds at https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/).

Other than a short-term workaround, it shouldn't be necessary to change the client if it's conforming to the spec, the server definitely needs to too.

**Comment by DanTup** [comment]
>  @DanTup , since I can't repro this issue it could be some server corner case?

Sorry, missed this above. That definitely sounds odd if you're using the same Dart SDK version. Is it possible for you both to capture logs by passing `--instrumentation-log-file=/foo/log.txt` (set your own path) to the server and sending me everything up until the initialized response? (either here, or logs@dartcode.org). Using the servers log will eliminate any client display issue (although it's probably unlikely it's not printing exactly what's being sent).

**Comment by flexv99** [comment]
> @flexv99 what is your server version?

I am using version `1.32.8`

**Comment by yyoncho** [comment]
@flexv99 can you tell me what `M-: (lsp--json-serialize (list :processId nil)) RET` returns?

**Comment by DanTup** [comment]
btw there are some other places that show `null` in the client log shown above but were empty objects in the server log, for example:

```
"onlyAnalyzeProjectsWithOpenFiles"::{}
```

**Comment by flexv99** [comment]
> @flexv99 can you tell me what `M-: (lsp--json-serialize (list :processId nil)) RET` returns?

Sorry for the super late reply, as mentioned by @DanTup it returns:
`"{\"processId\":{}}"`

**Comment by yyoncho** [comment]
@flexv99 what is your emacs version? This is causing the issue.

**Comment by flexv99** [comment]
After using eglot for a while I gave it another try today first using `emacs 28.1` which did not change anything.
But I solved the issue changing [processID](https://github.com/emacs-lsp/lsp-mode/blob/b2dc84128fc6b2cd0460569bae6d0451856d2e0b/lsp-mode.el#L7363) from `nil` to `0`

**Comment by yyoncho** [comment]
@flexv99 I tried the reproduce the issue with these builds but I am unable to do so. Another user reported it here: https://github.com/emacs-lsp/lsp-mode/issues/3629#issuecomment-1193297553 and it was fixed after compiling it with native json support. Can you tell me if `(functionp 'json-serialize)` returns t? I suspect that the issue might be caused by jansson changes but without a reproducer it is hard for me to figure it out.
