### ISSUE TITLE
Cannot bring up LSP seesion

### ISSUE THREAD

**Issue by liurnd** [emacs-lsp/lsp-dart#17]
**Describe the bug**
Upon M-x lsp, LSP session is not created. Error message:

LSP :: The following servers support current file but do not have automatic installation configuration: dart_analysis_server

**Note**
lsp-dart-sdk-dir is set already.
(setq lsp-dart-sdk-dir "~/utils/dart-sdk")

**To Reproduce**
Open a dart file, M-x lsp

**Expected behavior**
LSP session should be created

**Version**
[LSP Dart] 1.8.0 at 2020.05.05 @ Emacs 28.0.50

**Logs**
Cannot get any logs as the session was not created. * lsp-log * buffer is not available also.

**Comment by ericdallo** [comment]
Are your `lsp-mode` and `lsp-dart` pacakges configured correctly?
Could you share you configuration?

**Comment by liurnd** [comment]
Yes I was using the same config previously but it stops working after i upgraded. 

My config:
```
(straight-use-package 'lsp-mode)
(straight-use-package 'dap-mode)
(straight-use-package 'lsp-ui)
(straight-use-package 'lsp-dart)

(require 'lsp-mode)
(setq lsp-ui-doc-enable nil)
(setq lsp-prefer-capf t)
(setq lsp-ui-sideline-show-diagnostics t)
(setq lsp-ui-sideline-show-hover t)
(setq lsp-ui-sideline-show-code-actions t)
(setq lsp-prefer-capf t)

(require 'lsp-dart)
(setq lsp-dart-sdk-dir "~/utils/dart-sdk")

(add-hook 'dart-mode-hook 'lsp-deferred)
```

Pls lmk where can i get more debug logs if that would help.

**Comment by ericdallo** [comment]
@liurnd, I believe this was a change on `1.6.2` where we renamed the `lsp-dart-sdk-dir` -> `lsp-dart-project-sdk-dir`. Can you fix it in your config and test it?

**Comment by liurnd** [comment]
It works now! Thx a lot

**Comment by justinjk007** [comment]
README still says to use the old variable `lsp-dart-sdk-dir`

**Comment by ericdallo** [comment]
Yeah, I renamed back @justinjk007 and @liurnd, I think that `lsp-dart-sdk-dir` is a more friendly name.

**Comment by justinjk007** [comment]
Its a little bit annoying when you make config breaking changes like this so often.

**Comment by ericdallo** [comment]
I know... It's just that I need to reorganize the project to keep the customizable variables the more friendly as possible, I do not pretend to change this again.

**Comment by oatmealm** [comment]
Where should this variable pointing for a Dart SDK that's part of a flutter SDK installation? I'm seeing this message when opening dart files. I did not install dart separately. Every thing else seems to work, including hover, so I'm assuming the basic configuration for the SDK locations (Android and Flutter) are correct.

**Comment by oatmealm** [comment]
Sorry, assuming it's bin/cache/dart-sdk...

**Comment by ericdallo** [comment]
@oatmealm currently, in a flutter project, if you have `flutter` command in your `PATH` env, everything should work, if you don't have it, you only need to set `lsp-dart-flutter-sdk-dir` pointing to the `flutter` root dir, after that, `lsp-dart` will automatically pickup the dart-sdk built-in in flutter `bin/cached-dart-sdk` dir.

**Comment by psygo** [comment]
I'm still having this issue. My config is as follows:

```lisp
(defun efs/lsp-mode-setup ()
  (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
  (lsp-headerline-breadcrumb-mode))

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :hook (lsp-mode . efs/lsp-mode-setup)
  :init
  (setq lsp-keymap-prefix "C-c l")
  :config
  (lsp-enable-which-key-integration t))

(use-package dart-mode)
(use-package lsp-dart
  :ensure t
  :hook (dart-mode . lsp))
(setq lsp-dart-flutter-sdk-dir "/home/philippe/Code/Flutter")
(use-package hover :ensure t)
```

Does anyone have an idea of what I'm doing wrong?

**Comment by ericdallo** [comment]
@psygo in the buffer when you face the error, could you provide the output of `M-x` `eval-expression` `lsp-dart-sdk-dir`?

**Comment by psygo** [comment]
@ericdallo, I'm getting back `nil`.

**Comment by ericdallo** [comment]
@psygo my bad, could you check both:
- `M-x` `eval-expression` `(lsp-dart-get-sdk-dir)`
- `M-x` `eval-expression` `(lsp-dart-get-flutter-sdk-dir)`

**Comment by psygo** [comment]
- `M-x` `eval-expression` `(lsp-dart-get-sdk-dir)` -> `nil`
- `M-x` `eval-expression` `(lsp-dart-get-flutter-sdk-dir)` -> `/home/philippe/Code/Flutter`, which is the path I had typed in the configuration above.

**Comment by ericdallo** [comment]
Alright, the issue is that `(lsp-dart-get-sdk-dir)` is returning nil, [here](https://github.com/emacs-lsp/lsp-dart/blob/master/lsp-dart-utils.el#L104-L105) it tries to find the dart sdk inside the flutter sdk if available, could you check if `(lsp-dart--flutter-project-p)` returns non nil in your buffer and if your flutter installation has this `bin/cache/dart-sdk/` folder inside it?

**Comment by psygo** [comment]
- `(lsp-dart--flutter-project-p)` is returning `nil`.
- Yes, I do have a `bin/cache/dart-sdk/` folder inside my `/home/philippe/Code/Flutter` folder.

**Comment by ericdallo** [comment]
Ok, so for some reason, it's not detecting that your project is a flutter one, could you please check the return of:
- `(lsp-dart-get-project-root)`
`(-some->> (lsp-dart-get-project-root) (expand-file-name "pubspec.yaml"))`

(I have in mind a `lsp-dart-doctor` to improve that debug later 😅 )

**Comment by psygo** [comment]
Both commands above return what I would expect:

- `(lsp-dart-get-project-root)` -> the correct root for my project
- `(-some->> (lsp-dart-get-project-root) (expand-file-name "pubspec.yaml"))` -> the correct path to my `pubspec.yaml` file

**Comment by ericdallo** [comment]
Alright, I think this is the last one to eval:
```elisp
(with-temp-buffer
  (insert-file-contents pubspec-path)
  (goto-char (point-min))
  (re-search-forward "sdk\s*:\s*flutter" nil t))
```

Just FYI I'm debugging this function: https://github.com/emacs-lsp/lsp-dart/blob/master/lsp-dart-utils.el#L71

**Comment by psygo** [comment]
How do I evaluate a multiline expression under `eval-expression`?

Anyway, the result will be non-existent because the project I'm using as a testing ground doesn't use Flutter actually, only Dart itself. Is that a problem for this package? Does it assume every project uses Flutter?

**Comment by psygo** [comment]
Just evaluated it as a one-liner, still `nil`.

**Comment by ericdallo** [comment]
Oh, I thought your project was a flutter one by your path... so you only have a dart project, right? if so, if `(lsp-dart-get-sdk-dir)` returns correct, it should work

**Comment by ericdallo** [comment]
@psygo I released lsp-dart 1.18.3 with some improvements on the `M-x` `lsp-dart-version` command which should give more details about the current project, it should be available soon on MELPA.

**Comment by zw963** [comment]
Hi, @ericdallo, following is my lsp-dart-version output:

```
[LSP Dart] unknown at 2021.08.25 @ Emacs 27.2
[Dart SDK] Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"

[Flutter SDK] /home/public/Dropbox/linux/utils/flutter/
[Flutter project] true
[Project entrypoint] /home/zw963/Dart/myapp/lib/main.dart

```

But, i always get following error output when i want to run `lsp` on dart-mode

```
LSP :: The following servers support current file but do not have automatic installation configuration: dart_analysis_server
You may find the installation instructions at https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).
```

**Comment by zw963** [comment]
BTW: following is my `(lsp-dart--server-command)`

("/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/dart" "/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot" "--lsp" "--client-id emacs.lsp-dart" nil)

all path is correct, in fact, i can run server successful like this: (like a server, blocked)

"/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/dart" "/home/public/Dropbox/linux/utils/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot" "--lsp" "--client-id emacs.lsp-dart" nil

**Comment by ericdallo** [comment]
Check `lsp-dart.el:127`, we actually use the correct path, the dart-sdk path (which for flutter projects is the flutter-root/bin/.cache/dart-sdk) + `bin/snapshots/analysis_server.dart.snapshot`

**Comment by ericdallo** [comment]
LMK if you still think there is something to improve/fix we can discuss that on a separate issue

**Comment by zw963** [comment]
> LMK if you still think there is something to improve/fix we can discuss that on a separate issue

create #116
