### ISSUE TITLE
lsp-dart treat current-buffer as entry function when run `lsp-dart-run`.

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-dart#173]
lsp-dart work REALLY REALLY WELL recent days! with offical debugger.

only one concern, when i run `lsp-dart-run`, it let me device,
but, it not let me select the entry function. in fact, it always
use current open buffer as entry, that not work well. will make
start failed.

the, the corrent working processing is, open project, and open
`lib/main.dart` first(this step is necessory), run `lsp-dart-run` to start work.

so, do we consider set lib/main.dart as a default?

or at least, add a option make lib/main.dart as default instead.

Thank you.

**Comment by ericdallo** [comment]
For dart projects, lsp-dart does this:
```elisp
(or (lsp-dart-get-project-entrypoint)
    (buffer-file-name))
```

that function `lsp-dart-get-project-entrypoint` checks the variable `lsp-dart-program-entrypoints` which already include the `lib/main.dart`, so not sure why it's not working for you

**Comment by zw963** [comment]
> ```emacs-lisp
> (lsp-dart-get-project-entrypoint)
> ```

Sorry, i consider maybe i run lsp-dart-run too early, even before lsp start sucessful.

i will back if other issue.

**Comment by zw963** [comment]
> Yeah, that's the problem, we should'n use `default-directory`, but probably `lsp-workspace-root`

But, when i open project root folder use step 1, lsp-workspace-root not exists, it only exists after i open a dart file in current project, and after lsp start correct, so, we still need check the return of this function if nil, if nil, we can use `default-directory` instead?

**Comment by ericdallo** [comment]
@zw963 it should be fixed to use lsp-workspace-root, could you try again?
