### ISSUE TITLE
weird output on generating override for build method in StatelessWidget

### ISSUE THREAD

**Issue by laynor** [emacs-lsp/lsp-dart#174]
**Describe the bug**

When I create a simple widget class 
```
class Foo extends StatelessWidget {
}
``` 
and then invoke `lsp-execute-code-action`  with the cursor on `Foo` I get this weird output:
```
class Foo extends StatelessWidget {
  @override
  Widget build(1|BuildContext,Object| context) {
    // TODO: implement build
    throw UnimplementedError();
  }
}
```

**To Reproduce**
{populate}

**Expected behavior**
```
class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    throw UnimplementedError();
  }
}
```

**Version**
Include here the result of: <kbd>M-x</kbd> `lsp-dart-version`
```
[LSP Dart] 1.22.2 at 2022.07.12 @ Emacs 28.1
[Dart SDK] Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "linux_x64"

[Flutter SDK] /home/ale/src/3rdparty/flutter
[Flutter project] true
[Project entrypoint] /home/ale/src/foobar/main.dart
```

**Comment by ericdallo** [comment]
@laynor I think your emacs is missing yasnippets package, the returned code action is a snippet and those numbers are the place where the cursor should jump, for some reason is not working properly well for you, so I suggest you double check if yasnippets is installed.
https://emacs-lsp.github.io/lsp-mode/page/faq/#the-completion-does-not-work-fine-and-inserts-arguments-and-placeholders-what-i-am-doing-wrong

**Comment by laynor** [comment]
@ericdallo Yasnippet is installed,  and I use it daily. In fact, I have not changed my emacs config in quite a while and overriding `build` used to work flawlessly. It may have stopped working after some flutter upgrade, but I cannot be sure.
I'm using doom emacs, with a pretty standard configuration.

**Comment by ericdallo** [comment]
Yeah, looks correct, maybe @yyoncho could help here?

**Comment by yyoncho** [comment]
@laynor what is happening?

**Comment by laynor** [comment]
@yyoncho I'm getting weird output from LSP dart when I chose for example the `create missing overrides` action. I guess the action uses yasnippet, but I wonder if the issue is yasnippet related. 
for example, I get this output
```
  @override
  Matrix4 fromJson(1|List<double>,Object,EfficientLengthIterable<double>,Iterable<double>| json) {
    // TODO: implement fromJson
    throw UnimplementedError();
  }

  @override
  List<double> toJson(3|Matrix4,Object| object) {
    // TODO: implement toJson
    throw UnimplementedError();
  }
```
I would expect this instead 
```
  @override
  Matrix4 fromJson(List<double> json) {
    // TODO: implement fromJson
    throw UnimplementedError();
  }

  @override
  List<double> toJson(Matrix4 object) {
    // TODO: implement toJson
    throw UnimplementedError();
  }
```

**Comment by yyoncho** [comment]
@ericdallo do we have custom handling for this code action? If yes, we should use yas to expand the text edits send by the server. If no, then we should check if we are missing a piece from the protocol implementation.

**Comment by ericdallo** [comment]
Yeah, we don't have any code actions customizations on lsp-dart, so maybe something kissing from spec

**Comment by laynor** [comment]
Still having the same problem BTW :cry:

**Comment by ericdallo** [comment]
I managed to repro that, it seems to happen when dart SDK returns a choice for for example the `Extract function` code action, we need to check the response and check if matches the LSP spec and if yasnippets support it

**Comment by ericdallo** [comment]
@laynor feel free to open a new issue about it
