### ISSUE TITLE
flutter analyze makes emacs slow

### ISSUE THREAD

**Issue by latpaw** [emacs-lsp/lsp-dart#175]
problem：
1. use lsp-dart with flutter project
2. jump to definition which may be some flutter file

lsp-dart will analyze all the flutter source code and makes many errors / warnings
lsp-treemacs-errors-list list more than 800, 000 errors

this will make emacs slow Significantly, even just try to save a file which is not .dart

should lsp-dart just support ignore analyze flutter source code
 or 
change something to reduce the affect of errors

**Comment by ericdallo** [comment]
@latpaw when you go to flutter source, try not importing the flutter source, since you probably already imported try `lsp-workspace-folders-remove` to remove flutter source code project

**Comment by latpaw** [comment]
> 

yeah, it works. Thanks @ericdallo 
I should learn more about lsp docs

**Comment by ericdallo** [comment]
@latpaw maybe we could mention it somewhere on lsp-dart docs, I think this is pretty common
