### ISSUE TITLE
[dap-dart] Allow to pass parameters like `--flavor` but also others

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#18]
**Describe the Feature request**
I haven't found a way to pass the `--flavor` parameter to `flutter run` using `dap-debug`

There are likely others like `--route` `--no-pub` 
See `flutter run --help` for all possibilities
There was also an interesting option added/reverted recently to pass constant values to Dart by `--dart-define` https://github.com/flutter/flutter/pull/52041
Hopefully that will finally land eventually.

**Comment by ericdallo** [comment]
Nice, I forgot about the `flavor`, I'll think of something to easily achieve this :)

**Comment by ericdallo** [comment]
I think all of this can be achieved now with the custom template as explained [here](https://github.com/emacs-lsp/lsp-dart/issues/19#issuecomment-625846522).
