### ISSUE TITLE
dap-debug keeps launching forever

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#19]
I try to debug a flutter app, but it only shows `launching` with a "spinner" in the minibuffer.
The dap session window shows a session.

```elisp
(dap-register-debug-template
  "Flutter L@MB Origin"
  (list :type "flutter"
        :request "launch"
        :flutterMode "debug"
        :flutterPlatform "default"
        :program "lib/main_zoechi.dart"
        :args "--flavor origin"
))
```

I got the impression `:args` is just ignored.
If I run from command line without `--flavor origin` I get the output

```
Launching lib/main_zoechi.dart on Pixel 3a in debug mode...
Running Gradle task 'assembleDebug'...                             39.5s
Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under
/home/user/source/Customers/LookAtYou/lookatmybaby/lookatmybaby_flutter/build, but the tool couldn't find it.
```
and then the the command exits without an error code.

This could just be a duplicate of #18 but I guess user experience could still be improved.

**Comment by ericdallo** [comment]
@zoechi, Thanks for the report!
I'll improve the UX for custom debug parameters, but I think for this case the `args` should be a `list`:
```elisp
:args '("--flavor" "origin")
```

**Comment by zoechi** [comment]
<strike>
Thanks, didn't think of that form.
Now I only get 

> Debug session process exited with status: killed

immediately after I execute `dap-debug`

Is there a way to get some log output. 
I think I saw some buffer with log output of the debugger startup process at some point but I do not know if I have anything to do for it to show up.

It doesn't look like `(setq lsp-dart-dap-flutter-verbose-log t)` leads to any more log output.
</strike>

I restarted Emacs and didn't have a Dart file open yet so LSP-Mode was not active.
Perhaps this could lead to some more informative error?

**Comment by ericdallo** [comment]
Sorry, I didn't understand, is the flavor problem fixed?

**Comment by zoechi** [comment]
Yup, sorry for the confusion.

Args/flavor are working now.

**Comment by ericdallo** [comment]
No problem :)
I released now a new tag making it less verbose to add a custom template and [added to the README](https://github.com/emacs-lsp/lsp-dart#custom-templates) how to add a custom template, thanks for the feedback!
