### ISSUE TITLE
errors after upgrading to dart version 3.0.0

### ISSUE THREAD

**Issue by wolf-coder** [emacs-lsp/lsp-dart#197]
**Describe the bug**
- After upgrading from  dart 2.19.6 to version 3.0.0, `lsp-dart-run` fails with these buffers indicating Warning and Errors:
--  * Messages * :
_error in process filter: dap--send-message: Session Dart Run<1> is already terminated
error in process filter: Session Dart Run<1> is already terminated_
-- *  Warnings * :
_Warning (emacs): Initialize request failed: "args" argument in launch configuration must be a List<String> but provided value was a Null (null)_

**Version**
[LSP Dart] 1.24.1 at 2023.05.14 @ Emacs 27.1
[Dart SDK] Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "linux_x64"

[Flutter SDK] /home/cuore-pc/snap/flutter/common/flutter
[Flutter project] false

**Comment by ericdallo** [comment]
Thanks for reporting it, it should be fixed on master and 1.24.2 release

**Comment by wolf-coder** [comment]
Yes It did fix it. Thank you for your work.
