### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by nickenchev** [emacs-lsp/lsp-dart#2]
Hey I'm trying to actually install lsp-dart, and can't do so neither with :ensure t or straight.el

I'm currently getting completions using dart-mode + lsp-mode, but I'm having terrible completion lag so I thought I'd try this. To be honest, I don't even know dart-mode uses lsp-dart, or how any of this ties together.

**Comment by ericdallo** [comment]
@nickenchev we are migrating `lsp-dart` from `lsp-mode` to this repo and adding more feature to this, but this is recent and `lsp-dart` is not yet on melpa, I think in a couple of weeks this will be available.

I recommend you to use `lsp-dart` from `lsp`mode` temporarily or if you are using straight, you can use this repo with something like:

```elisp
(package :recipe (:fetcher github :repo "emacs-lsp/lsp-dart" :branch "master"))
```

**Comment by ericdallo** [comment]
The Melpa [PR](https://github.com/melpa/melpa/pull/6823) was merged, so I think this is fixed @nickenchev

**Comment by nickenchev** [comment]
Thank you Eric! Hadn't had a change to try your suggested install method, but thanks for the info.
