### ISSUE TITLE
dap-dart should allow to invoke hot-reload and hot-restart

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#20]
**Describe the bug**
Among others provided by the Flutter runtime

The output of <kbd>?</kbd> after `flutter run`
Not all might make sense from Emacs.

> Flutter run key commands.
> r Hot reload. 🔥🔥🔥
> R Hot restart.
> h Repeat this help message.
> d Detach (terminate "flutter run" but leave application running).
> c Clear the screen
> q Quit (terminate the application on the device).
> s Save a screenshot to flutter.png.
> w Dump widget hierarchy to the console.                                                                                                                    (debugDumpApp)
> t Dump rendering tree to the console.                                                                                                               (debugDumpRenderTree)
> L Dump layer tree to the console.                                                                                                                    (debugDumpLayerTree)
> S Dump accessibility tree in traversal order.                                                                                                        (debugDumpSemantics)
> U Dump accessibility tree in inverse hit test order.                                                                                                 (debugDumpSemantics)
> i Toggle widget inspector.                                                                                                       (WidgetsApp.showWidgetInspectorOverride)
> p Toggle the display of construction lines.                                                                                                       (debugPaintSizeEnabled)
> o Simulate different operating systems.                                                                                                           (defaultTargetPlatform)
> z Toggle elevation checker.
> M Write SkSL shaders to a unique file in the project directory.
> v Launch DevTools.
> P Toggle performance overlay.                                                                                                         (WidgetsApp.showPerformanceOverlay)
> a Toggle timeline events for all widget build methods.                                                                                         (debugProfileWidgetBuilds)
> An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:46091/hgqcUJHAI5A=/
>

**Comment by ericdallo** [comment]
I think [flutter.el](https://github.com/amake/flutter.el) implemented this, but I think that won't work with the dap-debug because the debug use a flutter daemon on the background and `flutter.el` starts another flutter process :/

**Comment by zoechi** [comment]
I only used this in IntelliJ, but I'm sure VSCode does this as well.

IMHO it doesn't really make sense to distinguish between debug and run in Flutter.
I'd always debug and when it hits a breakpoint or an exception (and halt on exceptions is configured) it should break, otherwise it just runs.

**Comment by ericdallo** [comment]
You are right, I checked the Dart-Code VSCode extension and noticed that they send a custom request for the debug session for `hotReload` and `hotRestart` and I implemented 2 new commands for the debug session:
`lsp-dart-dap-flutter-hot-restart`
`lsp-dart-dap-flutter-hot-reload`

Hope it helps and thanks for the report :)

**Comment by zoechi** [comment]
Incredible! I love what you are doing!

**Comment by ericdallo** [comment]
Thank you @zoechi! :rocket:
