### ISSUE TITLE
lsp-dart-line-length not working on dart 2.19.6

### ISSUE THREAD

**Issue by lscantelbury** [emacs-lsp/lsp-dart#203]
**Describe the bug**
I'm trying to set lsp-dart-line-length but it keeps the default value (80).

**To Reproduce**
(require 'lsp-dart)
(setq lsp-dart-line-length 100)

**Expected behavior**
My dart files were formatted wrapping the lines at char 100

**Version**
1.24.2

**Comment by ericdallo** [comment]
Thanks for the report, I'll take a look soon

**Comment by ericdallo** [comment]
Sorry for the late, I tested with latest version of lsp-dart and worked as expected, keep in mind that you need to restart the LSP after changing that var.

I used this code as testing:

```dart
const a = ["a", "b", "caaaaaaaaaaaaaaaaaaaa", "dkkkkkkkkkkkkkkkkkkkk", "aaaaaaaaaaaaaaaaaaaaaaaa"];
```

And after calling lsp format, it kept as it is.

**Comment by ericdallo** [comment]
Closing this, LMK if it's still an issue
