### ISSUE TITLE
Cannot pass "--no-sound-null-safety" as parameter to lsp-dart-test-extra-args

### ISSUE THREAD

**Issue by lscantelbury** [emacs-lsp/lsp-dart#205]
**Describe the bug**
Trying to run tests at my project, but it always fails due to --no-sound-null-safety not being passed as parameter to test command.

**To Reproduce**
Add the line bellow to init.el:

(setq lsp-dart-test-extra-args '("--no-sound-null-safety"))

**Expected behavior**
Test should be executing without null safety verification.

**Screenshots**
![image](https://github.com/emacs-lsp/lsp-dart/assets/83627038/75718ec2-71e2-465d-90f5-f07cc1ac26b5)

**Version**
Include here the result of: <kbd>M-x</kbd> `lsp-dart-version`
[LSP Dart] 1.24.2 at 2023.10.06 @ Emacs 29.1
[Dart SDK] Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "linux_x64"

**Comment by ericdallo** [comment]
Closing as this should be available for both test and debug, LMK otherwise.

**Comment by lscantelbury** [comment]
> Hi @lscantelbury 
> 
> Are you clicking on Test or Debug code lens?
> 

Both were not working, so I tweaked the source code myself so it was always passed as parameter to the "test" command.
