### ISSUE TITLE
lsp-dart incorrectly checks minimum SDK version

### ISSUE THREAD

**Issue by carlosperezm** [emacs-lsp/lsp-dart#22]
**Describe the bug**
lsp-dart claims that my SDK version is below 2.8.0, when it is actually 2.8.1

**Expected behavior**
Identify that my version is greater than 2.8.0

**Version**
[LSP Dart] 1.8.7 at 2020.05.09 @ Emacs 26.3

**Comment by ericdallo** [comment]
Thanks for the report, I'll take a look
