### ISSUE TITLE
Can't run flutter app with lsp-dart-run

### ISSUE THREAD

**Issue by robinsrk** [emacs-lsp/lsp-dart#224]
**Describe the bug**
After calling lsp-dart-dap-setup, when i run lsp-dart-run, it puts some random text inside the current buffer, and doesn't run the project. 

**To Reproduce**
- Install the package
- run lsp-dart-dap-setup
- run lsp-dart-run

**Expected behavior**
It should run the project

**Screenshots**
![image](https://github.com/user-attachments/assets/1e3570bc-4436-43a4-a942-1d2e5849960d)

**Version**
Include here the result of: <kbd>M-x</kbd> `lsp-dart-version`
![image](https://github.com/user-attachments/assets/123a6525-6ca7-434a-b982-be1d369787da)

**Comment by gwn06** [comment]
Is  (setq lsp-use-plists t) enabled? There's a guide here on how to fix the problem https://emacs-lsp.github.io/lsp-mode/page/performance/

**Comment by robinsrk** [comment]
> Is (setq lsp-use-plists t) enabled? There's a guide here on how to fix the problem https://emacs-lsp.github.io/lsp-mode/page/performance/

I have set this, still the same issue

**Comment by samuelematias** [comment]
Same issue here, any resolution?
Thanks.

**Comment by ericdallo** [comment]
Can anyone provide a sample flutter project where that happens so I can try? I can't repro yet

**Comment by ericdallo** [comment]
I think I foudn the issue, can you try again with latest?

**Comment by samuelematias** [comment]
> I think I foudn the issue, can you try again with latest?

Fixed! 
Thanks for the Support, @ericdallo 🙏🏾!

![CleanShot 2024-11-15 at 14 45 10@2x](https://github.com/user-attachments/assets/bad912cc-b979-4efc-805c-00324577d046)
