### ISSUE TITLE
How to debug `flutter test`?

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#25]
It is not clear to me how a DAP template would look like to be able to debug `flutter test` execution.

**Comment by zoechi** [comment]
There are also `flutter drive` tests where a part runs outside a device or emulator that drives code run inside a device or emulator.
I don't know how far other IDE's support that though

**Comment by ericdallo** [comment]
Yeah, there're 2 features here, one is run the tests inside a device and other is run the tests with DAP for debugging.

I'm working on the last one, is almost finished and is already working for dart, just missing flutter debug:
![image](https://user-images.githubusercontent.com/7820865/81816056-2c5cb300-9501-11ea-812a-29ef792e312e.png)

**Comment by zoechi** [comment]
Great to hear \o/

**Comment by ericdallo** [comment]
Fixed on release [1.10.0](https://github.com/emacs-lsp/lsp-dart/releases/tag/1.10.0), thanks for the report :)
