### ISSUE TITLE
Abillity to view analyzer errors for whole project

### ISSUE THREAD

**Issue by l7ssha** [emacs-lsp/lsp-dart#29]
Hi, I was recently doing refactoring of my whole project according to new rules that I added to analyzer and currently it isn't possible to view all issue that analyzer is returning for project. It would be very convenient to have separate buffer or treemacs tab that could display all issue with current file and issue for whole project - it would speed up navigation to places where attention is needed.

**Comment by ericdallo** [comment]
@yyoncho may can confirm this, but I think `lsp-treemacs-errors-list` resolve you problem?

**Comment by yyoncho** [comment]
yes.

**Comment by ericdallo** [comment]
![image](https://user-images.githubusercontent.com/7820865/82221038-d4092500-98f5-11ea-9c04-aa4cd24516f8.png)
