### ISSUE TITLE
Invalid version syntax

### ISSUE THREAD

**Issue by arashbi** [emacs-lsp/lsp-dart#32]
First of all, amazing job! I am really impressed by the features of this plugin. I am new to emacs, and lsp, so ...
**Describe the bug**
When I try `lsp-dart-show-outline`
I get 
`Invalid version syntax: ‘2.9.05.0..4540`

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page.

**To Reproduce**
Not sure really, I basically just installed it, and opened a sample project. It is a flutter project, I am on dev channel

**Version**
Include here the result of: `M-x` `lsp-dart-version`
`[LSP Dart] 1.11.4 (package: 20200523.2302) at 2020.05.25 @ Emacs 26.311

**Logs**
Please include the debug stack trace (if there is an error) and the content of Messages buffer with `lsp-print-io` set to t in case the bug is related to client->server communication.

**Comment by ericdallo** [comment]
Thanks for the kind words and the report!
I'll take a look :)

**Comment by ericdallo** [comment]
I just released a fix for the version check, could you please check if it works now @arashbi?

**Comment by arashbi** [comment]
Great! it is fixed!
