### ISSUE TITLE
dap-debug in flutter project not detecting real device  

### ISSUE THREAD

**Issue by cassc** [emacs-lsp/lsp-dart#33]
**Describe the bug**

I tried `dap-debug`  - `Flutter -Debug`, it only listed emulators but not my connected phone. 

I could see my connected phone with `flutter doctor` or Visual Studio.

**Version**
`[LSP Dart] 1.11.5 (package: 20200526.1328) at 2020.05.27 @ Emacs 26.3`

**Comment by ericdallo** [comment]
I think real devices are not supported currently in debug in `lsp-dart` :pensive: 
I'll take a look at how hard it is to make it work, thanks for the report!

**Comment by ericdallo** [comment]
@cassc I just released a new tag `1.11.6` that checks for real devices when debugging/emulating, could you please test it?

**Comment by cassc** [comment]
@ericdallo It's working, Thanks!
