### ISSUE TITLE
dap-debug for  flutter is not running.

### ISSUE THREAD

**Issue by gnumonk** [emacs-lsp/lsp-dart#37]
**Describe the bug**
While using dap-debug , following error is coming

Symbol’s function definition is void: lsp-make-flutter-daemon-command

**To Reproduce**
Install spacemacs, below are the configuration 
 (dart :variables
           dart-backend 'lsp
           lsp-enable-on-type-formatting t
           )
lsp mode is working and there is no issue with lsp, when I use flutter-run, default device simulator starts and work but dap-debug is not working. 
**Expected behavior**
It should open device list and ask which device to run.

**Version**
[LSP Dart] 1.12.4 (package: 20200621.2131) at 2020.06.26 @ Emacs 26.2
[Dart SDK] Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"

**Comment by ericdallo** [comment]
@gnumonk are you using the latest `lsp-mode` version?
If yes, make sure to remove all `.elc` files compiled and recompile again.

**Comment by gnumonk** [comment]
Thanks, With the latest version above issue is resolved.
