### ISSUE TITLE
Yasnipet is broken in dart mode

### ISSUE THREAD

**Issue by itome** [emacs-lsp/lsp-dart#38]
yasnippet with lsp-mode works fine with dart-mode just after lsp-mode started, but sometimes (I don't know the reason) error occurs in completion/resolve and after that, snippet directly shown in buffer like below.

<img width="331" alt="Screen Shot 2020-01-20 at 18 46 37" src="https://user-images.githubusercontent.com/24409457/72716252-402c8400-3bb5-11ea-9962-9cc08cc6904b.png">

First error message is

```
Error in post-command-hook (yas--post-command-handler): (wrong-type-argument markerp 2268)
```

And after the error, ↓ this error occur every time snippet expand.

```
company-call-backend-raw: Company: backend company-lsp error "[yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’" with args (post-completion child: )
company-call-backend-raw: Company: backend company-lsp error "[yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’" with args (post-completion borderRadius: )
company-call-backend-raw: Company: backend company-lsp error "[yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’" with args (post-completion floatingActionButton: )
```

**Comment by ericdallo** [comment]
@itome many things have changed after this issue was re-opened both in `lsp-mode` and `lsp-dart`, could you test if it's happening again with the latest version of everything?

**Comment by itome** [comment]
I don't know what was the cause of bug but it seems solved. Thanks!
