### ISSUE TITLE
dap-debug is not working with latest.

### ISSUE THREAD

**Issue by gnumonk** [emacs-lsp/lsp-dart#40]
**Describe the bug**
dap-debug shows the "Flutter Debug" and along with devices which are available via flutter devices, but while selecting dep-debug through errors 

string-match-p: Wrong type argument: stringp, (raise -0.24) [2 times]

**To Reproduce**
enable dap-debug and select "Flutter :: Debug"

**Expected behavior**
Should start process with the selected devices.

**Version**
[LSP Dart] 1.12.6 (package: 20200630.2233) at 2020.07.04 @ Emacs 26.2
[Dart SDK] Dart VM version: 2.9.0-18.0.dev.flutter-2ec47ad273 (be) (Thu Jun 25 00:20:31 2020 +0000) on "macos_x64"

**Comment by ericdallo** [comment]
@gnumonk could you provide the stack error with <kbd>M-x</kbd> `toggle-debug-on-error`?

**Comment by gnumonk** [comment]
Please find enclosed.
[bt.txt](https://github.com/emacs-lsp/lsp-dart/files/4879273/bt.txt)

**Comment by ericdallo** [comment]
@gnumonk it seems to be a problem with `helm` after choosing the device.
@yyoncho, in the stacktrace, have you seen this problem with `dap-completing-read` and `helm`?

**Comment by yyoncho** [comment]
This is the call that fails on helm:

``` emacs-lisp
(helm-completing-read-default-2 "Select a device to use: " 
                                '(#(" emulator - iOS Simulator" 0 1 (face (:family "FontAwesome" :height 1.2 :inherit all-the-icons-lsilver) font-lock-face (:family "FontAwesome" :height 1.2 :inherit all-the-icons-lsilver) display (raise -0.24) rear-nonsticky t)) 
                                  #(" emulator - Nexus 6 API 28" 0 1 (face (:family "FontAwesome" :height 1.2 :inherit all-the-icons-green) font-lock-face (:family "FontAwesome" :height 1.2 :inherit all-the-icons-green) display (raise -0.24) rear-nonsticky t)) 
                                  "web - device - Chrome" "web - device - Web Server") 
                                nil t nil nil nil nil "nil" "*helm-mode-nil*")

```

I am not 100% this is valid call because the vanilla completing read does not work at all (or at least I was unable to make it work) because you cannot (or you cannot easily) type the completion.

What I suggest to test with the completion with ivy-mode off. If you can make it work, then it is helm bug otherwise it is lsp-dart bug. I suggest also to try it make it work with `completion-extra-properties` check `proced-send-signal` for example so the icons are added as decoration but they are not part of the item itself.

**Comment by yyoncho** [comment]
Ok, it works with vanilla by using C-n/C-p, then you should report in in helm repo.

**Comment by ericdallo** [comment]
I tested it local with helm and seems to work too. I'm not sure what to say on the helm issue as it works on my emacs and vanilla, maybe you should open the issue @gnumonk ?

**Comment by yyoncho** [comment]
reported this: https://github.com/emacs-helm/helm/issues/2335

**Comment by ericdallo** [comment]
Thank you very much @yyoncho!

**Comment by ericdallo** [comment]
@gnumonk it seems to [be fixed](https://github.com/emacs-helm/helm/issues/2335#issuecomment-654466053), can you test it again with latest helm version?

**Comment by gnumonk** [comment]
Thanks, Let me check and get back.

**Comment by gnumonk** [comment]
It's working with the latest helm. Closing this bug now.
