### ISSUE TITLE
dap-dart-setup not working?

### ISSUE THREAD

**Issue by shivahnshankar** [emacs-lsp/lsp-dart#43]
**Describe the bug**
When i run dap-dart-setup, nothing happens. And i am not able to run devtools. However, i am able to start flutter debug and run the app using flutter-run.

**Version**
[LSP Dart] 1.12.4 at 2020.07.13 @ Emacs 27.0.91
[Dart SDK] Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "macos_x64"

node and npm are available in exec-path. I am running this in the latest develop version of doom if that matters.

**Comment by ericdallo** [comment]
Thanks for the report @shivahnshankar, could test on latest release and removing ` ~/.emacs.d/.local/etc/dap-extension/github/Dart-Code.Dart-Code/` then running `dap-dart-setup` again ?

**Comment by shivahnshankar** [comment]
Interesting, there is no dap-extension folder under DOOMDIR/.local/etc. Could this be related to this?
[https://github.com/hlissner/doom-emacs/issues/3103](https://github.com/hlissner/doom-emacs/issues/3103). Checking...

**Comment by ericdallo** [comment]
Probably, `dap-dart-setup` did not run successfully or something like that

**Comment by ericdallo** [comment]
Any news on that @shivahnshankar?

**Comment by shivahnshankar** [comment]
Was away for a while sorry. Will check and revert.

**Comment by ericdallo** [comment]
Any news @shivahnshankar
