### ISSUE TITLE
Laggy while inputting if the flutter SDK is not specified

### ISSUE THREAD

**Issue by liurnd** [emacs-lsp/lsp-dart#44]
**Describe the bug**
If the flutter SDK path is not specified, the normal input will be really laggy.

**To Reproduce**
+ Do not set lsp-dart-flutter-sdk-dir
+ Type normally in dart buffer.
Observed that the typing is laggy.

**Expected behavior**
Normal typing should be smooth

**Version**
[LSP Dart] 1.13.0 at 2020.07.15 @ Emacs 28.0.50

**PS**
Here's the screenshot of the CPU profiling
![Screen Shot 2020-07-15 at 11 43 44](https://user-images.githubusercontent.com/509914/87500945-72183200-c690-11ea-8c05-ebfbfae6a486.png)

Note that the lsp-dart--flutter-project-p is taking a lot of cycles.
The theory is that:
1. If the flutter SDK is not specified, the lsp-dart-flutter-daemon--running-p will always be nil.
2. For each call to lsp-dart--handle-analyzer-status, the lsp-dart--flutter-project-p will be called.
3. lsp-dart--flutter-project-p will (indirectly) call locate-dominating-file which is expensive

Changing the lsp-dart--flutter-project-p to
`(defun lsp-dart--flutter-project-p () nil)` fixed the issue

**Comment by ericdallo** [comment]
Thank you for the report!
I see the problem, we should cache the analyzer status per buffer, I'll fix that

**Comment by ericdallo** [comment]
@liurnd Fixed on [1.13.1](https://github.com/emacs-lsp/lsp-dart/releases/tag/1.13.1) release, if you could confirm it would be great, thank you!
