### ISSUE TITLE
How to access Flutter console?

### ISSUE THREAD

**Issue by shivahnshankar** [emacs-lsp/lsp-dart#45]
Hi
In my flutter program, i have print statements that i use for debugging. Where does this output go?
Would appreciate if you could send me a pointer to existing documentation if any.
Thanks

**Comment by shivahnshankar** [comment]
There is the "DEBUG CONSOLE" in VS Code where the print output messages appear.

**Comment by ericdallo** [comment]
I think you seek for `dap-ui-show-many-windows`, but normally you don't need to manually open that, if `dap-mode-auto-configure` is enabled, it will open the default debug windows

@shivahnshankar `lsp-dart` uses [dap-mode](https://emacs-lsp.github.io/dap-mode/) for debugging features, you can find the documentation there and if it's missing something feel free to open an issue/PR and we will certainly fix it.

**Comment by ericdallo** [comment]
@shivahnshankar I think `dap-go-to-output-buffer` should do the trick

**Comment by shivahnshankar** [comment]
Yes that did give the print statements output. Belated Thanks!
