### ISSUE TITLE
Reference to obsolete `lsp--buffer-for-file` function

### ISSUE THREAD

**Issue by akirak** [emacs-lsp/lsp-dart#46]
**Describe the bug**
Several files contain references to `lsp--buffer-for-file` function, which was removed in this commit: https://github.com/emacs-lsp/lsp-mode/pull/1824/files

**To Reproduce**
Run `batch-byte-compile` on the source files against the latest version of `lsp` package:

```sh
  emacs --batch --no-site-file --eval "(setq byte-compile-error-on-warn t)" \
    --eval "(add-to-list 'load-path \"$(pwd)\")" \
    --funcall batch-byte-compile *.el
```

The following error message is produced on several files:

> lsp-dart-flutter-widget-guide.el:164:1:Error: the function `lsp--buffer-for-file' is not known to be defined.

**Expected behavior**
No byte-compilation error should occur.

**Version**
1.11.8 (latest Git)
(and `lsp-mode` from the latest emacs-overlay)

**Comment by ericdallo** [comment]
@akirak this was already fixed on master a few releases ago, could you check your lsp-dart version? The latest is 1.13.3

**Comment by akirak** [comment]
I see. Thanks.
