### ISSUE TITLE
Lots of errors make Emacs unresponsive

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#47]
**Describe the bug**
When I open certain Dart files, I guess it's mostly when I open files from the SDK, but also sometimes when I open files from other projects, CPU usage goes up and Emacs becomes unresponsive
and the LSP errors count in the modeline keeps growing (up to 230000/4200 the last time)

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages.

**To Reproduce**
{populate}

**Expected behavior**
Should not cause Emacs to become unresponsive

**Screenshots**

**Version**
```
[LSP Dart] 1.13.4 (package: 20200510.2055) at 2020.08.05 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.9.0-21.10.beta (beta) (Unknown timestamp) on "linux_x64"
```

**Comment by yyoncho** [comment]
Please provide a performance report.

**Comment by ericdallo** [comment]
I think the errors were related to this? https://github.com/emacs-lsp/lsp-dart/issues/48
Can you provide a performance report following this: https://github.com/emacs-lsp/lsp-dart/issues/48?

**Comment by zoechi** [comment]
I updated all packages again today and the issue seems to be solved.
I still wonder why I get do much errors when I open a file from the Flutter SDK, but it doesn't seem to affect performance.
