### ISSUE TITLE
Lots of `Invalid face reference: lsp-lens-face [8 times]`

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#48]
@yyoncho suggested to execute `(require 'lsp-lens) 
which seems to have fixed it.

He meant that this should be fixed in lsp-dart.

**Comment by ericdallo** [comment]
Sorry, We are segregating lsp-mode features into multiple files and I forgot to update lsp-dart to require that new file, thank you for the report!
Fixed on `lsp-dart` `1.13.5`

**Comment by TiborCornelli** [comment]
I'm having the same issue. How/where exactly am I supposed to execute `(require 'lsp-dart) ?

**Comment by ericdallo** [comment]
@TiborCornelli please update your lsp-dart and lsp-mode package and this should not happen anymore.
You can require lsp-dart after lsp-mode, are you using use-package ?
