### ISSUE TITLE
[LSP Dart] Dart command not found in path

### ISSUE THREAD

**Issue by giodevcoding** [emacs-lsp/lsp-dart#50]
I have been trying to get lsp-dart working in Emacs, but I keep running into this error:

`Command "[LSP Dart] Dart command not found in path ’c:/flutter/bin/cache/dart-sdk/bin/dart’ c:/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.14.3 (package: 20200811.1515)" is not present on the path.`

`Command "[LSP Dart] Dart command not found in path ’c:/flutter/bin/cache/dart-sdk/bin/dart’ c:/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.14.3 (package: 20200811.1515)" is not present on the path.
`

I have done the setup according to the Quick Start information. I have the proper paths set up and I can copy and paste the path from the error into my file explorer and find where `analysis_server.dart.snapshot` is. I cannot seem to find a fix for this bug, and I would really like do flutter development in Emacs. Any help is most appreciated.

Here's a screenshot of the dart command found in the specified path: 
![image](https://user-images.githubusercontent.com/33172553/90000073-870ec380-dc44-11ea-866b-e263f68dff56.png)

**Comment by ericdallo** [comment]
Hey @giodevcoding, thank you for the report, I think the problem is because `lsp-dart` expect that you dart/flutter/pub executbles do not have the `.exe`, we can fix that, but could you help providing the output of <kbd>M-x</kbd> `(list (executable-find "dart") (executable-find "pub") (executable-find "flutter"))` ?

**Comment by ericdallo** [comment]
@giodevcoding I also released a new version that may fix your issue, `1.14.4`, could you test it later too?

**Comment by giodevcoding** [comment]
Thanks Eric! I decided to just try to see if the update fixed the issue, and it did! Everything seems to be working smoothly now! Thanks so much for your quick response!

**Comment by ericdallo** [comment]
Great :)
You're welcome!
