### ISSUE TITLE
Sometimes dap-debug not work

### ISSUE THREAD

**Issue by rafamedina** [emacs-lsp/lsp-dart#52]
**Describe the bug**
It's random, but sometimes `dap-debug` shows an error:

`dap-dart-setup` no problems
```
[LSP Dart] [DAP] Setting up debugger...
[LSP Dart] [DAP] Setup done!

```

```
Debug on Error enabled globally
helm-M-x-execute-command: Opening input file: No such file or directory, /Users/rafael.medina/dev/source/fluttertesting/hello_flutter/launch.json

```

Maybe am I missing a setting?

**Comment by ericdallo** [comment]
This is a bug in `dap-mode` with the latest release of the launch.json feature, do you mind opening a PR there and linking to this?

**Comment by ericdallo** [comment]
Fixed on dap-mode, thanks for the report!
