### ISSUE TITLE
Can't start analysis server since Dart 2.9.1, but it's present on the path

### ISSUE THREAD

**Issue by Comevius** [emacs-lsp/lsp-dart#54]
For some reason lsp-dart can't start analysis_server.dart.snapshot despite confirming that it is present on the path.

`Command "/home/comevius/flutter/bin/cache/dart-sdk/bin/dart /home/comevius/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.14.6" is present on the path.`

`Error: Error when reading '../../flutter/bin/snapshots/analysis_server.dart.snapshot': No such file or directory`

```
$ lsp-dart-dart-command
/home/comevius/flutter/bin/cache/dart-sdk/bin/dart
$ lsp-dart-flutter-command
/home/comevius/flutter/bin/flutter
$ lsp-dart--server-command
("/home/comevius/flutter/bin/cache/dart-sdk/bin/dart" "/home/comevius/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot" "--lsp" "--client-id emacs.lsp-dart" "--client-version 1.14.6")
```

```
$ lsp-dart-version
[LSP Dart] 1.14.6 at 2020.08.14 @ Emacs 27.1
[Dart SDK] Dart SDK version: 2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "linux_x64"
```

When I downgrade to Dart 2.8.4 everything works as expected.

```
$ lsp-dart-version
[LSP Dart] 1.14.6 at 2020.08.14 @ Emacs 27.1
[Dart SDK] Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "linux_x64"
```

When I upgrade to Dart 2.9.1 again, I get back the same error.

`Error: Error when reading '../../flutter/bin/snapshots/analysis_server.dart.snapshot': No such file or directory`

**Comment by ericdallo** [comment]
Thanks for the report, I'll take a look if the dart SDK changed something related to that

**Comment by ericdallo** [comment]
Odd, I tested it with the latest flutter stable and everything seems to work fine with `lsp-dart`:
```

**Comment by ericdallo** [comment]
Maybe this could be some lsp-mode bug?
Could you test the latest lsp-mode bug and byte-compile the package again?

**Comment by Comevius** [comment]
@ericdallo

Can't reproduce this on a virtual machine, not even after I copy over my entire home directory, however I can't avoid it on my own machine even with a new home directory and empty Emacs configuration.

If the project only have a single `lib/main.dart` and I delete `.lsp-session-v1` I can get the server started, however lsp-mode only works until I close the buffer, then I get these kinds of errors:

```
Error running timer: (error "The connected server(s) does not support method textDocument/documentHighlight.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section")
```
```
lsp--send-request-async: The connected server(s) does not support method textDocument/onTypeFormatting.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

VS Code works properly.

I have no idea what's going on, maybe it's the kernel or some packages, because everything else should be the same between my machine and the virtual machine.

Tried it with the melpa-stable and melpa for lsp-mode and lsp-dart. Only downgrading Dart to 2.8.4 works.

**Comment by Comevius** [comment]
@ericdallo 

Finally managed to reproduce this on a virtual machine running Arch Linux.

It is caused by rebinding lsp-command-map when lsp-keymap-prefix is also set.

```
(use-package lsp-mode
  :ensure t
  :init
  (setq lsp-keymap-prefix "C-c l")
  :bind (:map lsp-mode-map
              ("s-l"   . nil)
              ("C-c l" . lsp-command-map)))
```

```
$ git clone https://github.com/flutter/flutter.git
$ export PATH="$PATH:$HOME/flutter/bin"
$ flutter create example
$ emacs
M-x find-file (example/lib/main.dart)
M-x kill-buffer
M-x find-file (example/lib/main.dart)
```

If you don't select the directory where pubspec.yaml is in as a root directory or there are more than one Dart files in the project lsp-mode stops working after the first find-file, otherwise it stops working after the second one.

Strangely only Dart 2.9.1 and newer is affected.

**Comment by ericdallo** [comment]
This is very strange indeed, I don't see how a keymap could affect that.
@yyoncho do you have any ideas why this happens?

**Comment by Comevius** [comment]
Some additional error messages from the Messages buffer:

```
Error processing message (error "Key sequence C-c l D t t starts with non-prefix key C-c l").
```

```
File mode specification error: (error Key sequence C-c l D t t starts with non-prefix key C-c l)
```

**Comment by yyoncho** [comment]
I got some trouble trying to create minimal example with lsp-keymap-prefix. I think that having the setq on top level instead of being in setq works.

**Comment by ericdallo** [comment]
@Comevius did you try @yyoncho's suggestion :point_up: ?

**Comment by Comevius** [comment]
Closed this, because the workarounds fixed the issue.

The issue can still be reproduced with use-package configuration above, so someone might want to look into what's going on.
