### ISSUE TITLE
Upcoming Dart-Code Debug Adapter changes

### ISSUE THREAD

**Issue by DanTup** [emacs-lsp/lsp-dart#55]
I noticed you're using the DAP debug adapter from Dart-Code:

https://github.com/emacs-lsp/lsp-dart/blob/437c548d411c9e166b7c658fd45294775235fd5f/lsp-dart-dap.el#L44

As a heads up, there are some changes landed in the repo that will be included in the latest release. We're starting to run the DAPs out-of-process again from VS Code, and as part of that we now have a single DAP entry point that is packed with webpack (same as the extension). Whereas before you would run:

```
node /foo/out/src/debug/dart_debug_entry.js
```

You would now run:

```
node extension/out/dist/debug.js dart
```

The argument passed here should be one of the debuggers listed here:

https://github.com/Dart-Code/Dart-Code/blob/master/src/debug/debug_entry.ts#L12-L18

If you have any issues making this work, do let me know!

**Comment by ericdallo** [comment]
Thank you very much for bringing this to me @DanTup!
Every time I bump the debugger version, I need to deep in the DartCode extension code to see what has changed, this will help a lot :)

**Comment by ericdallo** [comment]
Thanks for the heads up @DanTup
