### ISSUE TITLE
Invalid file path (Unknown error) and dart-sdk search path

### ISSUE THREAD

**Issue by repelliuss** [emacs-lsp/lsp-dart#59]
**Describe the bug**
`lsp-dart` doesn't pick the dart-sdk path from `$PATH` variable. It seems that *alternatively* it should. I have `.../flutter/bin` in my `$PATH` variable. Also in Doom Emacs, setting `flutter-sdk-path` neither `lsp-dart-flutter-sdk-dir` to `.../flutter` have an effect.

Setting `lsp-dart-sdk-dir` to `.../flutter/bin/cache/dart-sdk` seems to resolve this issue but returns `LSP :: Error from the Language Server: Invalid file path (Unknown error)` for every action on the file.

If I don't specify it, it searches the server at `.../flutter/bin/snapshots/analysis_server.dart.snapshot` which is not there.

`*Messages*`
```
LSP :: Guessed project root is ~/workspace/tmp/dart
LSP :: Connected to [dart_analysis_server:6916 status:starting].
LSP :: dart_analysis_server:6916 initialized successfully
LSP :: When using onlyAnalyzeProjectsWithOpenFiles, files opened that are not contained within project folders containing pubspec.yaml, .packages or BUILD files will not be analyzed.
LSP :: Error from the Language Server: Invalid file path (Unknown error) [4 times]
```
`*lsp-log*`
```
Command "/home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/dart /home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.15.1" is present on the path.
Command "/home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/dart /home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.15.1" is present on the path.
Found the following clients for /home/repelliuss/workspace/tmp/dart/hello.dart: (server-id dart_analysis_server, priority -1)
The following clients were selected based on priority: (server-id dart_analysis_server, priority -1)
```

`*lsp-log: dart_analysis_server:XXXX*`
[Pastebin](https://pastebin.com/5J83zbVj)

**To Reproduce**
1- Get stable branch for flutter
2- Add `.../flutter/bin` to `$PATH`
3- Run `flutter doctor`
4- Enable `+lsp +flutter` flags for Doom Emacs and do a `doom sync`
5- Enter a Dart a workspace

**Note:** I didn't install Android Studio but used `sdkmanager` to get the Android SDK. So flutter doctor warns me about Android Studio not being installed and no connected device available but I don't think these are related.

**Expected behavior**
- Understand the dart-sdk path from `.../flutter/bin` path since flutter comes bundled with dart-sdk so I don't need to specify another path for dart-sdk in my `$PATH` variable.
- Dont get the `... Invalid file path ...` error.

**Screenshots**
After setting `lsp-dart-sdk-dir` to `.../flutter/bin/cache/dart-sdk`
![](https://i.imgur.com/Yjxitnu.png)

**Version**
[LSP Dart] 1.15.1 at 2020.09.09 @ Emacs 27.1.50
[Dart SDK] Dart SDK version: 2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "linux_x64"

Doom v2.0.9 (HEAD -> develop c2e921177 2020-09-05 01:55:51 -0400)

**Comment by ericdallo** [comment]
@repelliuss unfortunately I was not able to reproduce your issue.

 I switched to flutter stable version and tested pointing `lsp-dart-flutter-sdk-dir` to my downloaded flutter `~/flutter` and everything worked as expected.

Also, `flutter-sdk-path` is not from `lsp-dart` it's from `flutter.el` and the correct path to the analyser server that `lsp-dart` automatically find it's `flutter/bind/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot` 
Basically when you set `lsp-dart-flutter-sdk-dir`, `lsp-dart` uses the `dart-sdk` from `<lsp-dart-flutter-sdk-dir>/bin/cache/dart-sdk` and everything should work.

From your `*lsp-log*` it seems that lsp-dart is finding correctly the flutter dir and the analyser, so I recommend you run `rm -rfv ~/.emacs.d/.local/straight/repos/lsp-{mode,dart} && rm -rfv ~/.emacs.d/.local/straight/build/lsp-{mode,dart}` and run `doom sync` again to make sure lsp-mode and lsp-dart are byte-compiled correctly

**Comment by repelliuss** [comment]
I took these logs/screenshot after I set `lsp-dart-sdk-dir` and it seems to be finding them correctly as you said but I was still getting that `Invalid file path` error.

I expect `lsp-dart-flutter-sdk-dir` to be working as you described but it doesn't have any effect. I run the commands and byte-compiled them again but issue still persists.

[Here I show you the value of `lsp-dart-flutter-sdk-dir` to my flutter sdk and where lsp-dart searches for dart-sdk and analysis-server](https://imgur.com/ZCaa0p1)

`*Messages*` buffer after I only set `lsp-dart-flutter-sdk-dir`
```
LSP :: Guessed project root is ~/workspace/tmp/dart
LSP :: Connected to [dart_analysis_server:3794 status:starting].
LSP :: dart_analysis_server has exited (exited abnormally with code 254)
Server dart_analysis_server:3794 status:starting exited with status exit. Do you want to restart it? (y or n) n
```

I tried removing `.../flutter/bin` from my `$PATH` variable then run `doom env` and after that got a different error message. There is no `*lsp-log*` this time though

`*Messages*` buffer after I set `lsp-dart-flutter-sdk-dir` but `.../flutter/bin` removed from `$PATH`
```
[LSP Dart] Dart command not found in path ’/home/repelliuss/workspace/tmp/dart/bin/dart’ [2 times]
LSP :: The following servers support current file but do not have automatic installation configuration: dart_analysis_server
You may find the installation instructions at https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).
```

**Comment by ericdallo** [comment]
are you sure `lsp-dart-flutter-sdk-dir` should be `~/workspace/bin/flutter`? shouldn't be `~/workspace`? remember that it should point to the flutter dir, not to the flutter executable

**Comment by repelliuss** [comment]
[Nope, the path is correct](https://i.imgur.com/Q9JLBF1.png)

I didn't get which specific file you were asking me to check though

**Comment by repelliuss** [comment]
So I was testing with this just one plain dart file but now created flutter project with `flutter create ...` and now it correctly finds dart-sdk and analysis_server via `lsp-dart-flutter-sdk-dir`. Very sorry about that, I'm just starting to Flutter.

But still there was one more thing,
`*dart_analysis_server::stderr*`
```
Error: Error when reading '../../bin/flutter/bin/snapshots/analysis_server.dart.snapshot': No such file or directory
``` 
I was having this error and I did a workaround with creating a symlink of `.../flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot` to `.../flutter/bin/snapshots/analysis_server.dart.snapshot` but I guess this shouldn't be the case, right? Navigating the created `lib/main.dart` was considerably slow this way

**Comment by ericdallo** [comment]
I see, no problem, it's weird that it is not finding the `analysis_server.dart.snapshot`... do you have the correct path for it? it is `<you-flutter-dir>/bin/snapshots/analysis_server.dart.snapshot`?

**Comment by ericdallo** [comment]
Flutter should have this file, make sure you downloaded the stable version from flutter webpage.
For flutter projects, just setting `lsp-dart-flutter-sdk-dir` is enough and for dart projects `lsp-dart-sdk-dir` is enough.

For performance check if everything it's okay with `lsp-doctor`

**Comment by repelliuss** [comment]
I tried downloading the fixed version as well as cloning the stable branch but both don't contain the `<my-flutter-dir>/bin/snapshots/analysis_server.dart.snapshot`. We are talking about here right?
![image](https://user-images.githubusercontent.com/53377661/92773101-f9d6a000-f3a4-11ea-8d7d-0ae9d5a7fb88.png)

There is one under `<my-flutter-dir>/bin/cache/dart-sdk/bin/snapshots/` but `<my-flutter-dir>/bin/` doesn't even have a `snapshots` folder

**Comment by ericdallo** [comment]
Sorry if I misunderstood, but the correct path is `<my-flutter-dir>/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot` not `<my-flutter-dir>/bin/snapshots/analysis_server.dart.snapshot`. if your emacs/flutter is not trying to search the former, then we need to debug that.

**Comment by repelliuss** [comment]
Well, interestingly my final issue solved on its own or re-downloading the Flutter SDK had an effect. LSP starts correctly as it should right now

Thanks @ericdallo for sparing your time
