### ISSUE TITLE
Too Low Performance

### ISSUE THREAD

**Issue by repelliuss** [emacs-lsp/lsp-dart#61]
**Describe the bug**
Performance is considerably slow on some(?) files.

 Note: I also use `lsp-pyright`, `ccls with lsp-mode` and there is no problem with these.

`*lsp-log*`, taken after video below
```
Command "/home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/dart /home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.15.1" is present on the path.
Command "/home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/dart /home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.15.1" is present on the path.
Found the following clients for /home/repelliuss/workspace/tmp/lspdart/lib/main.dart: (server-id dart_analysis_server, priority -1)
The following clients were selected based on priority: (server-id dart_analysis_server, priority -1)
Cancelling textDocument/documentHighlight(24) in hook after-change-functions
Cancelling textDocument/codeAction(23) in hook after-change-functions
Cancelling textDocument/documentHighlight(31) in hook after-change-functions
Cancelling textDocument/codeAction(30) in hook after-change-functions
Cancelling textDocument/hover(27) in hook after-change-functions
Cancelling textDocument/hover(38) in hook after-change-functions
Cancelling textDocument/documentHighlight(37) in hook after-change-functions
Cancelling textDocument/codeAction(36) in hook after-change-functions
Cancelling textDocument/codeAction(46) in hook post-command-hook
Command "/home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/dart /home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.15.1" is present on the path.
Command "/home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/dart /home/repelliuss/workspace/bin/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.15.1" is present on the path.
Found the following clients for /home/repelliuss/workspace/tmp/lspdart/test/widget_test.dart: (server-id dart_analysis_server, priority -1)
The following clients were selected based on priority: (server-id dart_analysis_server, priority -1)
Cancelling textDocument/documentHighlight(81) in hook after-change-functions
Cancelling textDocument/codeAction(80) in hook after-change-functions
Cancelling textDocument/documentHighlight(84) in hook after-change-functions
Cancelling textDocument/codeAction(83) in hook after-change-functions
Cancelling textDocument/documentHighlight(94) in hook after-change-functions
Cancelling textDocument/codeAction(93) in hook after-change-functions
Cancelling textDocument/hover(102) in hook after-change-functions
Cancelling textDocument/documentHighlight(126) in hook after-change-functions
Cancelling textDocument/codeAction(125) in hook after-change-functions
Cancelling textDocument/hover(182) in hook after-change-functions
```

**To Reproduce**
1- `flutter create myApp`
2- Open `myApp/lib/main.dart`
3- Select project root as `myApp/`
4- and edit things

[Also a video here. I run a profiler too.](https://youtu.be/wdPur13aP9Q)

**Expected behavior**
Flow like water

**Version**
[LSP Dart] 1.15.1 at 2020.09.14 @ Emacs 27.1.50
[Dart SDK] Dart SDK version: 2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "linux_x64"

Doom v2.0.9 (grafted, HEAD -> develop, origin/develop, origin/HEAD c2e9211 2020-09-05 01:55:51 -0400)

**Comment by yyoncho** [comment]
As you can see from the profiler the majority of the time goes into logging which should not be on when performing profiling. Set lsp-print-io to nil and provide a perf report.

**Comment by ericdallo** [comment]
Thanks for the report @repelliuss, @yyoncho is right, could you provide the profile content too via some file or pastebin?

**Comment by repelliuss** [comment]
Sorry, I forgot it on. Now I also set `lsp-print-performance` to `t`. I couldn't find a way to expand all of the profiler report though.
[CPU Profiler](https://pastebin.com/AMzmcfzy)
[Memory Profiler](https://pastebin.com/G3YThGfe)

**Comment by repelliuss** [comment]
I guess I found the cause of the issue.

Having this
```
(after! doom-modeline
  (setq doom-modeline-major-mode-icon t)
  )
```
in my `config.el` is what causes the issue. If you look closely to the modeline in the video, you can see that there is an `E in a square` which should be a proper Dart icon normally.

Are you able to reproduce the issue with this?

@ericdallo I know you are the maintainer of `lang/dart` module in Doom Emacs so would you want to fix this if its the same on you too?

**Comment by ericdallo** [comment]
Thanks for the hard try @repelliuss. 
I don't see anything relevant in the profiler.

I could not reproduce that on doom-emacs but AFAIK this happens when you don't have installed `all-the-icons` correctly in your system/emacs. As this is a issue specific with doom-modeline, I think there's nothing we can do on the doom/dart module as disabling `doom-modeline-major-mode-icon` may affect user UX for other modes.

I suggest you open a doom-modeline bug, also doom-emacs has the `+light` modeline flag that is way faster that doom-modeline, and the doom-emacs maintainer itself recommends it :)

**Comment by repelliuss** [comment]
I have `all-the-icons` installed. I thought without `lsp-mode`, there was no issue but now I tried it and issue persists so I understood that it wasn't related to `lsp-dart` at all.

I tried `+light` but it basically broke Doom and that's another issue to be solved 😁.  I'll open a doom-modeline bug sometime and refer this maybe.

Thanks again for helping my own little issues as well as maintaining dart module for Doom.

**Comment by ericdallo** [comment]
Thank you, you're welcome ;)

**Comment by shackra** [comment]
> I guess I found the cause of the issue.
> 
> Having this
> 
> ```
> (after! doom-modeline
>   (setq doom-modeline-major-mode-icon t)
>   )
> ```
> 
> in my `config.el` is what causes the issue. If you look closely to the modeline in the video, you can see that there is an `E in a square` which should be a proper Dart icon normally.
> 
> Are you able to reproduce the issue with this if you are a Doom Emacs user?
> 
> @ericdallo I know you are the maintainer of `lang/dart` module in Doom Emacs so would you want to fix this if its the same on you too?

I'm also experiencing slowness when editing a Dart file and I also see the E inside the square

**Comment by shackra** [comment]
My workaround for this issue was turning off buffer-locally the option in doom-modeline that shows the major mode icon:

```
(use-package dart-mode
  :hook ((dart-mode . flutter-test-mode)
         (dart-mode . shackra/dart-doom-modeline-no-major-mode-icon))
  :init
  (defun shackra/dart-doom-modeline-no-major-mode-icon ()
    "Cambia doom-modeline para que no muestre el icono del modo major en Dart.

Ver https://github.com/emacs-lsp/lsp-dart/issues/61#issuecomment-692392701"
    (setq-local doom-modeline-major-mode-icon nil)))
```
