### ISSUE TITLE
Can not open devtools

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#62]
**Describe the bug**
Start debugging a flutter app
`M-x` `lsp-dart-open-devtools` causes
```
Error running timer ‘lsp-dart-devtools--check-devtools-uri’: (json-parse-error "'[' or '{' expected near 'Precompiling'" "<string>" 1 12 12)
```

**Note**

**To Reproduce**
{populate}

**Expected behavior**
{populate}

**Screenshots**

**Version**
```
[LSP Dart] 1.17.0 (package: 20200510.2055) at 2020.09.15 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.10.0-7.3.beta (beta) (Wed Aug 26 09:46:50 2020 +0200) on "linux_x64"
```

**Comment by ericdallo** [comment]
Thanks for the report!
I'll take a look, are you using which version of the debugger?

**Comment by zoechi** [comment]
Right, I forgot to update the VSCode plugin. I'll check that tomorrow and post the results.

**Comment by ericdallo** [comment]
BTW, I know that the vscode plugin version 3.14 will fail with lsp-dart, so it's in my TODO fix that integration: https://github.com/emacs-lsp/lsp-dart/issues/55

**Comment by zoechi** [comment]
I updated. It installed 3.13.2 and this seems to have fixed it.
Thanks a lot!

**Comment by ericdallo** [comment]
@zoechi just bumped the debugger to latest vscode version :)
