### ISSUE TITLE
When will the latest versions be available in Doom Emacs?

### ISSUE THREAD

**Issue by shivahnshankar** [emacs-lsp/lsp-dart#69]
I have 1.15.1 from the latest version of Doom Emacs develop branch. Cant wait to try out the latest features that you have added 👍

**Comment by ericdallo** [comment]
You can try to ping doom-emacs maintainer on this issue :)
https://github.com/hlissner/doom-emacs/pull/3954

**Comment by ericdallo** [comment]
The PR was merged :tada:
