### ISSUE TITLE
Cannot start dart_analysis_server with error "Could not find an option named lsp"

### ISSUE THREAD

**Issue by AllenDang** [emacs-lsp/lsp-dart#71]
**Describe the bug**
I'm using newest version of Doom with gccemacs.
After open a flutter project, I noticed that in *lsp-log* buffer
`Command "/Users/allendang/SDK/flutter/bin/cache/dart-sdk/bin/dart /Users/allendang/SDK/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.17.6" is present on the path.`

But in *dart_analysis_server::strerr* buffer
```
Process dart_analysis_server stderr finished
Could not find an option named "lsp".
```

**Version**
[LSP Dart] 1.17.6 at 2020.10.06 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.10.0 (stable) (Mon Sep 28 09:21:23 2020 +0200) on "macos_x64"

**Comment by ericdallo** [comment]
Hey, thanks for the report, but I use doom-emacs with gccemacs too and could not reproduce that :thinking: 
Could you try to run this command from your flutter sdk directory:
```bash
./bin/dart bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id emacs.lsp-dart --client-version 1.17.6
```
If it stucks like the image below, it's because it connected successfully
![image](https://user-images.githubusercontent.com/7820865/95213998-cfbaa700-07c5-11eb-9775-8669f77d33b5.png)

**Comment by ericdallo** [comment]
Also, make sure your flutter SDK is correct/updated, I'd try to download again the flutter SDK

**Comment by AllenDang** [comment]
@ericdallo If I run the command in sdk directory, it does stuck. seems this is not the root cause.
I think my flutter is already up to date.
```
Flutter is already up to date on channel beta
Flutter 1.22.0 • channel beta • git@github.com:flutter/flutter.git
Framework • revision d408d302e2 (7 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

**Comment by ericdallo** [comment]
This is quite odd, it seems to be some corner casa or some emacs configuration, it's hard to know what to do without being able to reproduce it :/

**Comment by AllenDang** [comment]
@ericdallo Understand. Any related variables I could check?

**Comment by ericdallo** [comment]
Could you try to confirm if this happens in a sample project? like this: https://github.com/ericdallo/flutter-sample

**Comment by AllenDang** [comment]
@ericdallo It works fine with the sample project. I guess this should be caused by the project structure of my side. Thanks very much!

**Comment by ericdallo** [comment]
Good to know :)

**Comment by youngpm** [comment]
Hi @ericdallo ; I am experiencing this same issue.  

Everything works great with your cloned Flutter app, but I can't seem to get it to work with a test app created by `dart create -t console-full testlsp`, which doesn't use any Flutter.  I get the same error:

```
Process dart_analysis_server stderr finished
Could not find an option named "lsp".
```

**Comment by ericdallo** [comment]
Right, I'll take a look soon!

**Comment by youngpm** [comment]
@ericdallo I fixed this by installing the stand alone dart package; previously I was using the dart binary provided by a flutter install (they include it now in recent versions of flutter).  

I would guess the logic that tries to figure out which dart binary to invoke doesn't handle my original case; I perused the elisp a little but not really sure what I'm doing on that front!
