### ISSUE TITLE
Debugging Dart tests stopped working

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#77]
**Describe the bug**
Set a breakpoint in a Dart test file and start debugging
(code lense "Debug" or `lsp-dart-debug-test-at-point`)

`*Dart Tests<2> stderr*` shows
```
(node:13878) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:13878) UnhandledPromiseRejectionWarning: [object Object]
(node:13878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13878) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages.

Debugging a Dart or Flutter app still works fine.

**To Reproduce**
{populate}

**Expected behavior**
{populate}

**Screenshots**

**Version**
```
[LSP Dart] 1.17.7 (package: 20200510.2055) at 2020.10.19 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.11.0-213.1.beta (beta) (Unknown timestamp) on "linux_x64"
```

**Comment by ericdallo** [comment]
Thanks for the report, I'm kind of busy lately, but I'll try to take a look today

**Comment by ericdallo** [comment]
@zoechi I tested both beta and dev channels of flutter with [this sample](https://github.com/ericdallo/dart_sample) and it works :thinking: 
Did you run `dap-dart-setup`?

**Comment by zoechi** [comment]
I run dap-dart-setup. It doesn't change the behavior.
It somehow looks like debug mode is started (modeline, dap toolbar is shown) but no breakpoints are hit and
the error output from the original post is still there.

**Comment by zoechi** [comment]
After experimenting a bit and updating everything it's back to working.
Might have been caused by straight, but I'm not sure, but at some point it started complaining about a setting that I'm using since 6 months, and after I fixed that, I tried debugging the test again and it was working.
Thanks a lot for checking!
