### ISSUE TITLE
Autocomplete required function arguments

### ISSUE THREAD

**Issue by shivahnshankar** [emacs-lsp/lsp-dart#78]
Hi
In VS Code,  the LSP server fills in the required arguments to a function as part of autocomplete.

For ex:
if _firestore is a FirebaseFirestore instance, and i type in
`_firestore.coll `and press TAB, the autocompletion provided is
`_firestore.collection(collectionPath)`, with the collectionPath highlighted so that it can be replaced by the right path.

However, in lsp-dart in Doom Emacs, if i type
`_firestore.coll `and press <CR> , the autocomplete provided is
`_firestore.collection` without even the enclosing brackets.

Of course the hover menu does provide a hint that collectionPath has to be input but it is so much easier in VS Code. 
Is this behaviour possible? Is this a faeture of lsp-mode or lsp-dart?

[LSP Dart] 1.17.6 at 2020.10.19 @ Emacs 27.1
[Dart SDK] Dart SDK version: 2.10.0 (stable) (Mon Sep 28 09:21:23 2020 +0200) on "macos_x64"

**Comment by ericdallo** [comment]
@shivahnshankar I think this should be server's fault (`dart-sdk` with `LSP` flag true), could you try to reproduce it with `Vscode` but with `previewLSP` `true`?

**Comment by shivahnshankar** [comment]
Good catch! With previewLSP set to true, this does not happen. Found this on the Dart Code issues list:
[https://github.com/Dart-Code/Dart-Code/issues/2693](https://github.com/Dart-Code/Dart-Code/issues/2693). 
Thanks

**Comment by ericdallo** [comment]
Cool, thank you!

**Comment by ericdallo** [comment]
I'll keep an eye on that issue
