### ISSUE TITLE
Getting error after updating

### ISSUE THREAD

**Issue by ram535** [emacs-lsp/lsp-dart#8]
After updating and open a dart file (flutter project).
![1587513594401](https://user-images.githubusercontent.com/9011002/79926574-212ad180-83f2-11ea-987f-20d6be011be8.jpg)

I also noticed the same message appears even if it is not a dart or flutter project.
I open a `go` file and the same message appear `........lsp-dart-test)`.

In other words `lsp-mode` just stop working.
I remove `lsp-dart` from my configuration and everything works fine. 
For example I opened the same `go` file and the `go-lsp` worked fine.

**Comment by ericdallo** [comment]
Hi @ram535, probably a version different from master?
Are you using `doom-emacs`?

**Comment by ericdallo** [comment]
Fixed [here](https://github.com/emacs-lsp/lsp-dart/commit/b842ef74e6c71a07cb7e8e914d4efad39b111b88) on `1.6.5` release.
This should be available on MELPA in about 2 hours.

Thank you for the report @ram535

**Comment by ram535** [comment]
I confirm that It works now with the your new update.
I am using vanilla emacs with `use-package, straight.el and evil-mode`.

```
(use-package lsp-dart
  :straight (lsp-dart :type git :host github :repo "emacs-lsp/lsp-dart")
  :custom
  (lsp-dart-sdk-dir "~/bin/flutter/bin/cache/dart-sdk/")
  :hook (dart-mode . lsp-deferred))
```

Thanks.

**Comment by ericdallo** [comment]
Nice, thanks!
