### ISSUE TITLE
How use lsp-dart on doom emacs

### ISSUE THREAD

**Issue by MrMorteZw** [emacs-lsp/lsp-dart#81]
Hello sir how can i use lsp-dart on doom emacs i added (dart +lsp) on my doom config then type doom/sync and its sync successful but it doesn't work 
my flutter project:
![image](https://user-images.githubusercontent.com/43701982/100374048-f3110e00-3020-11eb-863f-b5693e695efa.png)
my doom config:
init.el:
![image](https://user-images.githubusercontent.com/43701982/100374641-d75a3780-3021-11eb-8a32-a4c788666ce7.png)

![image](https://user-images.githubusercontent.com/43701982/100374310-4e430080-3021-11eb-93ef-b96f608dbd1b.png)
sorry for bad english

**Comment by ericdallo** [comment]
@MrMorteZw, could you try to recompile doom modules with that config?
`doom sync` or `doom build -f`

**Comment by MrMorteZw** [comment]
for doom build -f:
! Unrecognized switch "-f"
for rm -rfv ~/.emacs.d/.local/straight/repos/lsp-{dart,mode} and then doom sync:
```
doom sync
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    > Updating recipe repos...
    → Cloning lsp-mode...for emacsmirror-mirror...
            → Cloning lsp-mode...done
    → Cloning lsp-dart...
    → Cloning lsp-dart...done
    - No packages need to be installed
  > (Re)building packages...
    ✓ No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating autoloads file...
    > Generating autoloads file...
    > Byte-compiling autoloads file...
    ✓ Generated .local/autoloads.27.1.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished in 119.2413s


```
and it work thank you
