### ISSUE TITLE
Could `flutter format` be used for indentation?

### ISSUE THREAD

**Issue by mgalgs** [emacs-lsp/lsp-dart#82]
It seems that `flutter format` is used in Android Studio and others for the code formatting backend. Could `lsp-dart` be made to do that as well or is that totally outside the Emacs paradigm of code indentation?

I guess I could set a save hook to just format externally and replace the buffer content pre-save, but wanted to see if there's any way to get it to work natively.

**Comment by ericdallo** [comment]
The format is already provided by the server(Dart SDK) which is the same from dartfmt, so I think already works pretty well.
What issues you have running `lsp-format-buffer`?

Check the format section of the docs too: https://emacs-lsp.github.io/lsp-mode/page/main-features/#formatting

**Comment by mgalgs** [comment]
aaah ok should be fine then. I noticed that spacing is different when I indent with Emacs vs Android Studio so I thought it was using a different underlying engine, but playing with it some more it's looking great. Thanks!
