### ISSUE TITLE
Customize height of *Flutter :: debug out" buffer when running dap-debug

### ISSUE THREAD

**Issue by m0rtis0** [emacs-lsp/lsp-dart#84]
**Describe the bug**
Add the ability to customize the height of the debug out buffer or remember from last adjusted size.

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages.

**To Reproduce**
Run dap debug

**Expected behavior**
Presence of a configuration variable to adjust the height of the buffer or automatically set to last present size

**Screenshots**

**Version**
Include here the result of: <kbd>M-x</kbd> `lsp-dart-version`
[LSP Dart] 1.17.9 at 2020.12.31 @ Emacs 27.1
[Dart SDK] Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "linux_x64"

**Comment by ericdallo** [comment]
Thanks for the suggestion, but this should be done in `dap-mode`
