### ISSUE TITLE
custom template is invalid  

### ISSUE THREAD

**Issue by guzishiwo** [emacs-lsp/lsp-dart#85]
**Describe the bug**
1. I need to specify the target file `lib/main_dev.dart`, so I set a custom template from the document, and then I execute the command `dap-debug` select the template just now， 
```dart
(use-package lsp-dart
  :ensure t
  :hook
  (dart-mode . lsp)
  :init
  (setq lsp-dart-flutter-sdk-dir "~/development/flutter/")
  (dap-register-debug-template "Flutter :: dev"
                               (list :program "lib/main_dev.dart"))
  )

```
> user-error: (:name Flutter :: dev :program lib/main_dev.dart) does not specify :type

2. If I click the run command on the main function and select a device, then it fails.
 > Message: Debug session process exited with status: exited abnormally with code 1

**Version**
[LSP Dart] 1.17.9 (package: 20201118.205) at 2021.01.03 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"

**Comment by ericdallo** [comment]
Hi @guzishiwo, did you run `dap-dart-setup` before?

**Comment by ericdallo** [comment]
Also, I think the correct template would be:
```elisp
(dap-register-debug-template "Flutter :: dev"
                             (list :type "flutter"
                                   :program "lib/main_dev.dart"))
```

**Comment by guzishiwo** [comment]
> Also, I think the correct template would be:
> 
> ```emacs-lisp
> (dap-register-debug-template "Flutter :: dev"
>                              (list :type "flutter"
>                                    :program "lib/main_dev.dart"))
> ```
> 
> As type is the only required argument, we need to know if this is a `flutter` debug template or a `dart` one

Thank you for your prompt reply 😁  . According to what you said, the template problem can be solved。 I choose a custom template, run `dap-dart-setup`。there are some error logs when it is running. I hope you can help me.

- Message buffer
```sh
Debug session process exited with status: exited abnormally with code 1
```

- Flutter Run stderrr buffer
```sh
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module '/Users/rrr/.emacs.d/.extension/vscode/Dart-Code.Dart-Code/extension/out/dist/debug.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Process Flutter Run stderr finished
```

**Comment by ericdallo** [comment]
Hum, the debug was not properly installed I think, also I saw that you have an outdated `lsp-dart`, could you make sure you have `lsp-mode`, `lsp-dart` and `dap-mode` updated?

**Comment by guzishiwo** [comment]
> Hum, the debug was not properly installed I think, also I saw that you have an outdated `lsp-dart`, could you make sure you have `lsp-mode`, `lsp-dart` and `dap-mode` updated?

I tried to reinstall the package and no effect, but I found that the .emacs.d/.extension/vscode/Dart-Code.Dart-Code/3.17.0 folder was empty, so I `deleted .emacs.d/. Extension/vscode` folder, then re-run dap-dart-setup, thank you very much for your prompt reply, hope this can help others.

**Comment by ericdallo** [comment]
Yeah, we should improve how dap-mode download the debug extension to avoid these cases ;)
