### ISSUE TITLE
Unable to debug running Flutter app

### ISSUE THREAD

**Issue by siraben** [emacs-lsp/lsp-dart#86]
**Describe the bug**
I started the app on my Android device using `flutter-run` and started `dap-mode`, selected the device but the debugger process failed.

**To Reproduce**
Go into a flutter project, perform `M-x flutter-run`, then let it compile and run, then `M-x dap-mode` to launch the debugger.

**Expected behavior**
The debugger should attach the running app.

**Logs**
```
Error: Cannot find module '/Users/siraben/.emacs.d/.extension/vscode/Dart-Code.Dart-Code/3.17.0/extension/out/dist/debug.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Process Flutter :: Debug stderr finished
```

**Version**
```
[LSP Dart] 1.17.11 (package: 20201206.1725) at 2021.01.05 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
```

**Comment by ericdallo** [comment]
Hi @siraben, did you run `dap-drart-setup`?
If so, could you try removing the debugger extension downloaded and running again?

**Comment by siraben** [comment]
Fixed by running `dap-dart-setup` with a prefix argument, thanks!
