### ISSUE TITLE
lsp-dart constantly throwing error

### ISSUE THREAD

**Issue by serezlan** [emacs-lsp/lsp-dart#88]
Hello,

I am new to dart and I've ben trying to start dart dev today. After following instruction on how to install lsp-dart, I open a new dart file and everytime I type, I have error thrown on message buffer. Also completion not working.

System:
=========
Debian 10
#("[LSP Dart] 1.17.11 at 2021.01.08 @ Emacs 27.1.90
[Dart SDK] Dart SDK version: 2.10.4 (stable) (Unknown timestamp) on \"linux_x64\"
Error message:
=======
Debugger entered--Lisp error: (wrong-type-argument listp [#<hash-table equal 4/65 0x1582d22d3809>])
  lsp-dart-flutter-widget-guide--outline->guides(#<hash-table equal 5/65 0x1582d23a0d69>)
  lsp-dart-flutter-widget-guide-check(#<hash-table equal 2/65 0x1582d1fc2645>)
  run-hook-with-args(lsp-dart-flutter-widget-guide-check #<hash-table equal 2/65 0x1582d1fc2645>)
  #f(compiled-function (workspace notification) #<bytecode 0x1582d2b6b599>)(#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 13/65 0x1582d2c3f025> :registered-server-capabilities (#s(lsp--registered-capability :id "3" :method "textDocument/foldingRange" :options #<hash-table equal 1/65 0x1582d2292b99>) #s(lsp--registered-capability :id "2" :method "textDocument/rename" :options #<hash-table equal 2/65 0x1582d1fa4e45>) #s(lsp--registered-capability :id "1" :method "textDocument/codeAction" :options #<hash-table equal 2/65 0x1582d2290711>) #s(lsp--registered-capability :id "0" :method "textDocument/formatting" :options #<hash-table equal 1/65 0x1582d22906f1>)) :root "/tmp/delta" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x1582d2b6b635>) :test\? #f(compiled-function () #<bytecode 0x1582d2b6b649>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 4/65 0x1582d2b6b655> :request-handlers #<hash-table equal 1/65 0x1582d2b6b77d> :response-handlers #<hash-table eql 0/65 0x1582d2b6b79d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x1582d2b6c885> :action-handlers #<hash-table equal 0/65 0x1582d2b6cef9> :major-modes (dart-mode) :activation-fn nil :priority -1 :server-id dart_analysis_server :multi-root nil :initialization-options ((onlyAnalyzeProjectsWithOpenFiles . t) (suggestFromUnimportedLibraries . t) (closingLabels . t) (outline . t) (flutterOutline . t)) :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x1582d2b6b55d>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn lsp-dart--activate-features :async-request-handlers #<hash-table equal 0/65 0x1582d2b6d1f1> :download-server-fn nil :download-in-progress? nil :buffers nil) :host-root nil :proc #<process dart_analysis_server> :cmd-proc #<process dart_analysis_server> :buffers (#<buffer main.dart>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x1582d2c2ed45> :watches #<hash-table equal 0/65 0x1582d2c2ef75> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x1582d2c2ef95> :work-done-tokens #<hash-table equal 0/65 0x1582d2c2f81d>) #<hash-table equal 2/65 0x1582d1fc2645>)
  lsp--on-notification(#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 13/65 0x1582d2c3f025> :registered-server-capabilities (#s(lsp--registered-capability :id "3" :method "textDocument/foldingRange" :options #<hash-table equal 1/65 0x1582d2292b99>) #s(lsp--registered-capability :id "2" :method "textDocument/rename" :options #<hash-table equal 2/65 0x1582d1fa4e45>) #s(lsp--registered-capability :id "1" :method "textDocument/codeAction" :options #<hash-table equal 2/65 0x1582d2290711>) #s(lsp--registered-capability :id "0" :method "textDocument/formatting" :options #<hash-table equal 1/65 0x1582d22906f1>)) :root "/tmp/delta" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x1582d2b6b635>) :test\? #f(compiled-function () #<bytecode 0x1582d2b6b649>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 4/65 0x1582d2b6b655> :request-handlers #<hash-table equal 1/65 0x1582d2b6b77d> :response-handlers #<hash-table eql 0/65 0x1582d2b6b79d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x1582d2b6c885> :action-handlers #<hash-table equal 0/65 0x1582d2b6cef9> :major-modes (dart-mode) :activation-fn nil :priority -1 :server-id dart_analysis_server :multi-root nil :initialization-options ((onlyAnalyzeProjectsWithOpenFiles . t) (suggestFromUnimportedLibraries . t) (closingLabels . t) (outline . t) (flutterOutline . t)) :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x1582d2b6b55d>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn lsp-dart--activate-features :async-request-handlers #<hash-table equal 0/65 0x1582d2b6d1f1> :download-server-fn nil :download-in-progress? nil :buffers nil) :host-root nil :proc #<process dart_analysis_server> :cmd-proc #<process dart_analysis_server> :buffers (#<buffer main.dart>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x1582d2c2ed45> :watches #<hash-table equal 0/65 0x1582d2c2ef75> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x1582d2c2ef95> :work-done-tokens #<hash-table equal 0/65 0x1582d2c2f81d>) #<hash-table equal 3/65 0x1582d22eacd1>)
  lsp--parser-on-message(#<hash-table equal 3/65 0x1582d22eacd1> #s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 13/65 0x1582d2c3f025> :registered-server-capabilities (#s(lsp--registered-capability :id "3" :method "textDocument/foldingRange" :options #<hash-table equal 1/65 0x1582d2292b99>) #s(lsp--registered-capability :id "2" :method "textDocument/rename" :options #<hash-table equal 2/65 0x1582d1fa4e45>) #s(lsp--registered-capability :id "1" :method "textDocument/codeAction" :options #<hash-table equal 2/65 0x1582d2290711>) #s(lsp--registered-capability :id "0" :method "textDocument/formatting" :options #<hash-table equal 1/65 0x1582d22906f1>)) :root "/tmp/delta" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x1582d2b6b635>) :test\? #f(compiled-function () #<bytecode 0x1582d2b6b649>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 4/65 0x1582d2b6b655> :request-handlers #<hash-table equal 1/65 0x1582d2b6b77d> :response-handlers #<hash-table eql 0/65 0x1582d2b6b79d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x1582d2b6c885> :action-handlers #<hash-table equal 0/65 0x1582d2b6cef9> :major-modes (dart-mode) :activation-fn nil :priority -1 :server-id dart_analysis_server :multi-root nil :initialization-options ((onlyAnalyzeProjectsWithOpenFiles . t) (suggestFromUnimportedLibraries . t) (closingLabels . t) (outline . t) (flutterOutline . t)) :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x1582d2b6b55d>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn lsp-dart--activate-features :async-request-handlers #<hash-table equal 0/65 0x1582d2b6d1f1> :download-server-fn nil :download-in-progress? nil :buffers nil) :host-root nil :proc #<process dart_analysis_server> :cmd-proc #<process dart_analysis_server> :buffers (#<buffer main.dart>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x1582d2c2ed45> :watches #<hash-table equal 0/65 0x1582d2c2ef75> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x1582d2c2ef95> :work-done-tokens #<hash-table equal 0/65 0x1582d2c2f81d>))
  #f(compiled-function (proc input) #<bytecode 0x1582d2c2f9c9>)(#<process dart_analysis_server> "{\"method\":\"dart/textDocument/publishClosingLabels\"...")

How to reproduce:
==============
1. Open a blank dart file
2. 2. Type something 
3. 3. Error is thrown

**Comment by ericdallo** [comment]
Could you confirm if it happens with `(setq lsp-dart-flutter-widget-guides nil)` in your `init.el` before open the file?

**Comment by serezlan** [comment]
Works beautifully.
Thank you
