### ISSUE TITLE
Error when calling lsp-dart-show-outline and lsp-dart-show-flutter-outline

### ISSUE THREAD

**Issue by ram535** [emacs-lsp/lsp-dart#9]
I am running:

```
GNU Emacs 28.0.50


Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (2 weeks ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
```

My relevant configuration.
```
(use-package lsp-mode
  :straight (lsp-mode :type git :host github :repo "emacs-lsp/lsp-mode")
  :commands (lsp lsp-deferred))

(use-package lsp-dart
  :straight (lsp-dart :type git :host github :repo "emacs-lsp/lsp-dart")
  :custom
  (lsp-dart-sdk-dir "~/bin/flutter/bin/cache/dart-sdk/")
  :hook (dart-mode . lsp-deferred))

(use-package treemacs)

(use-package lsp-treemacs
  :after lsp-mode
  :config
  (lsp-treemacs-sync-mode 1))
```
Before calling `lsp-dart-show-outline or lsp-dart-show-flutter-outline`.

![1587522103880](https://user-images.githubusercontent.com/9011002/79934257-0020ab80-8407-11ea-92e3-9a5253524cad.jpg)

After calling `lsp-dart-show-outline or lsp-dart-show-flutter-outline`.
Notice that the color indicator disapear. 
![1587522117124](https://user-images.githubusercontent.com/9011002/79934311-175f9900-8407-11ea-8a70-54db1f1377a3.jpg)

**Comment by ericdallo** [comment]
This is odd, I tested with the latest `treemacs` and `lsp-treemacs` versions and could not reproduce this... Could you try to enable the debug on your emacs session to give us more feedback on why this `treemacs--maybe-move-forward` is void? I think [`debug-on-error`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Error-Debugging.html) could help

**Comment by ericdallo** [comment]
If you are using the latest release `1.6.7` I included a new command, could you try `M-x` `lsp-dart-version`?

**Comment by ram535** [comment]
M-x lsp-dart-version.
```
[LSP Dart] 1.6.7 at 2020.04.22 @ Emacs 28.0.50
```

debug-on-error
```
Debugger entered--Lisp error: (void-function treemacs--maybe-move-forward)
  treemacs--maybe-move-forward()
  treemacs--do-expand-generic(#<marker at 1 in *Dart Outline*>)
  treemacs-GENERIC-extension()
  lsp-treemacs-initialize()
  lsp-treemacs-render(((:key #("main ()" 4 7 (face lsp-lens-face)) :label #("main ()" 4 7 (face lsp-lens-face)) :icon method :children #f(compiled-function (&rest _) #<bytecode -0x1eee2c02b5942f2e>) :ret-action #f(compiled-function (&rest _) #<bytecode -0x1888279bae44bd70>)) (:key "MyApp" :label "MyApp" :icon class :children #f(compiled-function (&rest _) #<bytecode -0x1eee2c02b08f7f2e>) :ret-action #f(compiled-function (&rest _) #<bytecode -0x1888279baea44970>)) (:key "MyHomePage" :label "MyHomePage" :icon class :children #f(compiled-function (&rest _) #<bytecode 0x48135d90ac0a0cc>) :ret-action #f(compiled-function (&rest _) #<bytecode -0x1888279bacd93970>)) (:key "_MyHomePageState" :label "_MyHomePageState" :icon class :children #f(compiled-function (&rest _) #<bytecode 0x1ad8b265fb6e078e>) :ret-action #f(compiled-function (&rest _) #<bytecode -0x1888279baa64c970>))) "Outline" t "*Dart Outline*")
  lsp-dart--render-outline-tree("file:///home/last/Projects/flutter/myapp/lib/main_..." [#<hash-table equal 4/4 0x157900e55e99> #<hash-table equal 4/4 0x157900e56835> #<hash-table equal 4/4 0x157900e58261> #<hash-table equal 4/4 0x157900e595b5>])
  lsp-dart--show-outline(#<buffer main_desktop.dart> nil)
  lsp-dart-show-outline(nil)
  funcall-interactively(lsp-dart-show-outline nil)
  call-interactively(lsp-dart-show-outline record nil)
  command-execute(lsp-dart-show-outline record)
  execute-extended-command(nil "lsp-dart-show-outline" nil)
  funcall-interactively(execute-extended-command nil "lsp-dart-show-outline" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by ericdallo** [comment]
Hum it looks like a treemacs error, could you try `treemacs` to check if treemacs is opening correctly the tree view for your project?

**Comment by ram535** [comment]
When running treemacs.

![1587597572176](https://user-images.githubusercontent.com/9011002/80042923-269d2000-84b5-11ea-85a9-f9c63fad1886.jpg)

**Comment by ericdallo** [comment]
The `lsp-dart-show-outline` implementation is similar to the `lsp-treemacs-symbol`, Can you please confirm again if `lsp-treemacs-symbol` is working?

**Comment by ram535** [comment]
It has a weird behavior.

When doing `lsp-treemacs-symbol`.
![1587603525687](https://user-images.githubusercontent.com/9011002/80047785-37ed2900-84c3-11ea-946c-af397aaf510b.jpg)

And after like 10 seconds, the symbols appear.
![1587603710788](https://user-images.githubusercontent.com/9011002/80047859-6408aa00-84c3-11ea-9c22-086f7226f8f8.jpg)

**Comment by ericdallo** [comment]
Oh, that's a good start point to investigate, I'll check `lsp-treemacs-symbols` and try to find what's is causing it.
Thanks, hope I find something soon :sweat_smile:

**Comment by ericdallo** [comment]
Nice, sorry for not noticing it before :)
