### ISSUE TITLE
Can't find Flutter SDK directory when using Nix

### ISSUE THREAD

**Issue by peterstuart** [emacs-lsp/lsp-dart#90]
I have installed Flutter using Nix, and since the Flutter package in NixPkgs does not expose the `cache/dart-sdk/bin/dart` etc. files that are used by lsp-dart, I need to manually configure `lsp-dart-flutter-sdk-dir` to point at the correct location. I'd rather not do this manually, since the path will change with every change to the Flutter package (and will potentially differ between different Flutter projects on the same machine).

I'm not very familiar with elisp, but I think the issue could potentially be solved here by changing the order in the following function to prefer:
1. `lsp-dart-flutter-sdk-dir`
2. `$FLUTTER_ROOT`
3. path based on `lsp-dart-flutter-executable`

```elisp
(defun lsp-dart-get-flutter-sdk-dir ()
  "Return the Flutter SDK path.
Check for `lsp-dart-flutter-sdk-dir` then
flutter executable on PATH then
FLUTTER_ROOT environment variable."
  (or lsp-dart-flutter-sdk-dir
      (-some-> (executable-find lsp-dart-flutter-executable)
        file-truename
        (locate-dominating-file "bin")
        file-truename)
      (getenv "FLUTTER_ROOT")))
```

Currently, setting `$FLUTTER_ROOT` seems to have no effect for me.

Am I missing some configuration that would let me do what I want here? If not, I'd be happy to try and make a change to support this.

For reference, the `shell.nix` I'm using for this project is this:

```nix
let pkgs = import <nixpkgs> { };
in pkgs.mkShell {
  buildInputs = with pkgs; [
    android-studio
    flutter
    git
    jdk
    nodejs-14_x
    nodePackages.firebase-tools
  ];

  shellHook = ''
    export USE_CCACHE=1
    export ANDROID_JAVA_HOME=${pkgs.jdk.home}
    export ANDROID_HOME=/home/peter/Android/Sdk
    export FLUTTER_SDK=${pkgs.flutter.unwrapped}
  '';
}
```

Thanks for your time and for this great mode! I was very pleased to discover that such great Flutter support was available for Emacs.

**Comment by ericdallo** [comment]
THanks for the feedback ❤️ 

Oh, good to see another NixOS user :D 
Unfortunately, this is an issue with how nixpkgs ship the flutter package, but the above code fits well with me and it works nice:
https://github.com/ericdallo/dotfiles/blob/master/.doom.d/config.el#L141-L146

LMK if you need any more help

**Comment by ericdallo** [comment]
Also, I'm not sure if there is anything we could do in lsp-dart to improve that, but let me know if you find any

**Comment by peterstuart** [comment]
Hmm, that doesn't seem to work for me for some reason. I get the same messages about not being able to find the analysis server, and if I inspect `lsp-dart-sdk-dir` in a Dart buffer it is `nil`. Any idea what could be going wrong? I copied your entire `lsp-dart` config exactly, with the exception of the `!` at the end of `use-package!`. (Maybe that's a doom thing?)

**Comment by ericdallo** [comment]
Yeah, its a doom thing 😅 
If `lsp-dart-sdk-dir` is not set, probably it's not finding the dart executable from the `when-let`, check if emacs is finding it via:
`M-x` `(executable-find "dart")`

**Comment by ericdallo** [comment]
Oh, probably is not finding indeed, I forget to mention that the issue with flutter from nixpkgs is that when you install it only adds the flutter executable to the PATH, so you need to install dart too AFAIK
c/c @thiagokokada

**Comment by thiagokokada** [comment]
Yeah, both Dart and Flutter needs to be in `environment.systemPackages` or the command `dart` will not be available in PATH (and the workaround from @ericdallo will not work).

BTW, not related to the problem itself but I recommend you to use Dart and Flutter from `nixpkgs-unstable`. I did some fixes that avoids Flutter to be build with the Dart that ships with it, and also reduced the derivation by almost 400MB.

**Comment by peterstuart** [comment]
Thank you both! That set me on the right track. I am using a different setup than you where flutter is not installed system-wide, so I ended up tweaking it a bit and ended up with this:

```elisp
(defun set-flutter-sdk-dir ()
  (direnv-update-environment)
  (setq lsp-dart-flutter-sdk-dir
        (string-trim-right (shell-command-to-string "echo $FLUTTER_SDK"))))

(use-package dart-mode
  :init
  (add-hook 'dart-mode-hook 'set-flutter-sdk-dir))
```

I have a `shell.nix` which installs flutter, and also sets `$FLUTTER_SDK` (`export FLUTTER_SDK=${pkgs.flutter.unwrapped}`), so after getting the correct environment with `(direnv-update-environment)`, I can use that value directly. 🥳

**Comment by KouAkitaki** [comment]
> Thank you both! That set me on the right track. I am using a different setup than you where flutter is not installed system-wide, so I ended up tweaking it a bit and ended up with this:
> 
> ```emacs-lisp
> (defun set-flutter-sdk-dir ()
>   (direnv-update-environment)
>   (setq lsp-dart-flutter-sdk-dir
>         (string-trim-right (shell-command-to-string "echo $FLUTTER_SDK"))))
> 
> (use-package dart-mode
>   :init
>   (add-hook 'dart-mode-hook 'set-flutter-sdk-dir))
> ```
> 
> I have a `shell.nix` which installs flutter, and also sets `$FLUTTER_SDK` (`export FLUTTER_SDK=${pkgs.flutter.unwrapped}`), so after getting the correct environment with `(direnv-update-environment)`, I can use that value directly.

This is working perfect for me. Thanks for sharing the setup!
