### ISSUE TITLE
Dart and Flutter Sdks paths missing when opening a non flutter project with emacs GUI  from outside the terminal 

### ISSUE THREAD

**Issue by zakariaz** [emacs-lsp/lsp-dart#95]
I Ran in an issue when lunching GUI emacs from  the gnome shell. lsp couldn't find the Flutter and Dart sdks .

When launching emacs from the terminal everything works correct except when it is a non flutter project.
The language server did not start and is reporting missing.

I have got the flutter sdk installed and it's path is added to my path variable.
I am using `GNU bash`.

I fixed the issue for me so i wanted to share it so maybe it is worth to inclued the fix in lsp-dart.

What i discoverd when researching the issue is that in GNU/linux distro (manjaro since i am using it) that when you launch GUI emacs it doesn't acces the shell variables defined in `.bashrc` or `.profile` ... etc. I don't know if it is valid for all GUI applications, i suppose it is not only true for emacs.

To get emacs know about the path of the flutter sdk, the only solution is to tell it by setting `lsp-dart-flutter-sdk-dir` but the probleme is if you are in a non flutter project, you can't get the path of the Dart sdk because the `lsp-dart-get-sdk-dir` form calls
`lsp-dart-get-flutter-sdk-dir` only when it is in a flutter project as you can see in it's implementation:
```
(defun lsp-dart-get-sdk-dir ()
  "Return the Dart SDK path.
Check for PATH environment variable.
When editing a Flutter project, the version of Dart included in the Flutter SDK
is used in preference."
  (or lsp-dart-sdk-dir
      (when (lsp-dart--flutter-project-p)
        (expand-file-name "bin/cache/dart-sdk/" (lsp-dart-get-flutter-sdk-dir)))
      (-some-> (executable-find "dart")
        file-truename
        (locate-dominating-file "bin")
        file-truename)))
```
unless you set the `lsp-dart-sdk-dir` variable your self which is annoying because you have to search for it. because it is nested inside the `path_to_flutter_skd/bin/cache/dart-sdk` and i had to read the source code of `dart` command inside the flutter sdk to get the path. maybe a more effective way is to search for it in google which i didn't. lol

The solution i came with is to remove the check for flutter projects so the `lsp-dart-get-sdk-dir` became that way:
```
(defun lsp-dart-get-sdk-dir ()
  "Return the Dart SDK path.
Check for PATH environment variable.
When editing a Flutter project, the version of Dart included in the Flutter SDK
is used in preference."
  (or lsp-dart-sdk-dir
       (expand-file-name "bin/cache/dart-sdk/" (lsp-dart-get-flutter-sdk-dir))
      (-some-> (executable-find "dart")
        file-truename
        (locate-dominating-file "bin")
        file-truename)))
```
that fixed the issue for me and i think it will avoid future user from filling bugs about that.

By the way `lsp-dart-get-flutter-sdk-dir` doesn't have to possibility to get the path when i lunch emacs from my application launcher. because it can't acces the updated `PATH` by `.bashrc`

So i had to set the `lsp-dart-flutter-sdk-dir` variable my self to the proper path so i can get `lsp` working which is better that setting them all together.

if you find the fix interesting i can make a pull request to get it merged. of maybe you suggest some improvements.

Thank you for the amazing work.

[LSP Dart] 1.17.12 (package: 20210110.15) at 2021.02.12 @ Emacs 27.1
[Dart SDK] Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "linux_x64"

**Comment by ericdallo** [comment]
Thank you! and sorry for the need to debug all of that 😅 
The issue with your suggestion is that it won't find the correct dart sdk for Dart only projects, not flutter :/ 
If you remove the check if it's a flutter project, `(expand-file-name "bin/cache/dart-sdk/" (lsp-dart-get-flutter-sdk-dir))` will probably blow up the code for Dart only projects.

You can test it with this sample project: https://github.com/ericdallo/dart_sample and https://github.com/ericdallo/flutter_sample

**Comment by zakariaz** [comment]
I'll taste it and will give you feedback

**Comment by zakariaz** [comment]
Actually what is wired is when i byte compile lsp-dart there is two files that doesn't byte compile `lsp-dart-pkg.el` and `lsp-dart-autoloads.el`. The language server fails to start. when i remove the `.elc` files and restart emacs it  everything works!

**Comment by ericdallo** [comment]
That is I was talking about, with your modification, users that use lsp-dart with Dart out of the box without any further configuration will stop working since they need to set `lsp-dart-sdk-dir` manually.

I still don't get it why you need to remove the `(when (lsp-dart--flutter-project-p)`, that checks if the current buffer/project is a flutter one, not a dart one, we probably need to investigate why `(lsp-dart--flutter-project-p)` is returning false for you in this case.

**Comment by zakariaz** [comment]
> That is I was talking about, with your modification, users that use lsp-dart with Dart out of the box without any further configuration will stop working since they need to set `lsp-dart-sdk-dir` manually.

I see know the issue but what i don't understand is why when i am in a dart or a flutter project, lsp dart can't get the path to the dart sdk with the compiled version in contrast with the non compiled version of lsp dart. this is something related to emacs internals i think. I tried to know to understand emacs better.

> I still don't get it why you need to remove the `(when (lsp-dart--flutter-project-p))`, that checks if the current buffer/project is a flutter one, not a dart one, we probably need to investigate why `(lsp-dart--flutter-project-p)` is returning false for you in this case.

I don't necessarily want to remove it. the issue that i am addressing is the following:

when i install the flutter sdk and the only dart sdk installed is the flutter one. there is no way for me to a access this sdk outside of a flutter project -of course that is related to emacs when i start it from the gnome shell or  the application finder in XFCE- because emacs doesn't have acces to the `PATH` variable.

What i understood from the code of `lsp-dart-get-sdk-dir` is that it only get the dart sdk path that ships with flutter when i am in a flutter project. for the others, it checks the dart executable and tries to construct its path which is impossible when the `PATH` is not available to emacs as stated earlier. so the only option in that case is to initialize both variables related to flutter and dart sdk paths manually.
I thought it would be nice if all of that is handled automatically by `lsp-dart` or a least just set the path to the flutter sdk and everythings else is handled, since lot of people would set it anyway in their `$PATH` and in their IDE like android studio. this can be implemented in different ways and i thought of one way. That is why i  came with this suggestion.

The only benefit that i see with testing flutter project and only constructing the dart sdk path from the flutter one is when i have 2 dart sdks installed in my system and i want to use the flutter one in a flutter project and the none flutter one in the dart project which is logical with this system setting.

Actually That is not a big issue to set both skds paths in init.el. I though it would be nicer to have it handled automatically or at least have it mentioned in doc.

**Comment by zakariaz** [comment]
I solved the problem by creating an `emacs.desktop` file in `~/.local/share/applications/` so now emacs has access to variables sourced from my `.bashrc`

I still had issues in non flutter projects with the language server. it gets an improper path so i solved it by setting `lsp-dart-sdk-dir` manually

**Comment by ericdallo** [comment]
I see, thanks for the detailed explanation, I agree that it'd be great if lsp-dart just works automatically, but we need to take care when changing that logic since it can work for you and break for other :/ 
I can't see an easy solution for that issue but I think the `lsp-dart-sdk-dir` variables exists for fixing those corner cases indeed.

No problem, I'm not a native speaker too ;)
