### ISSUE TITLE
No Flutter outline data found when using Doom Emacs

### ISSUE THREAD

**Issue by DanMossa** [emacs-lsp/lsp-dart#98]
**Describe the bug**
My `config.el` is 
```
(use-package! lsp-mode)
(use-package! lsp-dart
  :hook (dart-mode . lsp))
(use-package! yasnippet
  :config (yas-global-mode))
(use-package! lsp-ui)
(use-package! hover)
```
and my `packages.el` is 
```
;; Install use-package
(package! lsp-mode)
(package! lsp-dart)
(package! yasnippet)
(package! lsp-ui)
(package! hover)
```
But inside of doom emacs, when I type M-x select `lsp-dart-show-flutter-outline` I get 
> [LSP Dart] No Flutter outline data found [3 times]

**To Reproduce**
Setup your config.el and packages.el like above. Type `doom sync` and then `doom/reload`

**Expected behavior**
Flutter outlines would appear

**Version**
Include here the result of: <kbd>M-x</kbd> `lsp-dart-version`
[LSP Dart] 1.18.1 at 2021.04.09 @ Emacs 27.2
[Dart SDK] Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"

**Comment by ericdallo** [comment]
Hey @DanMossa, you are missing [lsp-treemacs](https://github.com/emacs-lsp/lsp-treemacs) 😅 
This is something that I have a PR ready to open on doom-emacs side to add a flag for treemacs module, I'll open as soon doom-emacs back to accept PRs 🤞🏻 

LMK if have any issue after installing lsp-treemacs correctly

**Comment by andrewebdev** [comment]
I have the exact same problem. I do have lsp-treemacs installed.

**Comment by blez** [comment]
Yeah, same for me
