### ISSUE TITLE
Apps Wont run 

### ISSUE THREAD

**Issue by CadeMichael** [emacs-lsp/lsp-dart#99]
**Describe the bug**
Trying to run the App will create an instance of the emulator but when hitting run again two options pop up
emulator 
android x86

so first press of `run` brings up emulator second press brings up option to run on emulator and when selected it gives the error below. 

[LSP Dart] [FLUTTER ERROR]  The Android emulator exited with code 1 during startup
[LSP Dart] [FLUTTER ERROR]  Android emulator stderr:
[LSP Dart] [FLUTTER ERROR]  Address these issues and try again.

I am using doom emacs with the following packages related to dart installed 
(dart + flutter + lsp)

and I have lsp mode enabled 
**Expected behavior**
the app will open with full highlighting and auto-correct but will not let me run the app within emacs. 

**Version**
Include here the result of: <kbd>M-x</kbd> `lsp-dart-version`
[LSP Dart] 1.18.0 at 2021.04.14 @ Emacs 27.2
[Dart SDK] Dart VM version: 2.8.0-dev.18.0.flutter-1402e8e1a4 (be) (Thu Mar 26 13:15:18 2020 +0000) on "linux_x64"

**Comment by CadeMichael** [comment]
I get the same error on my mac os machine running emacs-mac with the same version of LSP dart if that helps

**Comment by ericdallo** [comment]
Tanks for the report, running one time only should work as expected, lsp-dart should start the emulator and then run the app, it may take a while the first run, could you share more details or a video showing how it's behaving?

**Comment by CadeMichael** [comment]
I don't think that it is running in the background without showing any signs (build gradle, initialize, etc) as even if I connect a physical device I am unable to run the app and an error is thrown during the first press of run. However if the former is the case  is there a way to see the app outputs such as print statements? when connecting a physical device this is the error when trying to run 

`Debug session process exited with status: exited abnormally with code 1`

**Comment by ericdallo** [comment]
Yes, you can check the `dap-output` buffer for logs

**Comment by ericdallo** [comment]
Or `M-x` `dap-go-to-output-buffer`

**Comment by CadeMichael** [comment]
Nothing is running in the background; the output buffer is empty.

**Comment by CadeMichael** [comment]
```
Session restored. Welcome back.
LSP :: Guessed project root is ~/Desktop/GXC/stt_demo/lib
LSP :: Connected to [dart_analysis_server:37745/starting].
LSP :: dart_analysis_server:37745 initialized successfully
Lsp-Dart-Dap mode enabled in current buffer
dap--cur-session-or-die: No active current session
```

**Comment by ericdallo** [comment]
Alright, I'll try to reproduce the issue with my [flutter_sample](https://github.com/ericdallo/flutter_sample) project, it'd be nice if you could confirm the repro on that project as well

**Comment by CadeMichael** [comment]
Thank you; and how do you mean sorry? It is also reproducible with the default main.dart in an empty flutter project. Across versions of flutter for me. (same issue on laptop and desktop)

**Comment by ericdallo** [comment]
@CadeMichael I just tested and it worked properly with a physical device.

One thing I remembered, did you run `dap-dart-setup` before?

**Comment by CadeMichael** [comment]
I did run dap-dart-setup but I cannot tell if it is doing anything. I am still unable to run on a physical or emulated device.  the output in the buffer is as follows (from trying to run on an emulator and then on a physical device)...
```
LSP :: Guessed project root is ~/Desktop/GXC/stt_demo/lib
LSP :: Connected to [dart_analysis_server:18535/starting].
LSP :: dart_analysis_server:18535 initialized successfully
Beginning of buffer [11 times]
[LSP Dart] [FLUTTER ERROR]  Error 1 retrieving device properties for ro.product.cpu.abi:
[LSP Dart] [FLUTTER ERROR]  error: closed

[LSP Dart] [FLUTTER ERROR]  Error 1 retrieving device properties for ro.product.cpu.abi:
[LSP Dart] [FLUTTER ERROR]  adb: device ’emulator-5554’ not found

dap--cur-session-or-die: No active current session
Debug session process exited with status: exited abnormally with code 1

Debug session process exited with status: exited abnormally with code 1

Beginning of buffer
```

I am not sure if this is because I am using Doom Emacs or if there is a compatibility issue, but thank you for trying to help! 

Cade

**Comment by ericdallo** [comment]
That's odd, I use doom-emacs as well, [here is my config](https://github.com/ericdallo/dotfiles/tree/master/.doom.d), but I don't see how this is affecting the debug.
@CadeMichael  could you get the content of the `*LSP Dart - Flutter daemon*` buffer to see if there is anything odd there?

**Comment by CadeMichael** [comment]
I see that in your configs you not only had `+lsp` in init.el but also installed dart-lsp and dap in packages.el. Is this the correct way to install these packages? I was able to get dap somewhat working (as you can see the LSP is connected and I am getting dap commands offered as suggestions) just by enabling `lsp` and `(dart +flutter +lsp)` in my init.el.

**Comment by ericdallo** [comment]
No, I'm about to remove that, I used to use that before doom-emacs has those packages built-in.

I think to enable dap via doom-emacs, you need to include the :debugger and :tools +lsp

**Comment by CadeMichael** [comment]
Ahh that would make sense. Would it look something like this. 

```lisp
       :tools
       ;;ansible
       debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;;rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       ;;tty               ; improve the terminal Emacs experience

       ;; ___
       ;;/\_ \
       ;;\//\ \      __      ___      __   __  __     __       __      __    ____
       ;;  \ \ \   /'__`\  /' _ `\  /'_ `\/\ \/\ \  /'__`\   /'_ `\  /'__`\ /',__\
       ;;   \_\ \_/\ \L\.\_/\ \/\ \/\ \L\ \ \ \_\ \/\ \L\.\_/\ \L\ \/\  __//\__, `\
       ;;   /\____\ \__/.\_\ \_\ \_\ \____ \ \____/\ \__/.\_\ \____ \ \____\/\____/
       ;;   \/____/\/__/\/_/\/_/\/_/\/___L\ \/___/  \/__/\/_/\/___L\ \/____/\/___/
       ;;                             /\____/                  /\____/
       ;;                             \_/__/                   \_/__/

       :lang
       ;;agda              ; types of types of types of types...
       cc                ; C/C++/Obj-C madness *** Don't forget to install irony server ***
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       (dart +flutter +lsp)   ; paint ui and not much else
```

**Comment by ericdallo** [comment]
yes, it looks correct

**Comment by CadeMichael** [comment]
I'm still receiving this error `[LSP Dart] [FLUTTER ERROR]  Error 1 retrieving device properties for ro.product.cpu.abi:
[LSP Dart] [FLUTTER ERROR]  adb: device ’emulator-5554’ not found` and the same error as before when trying on physical hardware. When you run dap-dart-setup does anything happen or does the command window just close?

**Comment by ericdallo** [comment]
If you already have setted up it won't print nothing, that's something that we can improve, but for now you can remove `~/.emacs.d/.extensions/vscode` and run `dap-dart-setup` again to download the debugger

**Comment by CadeMichael** [comment]
I think that did the trick! Thank you for being very patient and helping me with this issue.

**Comment by ericdallo** [comment]
Glad to hear :)
I'll try to improve the dap-dart-setup, probably you had a outdated/corrupted debugger downloaded.
